# Script per il sistema della Fama #
#
# PlaceHolder per la FAMA: %skript_fame::{player}%
#
# PERMESSI
#
# FAMA
# - fame.idle.notify
# - fame.check.self
# - fame.check.other
# - fame.top
# - fame.reset.self
# - fame.reset.other
# - fame.set
# - fame.add
# - fame.remove
# - fame.idle.toggle
# - fame.admin.help
# - fame.help
# - fame.reload
# - fame.commands
# - fame.*
#

options:
    prefix: &8[&b&lFAMA&8]
    error: &8[&4&lFAMA&8]
    
    version: 4.2

    confirm_sound: block.note_block.pling
    error_sound: entity.enderman.teleport
    check_sound: entity.player.levelup
    what_sound: entity.villager.trade

on load:
    if {fame.idle} isn't set:
        set {fame.idle} to true
    
on join:
    if {fame::%player%} isn't set:
        set {fame::%player%} to 0

every 5 hours:
    loop all players:
        set {_fame-5} to a random integer between 300 and 400
        set {_fame-4} to a random integer between 250 and 300
        set {_fame-3} to a random integer between 200 and 250
        set {_fame-2} to a random integer between 100 and 200
        set {_fame-1} to a random integer between 50 and 100
        set {_fame0} to a random integer between 10 and 50
        set {_fame1_1} to a random integer between 50 and 75
        set {_fame1_2} to a random integer between 50 and 125
        set {_fame2_1} to a random integer between 125 and 175
        set {_fame2_2} to a random integer between 125 and 200
        set {_fame3_1} to a random integer between 225 and 250
        set {_fame3_2} to a random integer between 225 and 275
        set {_fame4_1} to a random integer between 250 and 325
        set {_fame4_2} to a random integer between 250 and 350
        set {_fame5_1} to a random integer between 350 and 450
        set {_fame5_2} to a random integer between 450 and 500
        if loop-player is online:
            if {fame::%loop-player%} < 1000000:
                if {fame.idle} is true:
                    if {rank.%loop-player%} is {rank.alignment.-5.%loop-player%}:
                        add {_fame-5} to {fame::%loop-player%}
                        send "&6+%{_fame-5}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.-5.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame-5}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.-4.%loop-player%}:
                        add {_fame-4} to {fame::%loop-player%}
                        send "&6+%{_fame-4}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.-4.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame-4}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.-3.%loop-player%}:
                        add {_fame-3} to {fame::%loop-player%}
                        send "&6+%{_fame-3}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.-3.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame-3}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.-2.%loop-player%}:
                        add {_fame-2} to {fame::%loop-player%}
                        send "&6+%{_fame-2}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.-2.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame-2}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.-1.%loop-player%}:
                        add {_fame-1} to {fame::%loop-player%}
                        send "&6+%{_fame-1}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.-1.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame-1}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.0.%loop-player%}:
                        add {_fame0} to {fame::%loop-player%}
                        send "&6+%{_fame0}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.0.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame0}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.1.%loop-player%}:
                        add {_fame1_1} to {fame::%loop-player%}
                        send "&6+%{_fame1_1}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.1.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame1_1}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.2.%loop-player%}:
                        add {_fame1_2} to {fame::%loop-player%}
                        send "&6+%{_fame1_2}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.2.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame1_2}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.3.%loop-player%}:
                        add {_fame2_1} to {fame::%loop-player%}
                        send "&6+%{_fame2_1}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.3.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame2_1}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.4.%loop-player%}:
                        add {_fame2_2} to {fame::%loop-player%}
                        send "&6+%{_fame2_2}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.4.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame2_2}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.5.%loop-player%}:
                        add {_fame3_1} to {fame::%loop-player%}
                        send "&6+%{_fame3_1}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.5.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame3_1}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.6.%loop-player%}:
                        add {_fame3_2} to {fame::%loop-player%}
                        send "&6+%{_fame3_2}% Fama! (Tempo di gioco) &b&l>> &6(%{rank.alignment.6.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame3_2}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.7.%loop-player%}:
                        add {_fame4_1} to {fame::%loop-player%}
                        send "&6+%{_fame4_1}% Fama! (Tempo di gioco) &b&l>> %{rank.alignment.7.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame4_1}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.8.%loop-player%}:
                        add {_fame4_2} to {fame::%loop-player%}
                        send "&6+%{_fame4_2}% Fama! (Tempo di gioco) &b&l>> (%{rank.alignment.8.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame4_2}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.9.%loop-player%}:
                        add {_fame5_1} to {fame::%loop-player%}
                        send "&6+%{_fame5_1}% Fama! (Tempo di gioco) &b&l>> (%{rank.alignment.9.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame5_1}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                    else if {rank.%loop-player%} is {rank.alignment.10.%loop-player%}:
                        add {_fame5_2} to {fame::%loop-player%}
                        send "&6+%{_fame5_2}% Fama! (Tempo di gioco) &b&l>> (%{rank.alignment.10.%loop-player%}%&6)" to loop-player
                        send action bar "&2&l⌚ TEMPO DI GIOCO &a+%{_fame5_2}% Fama &6(%regex({fame::%loop-player%})% totale)" to loop-player
                        stop
                else:
                    if loop-player has permission "fama.idle.notify":
                        send "{@error} &cNon posso assegnare la Fama ai giocatori perché l'assegnazione automatica è disattivata!" to loop-player
                        send "{@error} &cPer attivarla, clicca <cmd:/fama idle>&6qui&c." to loop-player
                        stop
            else:
                send "{@prefix} &6Hai raggiunto la reputazione più alta del server, pertanto non riceverai più Fama in modo automatico." to loop-player
                send "{@prefix} &bPuoi comunque guadagnarla giocando normalmente nel server!" to loop-player
                stop
        
command /fama [<text>] [<offline player>] [<number>]:
    aliases: /f
    description: Visualizza quanta Fama possiedi.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.check.self":
                            send "{@prefix} &6Hai accumulato &c%regex({fame::%player%})% Fama&6."
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    
            else if arg-1 is "check":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.check.other":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama check <&egiocatore&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if arg-3 isn't set:
                        if player has permission "fama.check.other":
                            if {fame::%arg-2%} is set:
                                send "{@prefix} &c%arg-2% &6ha accumulato &e%regex({fame::%arg-2%})% Fama&6."
                                stop
                            else:
                                send "{@error} &6%arg-2% &cnon ha ancora giocato in questo server!"
                                play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else:
                        if player has permission "fama.check.other":
                            send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
            
            else if arg-1 is "top":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.top":
                            loop {fame::*}:
                                add 1 to {_size}
                                if {_low.to.high.list::%loop-value%} isn't set:
                                    set {_low.to.high.list::%loop-value%} to loop-index
                                else:
                                    set {_n} to 0
                                    loop {_size} times:
                                        set {_n} to {_n}+1
                                        {_low.to.high.list::%loop-value-1%.%{_n}%} isn't set
                                        set {_low.to.high.list::%loop-value-1%.%{_n}%} to loop-index
                                        stop loop
                            wait 1 tick
                            set {_n} to size of {_low.to.high.list::*}
                            loop {_low.to.high.list::*}:
                                set {_high.to.low.list::%{_n}%} to loop-value
                                set {_n} to {_n}-1
                            wait 1 tick
                            send "&7&m----------------------------------------------"
                            send "                  &e&lTOP 5 FAMA"
                            send " "
                            loop {_high.to.low.list::*}:
                                add 1 to {_pos}
                                set {_player} to loop-value parsed as offline player
                                if {_player} is offline:
                                    if {_pos} = 1:
                                        send " &e&l%{_pos}%. &c%{_player}% &e&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                    else if {_pos} = 2:
                                        send " &7&l%{_pos}%. &c%{_player}% &7&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                    else if {_pos} = 3:
                                        send " <##cd7f32>&l%{_pos}%. &c%{_player}% <##cd7f32>&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                    else if {_pos} != 1, 2 and 3:
                                        send " &f%{_pos}%. &c%{_player}% &8&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                else:
                                    if {_pos} = 1:
                                        send " &e&l%{_pos}%. &a%{_player}% &e&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                    else if {_pos} = 2:
                                        send " &7&l%{_pos}%. &a%{_player}% &7&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                    else if {_pos} = 3:
                                        send " <##cd7f32>&l%{_pos}%. &a%{_player}% <##cd7f32>&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                    else if {_pos} != 1, 2 and 3:
                                        send " &f%{_pos}%. &a%{_player}% &8&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)" to player
                                if {_pos} = 5:
                                    send "&7&m----------------------------------------------"
                                    stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if arg-3 isn't set:
                        if player has permission "fama.top":
                            send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else:
                        if player has permission "fama.top":
                            send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop

            else if arg-1 is "reset":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.reset.self":
                            if {fame::%player%} is not 0:
                                set {fame::%player%} to 0 
                                send "{@prefix} &6Hai azzerato la tua Fama."
                                play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                                stop
                            else:
                                send "{@error} &cNon hai nessun punto!"
                                play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                stop 
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if arg-3 isn't set:
                        if player has permission "fama.reset.other":
                            if {fame::%arg-2%} is not 0:
                                set {fame::%arg-2%} to 0
                                send "{@prefix} &6Hai azzerato la Fama di &c%arg-2%&6." to player
                                send "{@prefix} &c%player% &6ha azzerato la tua Fama." to arg-2
                                play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                                stop
                            else:
                                send "{@error} &6%arg-2% &cnon possiede Fama!"
                                play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else:
                        if player has permission "fama.reset.other":
                            send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                        
            else if arg-1 is "set":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.set":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama set <&egiocatore&6> <&enumero&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if arg-3 isn't set:
                        if player has permission "fama.set":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama set <&egiocatore&6> <&enumero&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else:
                        if player has permission "fama.set":
                            if arg-3 is set:
                                set {fame::%arg-2%} to arg-3
                                send "{@prefix} &6Hai impostato la Fama di &c%arg-2% &6a &e%arg-3%&6." to player
                                play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                                send "{@prefix} &c%player% &6ha impostato la tua Fama a &e%arg-3%&6." to arg-2
                                stop
                            else:
                                send "{@error} &cIl numero deve essere positivo!"
                                play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                stop    
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                
            else if arg-1 is "add":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.add":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama add <&egiocatore&6> <&enumero&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if arg-3 isn't set:
                        if player has permission "fama.add":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama add <&egiocatore&6> <&enumero&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else if arg-3 = 0:
                        if player has permission "fama.add":
                            send "{@error} &cChe senso ha aggiungere 0 Fama?"
                            play sound "{@what_sound}" with volume 1 at player for player
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else if arg-3 > 0:
                        if player has permission "fama.add":
                            add arg-3 to {fame::%arg-2%}
                            send "{@prefix} &6Hai aggiunto &e%arg-3% Fama &6alla Fama totale di &c%arg-2%&6." to player
                            play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                            send "{@prefix} &c%player% &6ha aggiunto &e%arg-3% Fama &6alla tua Fama totale." to arg-2
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else if arg-3 < 0:
                        if player has permission "fama.add":
                            send "{@error} &cIl numero deve essere positivo!"
                            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                
            else if arg-1 is "remove":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.remove":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama remove <&egiocatore&6> <&enumero&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if arg-3 isn't set:
                        if player has permission "fama.remove":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama remove <&egiocatore&6> <&enumero&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else if arg-3 = 0:
                        if player has permission "fama.remove":
                            send "{@error} &cChe senso ha togliere 0 Fama?"
                            play sound "{@what_sound}" with volume 1 at player for player
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else if arg-3 > 0:
                        if player has permission "fama.remove":
                            subtract arg-3 from {fame::%arg-2%}
                            send "{@prefix} &6Hai rimosso &e%arg-3% Fama &6dalla Fama totale di &c%arg-2%&6." to player
                            play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                            send "{@prefix} &c%player% &6ha rimosso &e%arg-3% Fama &6dalla tua Fama totale." to arg-2
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    else if arg-3 < 0:
                        if player has permission "fama.remove":
                            send "{@error} &cIl numero deve essere positivo!"
                            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop

            else if arg-1 is "pay":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.pay":
                            send "{@prefix} &cComando incompleto."
                            send "{@prefix} &cUtilizzo: &6/fama pay <&egiocatore&6> <&enumero&6>"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if arg-2 isn't player:
                        if arg-2 is offline:
                            if player has permission "fama.pay":
                                send "{@error} &6%arg-2% &cè offline."
                                play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                stop
                            else:
                                send "%{server.prefix.main}% &cComando sconosciuto."
                                stop
                        else if arg-2 is online:
                            if player has permission "fama.pay":
                                if arg-3 isn't set:
                                    send "{@error} &cQuanta Fama vuoi pagare a %arg-2%?"
                                    stop
                                else:
                                    if arg-3 > 0:
                                        if {fame::%player%} > arg-3:
                                            add arg-3 to {fame::%arg-2%}
                                            send "{@prefix} &aHai ricevuto &b%regex(arg-3)% Fama &ada &e%player%&a." to arg-2
                                            send action bar "&2&lVENDITA &a+%regex(arg-3)% Fama &6(%regex({fame::%arg-2%})% totale)" to arg-2
                                            subtract arg-3 from {fame::%player%}
                                            send action bar "&4&lACQUISTO &c+%regex(arg-3)% Fama &6(%regex({fame::%player%})% totale)" to player
                                            send "{@prefix} &aHai pagato &b%regex(arg-3)% Fama &aa &e%arg-2%&a." to player
                                            log "[TRANSAZIONE FAMA] %player% ha pagato %regex(arg-3)% Fama a %arg-2%." to "lista transazioni.log"
                                            play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                                            play sound "{@confirm_sound}" with volume 1 and pitch 2 at arg-2 for arg-2
                                            stop
                                        else:
                                            send "{@error} &cNon hai abbastanza Fama per effettuare questo pagamento!"
                                            send "{@prefix} &aPuoi controllare la tua Fama con &e/fama&a."
                                            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                            stop
                                    else if arg-3 < 0:
                                        send "{@error} &cIl numero deve essere positivo!"
                                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                        stop
                                    else if arg-3 = 0:
                                        send "{@error} &cChe senso ha pagare 0 Fama?"
                                        play sound "{@what_sound}" with volume 1 at player for player
                                        stop
                            else:
                                send "%{server.prefix.main}% &cComando sconosciuto."
                                stop
                    else:
                        if player has permission "fama.pay":
                            if {settings.%player%.user.genre} is "%{server.genre.male}%":
                                send "{@error} &cNon puoi effettuare questo comando su te stesso!"
                                play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                stop
                            else if {settings.%player%.user.genre} is "%{server.genre.female}%":
                                send "{@error} &cNon puoi effettuare questo comando su te stessa!"
                                play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                                stop                    
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                    
            else if arg-1 is "idle":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.idle.toggle":
                            if {fame.idle} isn't set:
                                set {fame.idle} to true
                                send "{@prefix} &7L'assegnazione automatica della Fama è stata &aattivata&7."
                                play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                                stop
                            else:
                                delete {fame.idle}
                                send "{@prefix} &7L'assegnazione automatica della Fama è stata &cdisattivata&7."
                                play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                                stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if player has permission "fama.idle.toggle":
                        send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
                    else:
                        send "%{server.prefix.main}% &cComando sconosciuto."
                        stop
            else if arg-1 is "help":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.admin.help":
                            send "&e> &7&m------------&r {@prefix} &7&m------------&r &e<"
                            send ""
                            send "&7Comandi che puoi eseguire:"
                            send "&c- &a/fama &7&o- Visualizza quanta Fama possiedi."
                            send "&c- &7/fama &acheck <giocatore> &7&o- Controlla quanta Fama ha un giocatore."
                            send "&c- &7/fama &atop &7&o- Controlla la classifica dei giocatori sulla Fama ottenuta."
                            send "&c- &7/fama &areset <giocatore> &7&o- Azzera la tua Fama o quella di un giocatore."
                            send "&c- &7/fama &aset <giocatore> <Fama> &7&o- Imposta il valore della Fama di un giocatore."
                            send "&c- &7/fama &aadd <giocatore> <Fama> &7&o- Aggiungi Fama ad un giocatore."
                            send "&c- &7/fama &aremove <giocatore> <Fama> &7&o- Rimuovi Fama da un giocatore."
                            send "&c- &7/fama &apay <giocatore> <Fama> &7&o- Paga un giocatore utilizzando la tua Fama"
                            send "&c- &7/fama &aidle &7&o- Attiva o disattiva l'assegnazione automatica della Fama ai giocatori."
                            send "&c- &7/fama &ainfo &7&o- Visualizza le info dello script."
                            send "&c- &7/fama &ahelp &7&o- Mostra questa lista."
                            send "&c- &7/fama &areload &7&o- Ricarica lo script."
                            send ""
                            send "&e> &7&m--------------------------------&r &e<"
                            stop
                        else:
                            send "&e> &7&m------------&r {@prefix} &7&m------------&r &e<"
                            send ""
                            send "&7Comandi che puoi eseguire:"
                            send "&c- &a/fama &7&o- Visualizza quanta Fama possiedi"
                            send "&c- &7/fama &apay <giocatore> <Fama> &7&o- Paga un giocatore utilizzando la tua Fama"
                            send "&c- &7/fama &ainfo &7&o- Visualizza le info dello script"
                            send "&c- &7/fama &ahelp &7&o- Mostra questa lista comandi"
                            send ""
                            send "&e> &7&m--------------------------------&r &e<"
                            stop
                else:
                    if player has permission "fama.help":
                        send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
                    else:
                        send "%{server.prefix.main}% &cComando sconosciuto."
                        stop
                
            else if arg-1 is "info":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.info":
                            send "&a> &9&m------------&r {@prefix} &9&m------------&r &a<"
                            send ""
                            send " &7Info sullo script:"
                            send formatted "   &3Versione dello script: <ttp:Clicca qui per visualizzarne la pagina sulla Wiki><link:https://wiki.ultrasmp.org/disagiosmp/il-server/fama-e-reputazioni>&c&n{@version}<reset>"
                            send "   &3Versione di Minecraft: &a%minecraft version%"
                            send "   &3Ideato e sviluppato da &b_Xedo_"
                            send ""
                            send "&a> &9&m--------------------------------&r &a<"
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if player has permission "fama.info":
                        send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
                    else:
                        send "%{server.prefix.main}% &cComando sconosciuto."
                        stop
            
            else if arg-1 is "reload":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "fama.reload":
                            send "{@prefix} &3Ricarico il config..."
                            wait 5 ticks
                            execute console command "/skript reload %script%"
                            send "{@prefix} &aConfig ricaricato! &cControlla la console per controllare se ci sono errori."
                            stop
                        else:
                            send "%{server.prefix.main}% &cComando sconosciuto."
                            stop
                else:
                    if player has permission "fama.reload":
                        send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
                    else:
                        send "%{server.prefix.main}% &cComando sconosciuto."
                        stop
            
            else if arg-1 is not "check", "top", "reset", "set", "add", "remove", "idle", "help", "info" or "reload":
                if player has permission "fama.commands":
                    send "{@error} &cComando sconosciuto."
                    send "{@error} &cUtilizzo: &6/fama"
                    send "{@error} &cUtilizzo: &6/fama check <&egiocatore&6>"
                    send "{@error} &cUtilizzo: &6/fama top"
                    send "{@error} &cUtilizzo: &6/fama reset [&egiocatore&6]"
                    send "{@error} &cUtilizzo: &6/fama set <&egiocatore&6> <&eFama&6>"
                    send "{@error} &cUtilizzo: &6/fama add <&egiocatore&6> <&eFama&6>"
                    send "{@error} &cUtilizzo: &6/fama remove <&egiocatore&6> <&eFama&6>"
                    send "{@error} &cUtilizzo: &6/fama pay <&egiocatore&6> <&eFama&6>"
                    send "{@error} &cUtilizzo: &6/fama idle"
                    send "{@error} &cUtilizzo: &6/fama info"
                    send "{@error} &cUtilizzo: &6/fama help"
                    send "{@error} &cUtilizzo: &6/fama reload"
                    stop
                else:
                    send "{@error} &cComando sconosciuto."
                    send "{@error} &cUtilizzo: &6/fama"
                    send "{@error} &cUtilizzo: &6/fama pay <&egiocatore&6> <&eFama&6>"
                    send "{@error} &cUtilizzo: &6/fama info"
                    send "{@error} &cUtilizzo: &6/fama help"
                    stop   
        else:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@error} &cSolo i giocatori possono eseguire questo comando."
                        stop
                    
            else if arg-1 is "check":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/fama check <&egiocatore&6>"
                        stop
                else:
                    if {fame::%arg-2%} is set:
                        send "{@prefix} &c%arg-2% &6ha accumulato &e%regex({fame::%arg-2%})% Fama&6."
                        stop
                    else:
                        send "{@error} &6%arg-2% &cnon ha ancora giocato in questo server!"
                        stop
            
            else if arg-1 is "top":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        loop {fame::*}:
                            add 1 to {_size}
                            if {_low.to.high.list::%loop-value%} isn't set:
                                set {_low.to.high.list::%loop-value%} to loop-index
                            else:
                                set {_n} to 0
                                loop {_size} times:
                                    set {_n} to {_n}+1
                                    {_low.to.high.list::%loop-value-1%.%{_n}%} isn't set
                                    set {_low.to.high.list::%loop-value-1%.%{_n}%} to loop-index
                                    stop loop
                        wait 1 tick
                        set {_n} to size of {_low.to.high.list::*}
                        loop {_low.to.high.list::*}:
                            set {_high.to.low.list::%{_n}%} to loop-value
                            set {_n} to {_n}-1
                        wait 1 tick
                        send "&7&m----------------------------------------------"
                        send "                  &e&lTOP 5 FAMA"
                        send " "
                        loop {_high.to.low.list::*}:
                            add 1 to {_pos}
                            set {_player} to loop-value parsed as offline player
                            if {_player} is offline:
                                if {_pos} = 1:
                                    send " &e&l%{_pos}%. &c%{_player}% &e&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                                else if {_pos} = 2:
                                    send " &7&l%{_pos}%. &c%{_player}% &7&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                                else if {_pos} = 3:
                                    send " <##cd7f32>&l%{_pos}%. &c%{_player}% <##cd7f32>&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                                else if {_pos} != 1, 2 and 3:
                                    send " &f%{_pos}%. &c%{_player}% &8&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                            else:
                                if {_pos} = 1:
                                    send " &e&l%{_pos}%. &a%{_player}% &e&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                                else if {_pos} = 2:
                                    send " &7&l%{_pos}%. &a%{_player}% &7&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                                else if {_pos} = 3:
                                    send " <##cd7f32>&l%{_pos}%. &a%{_player}% <##cd7f32>&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                                else if {_pos} != 1, 2 and 3:
                                    send " &f%{_pos}%. &a%{_player}% &8&l» &f%regex({fame::%{_player}%})% Fama &f(%{rank.%{_player}%}%&f)"
                            if {_pos} = 5:
                                send "&7&m----------------------------------------------"
                                stop
                else:
                    if arg-3 isn't set:
                        send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
                    else:
                        send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                        stop

            else if arg-1 is "reset":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@error} &cSolo i giocatori possono eseguire questo comando."
                        stop
                else:
                    if arg-3 isn't set:
                        if {fame::%arg-2%} is not 0:
                            set {fame::%arg-2%} to 0
                            send "{@prefix} &6Hai azzerato la Fama di &c%arg-2%&6." to console
                            send "{@prefix} &c%player% &6ha azzerato la tua Fama." to arg-2
                            stop
                        else:
                            send "{@error} &6%arg-2% &cnon possiede Fama!"
                            stop
                    else:
                        send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
                    
            else if arg-1 is "set":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/fama set <&egiocatore&6> <&enumero&6>"
                        stop
                else:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/fama set <&egiocatore&6> <&enumero&6>"
                        stop
                    else:
                        if arg-3 is set:
                            set {fame::%arg-2%} to arg-3
                            send "{@prefix} &6Hai impostato la Fama di &c%arg-2% &6a &e%arg-3%&6." to console
                            send "{@prefix} &c%player% &6ha impostato la tua Fama a &e%arg-3%&6." to arg-2
                            stop
                
            else if arg-1 is "add":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/fama add <&egiocatore&6> <&enumero&6>"
                        stop
                else:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/fama add <&egiocatore&6> <&enumero&6>"
                        stop
                    else if arg-3 = 0:
                        send "{@error} &cChe senso ha aggiungere 0 Fama?"
                        stop
                    else if arg-3 > 0:
                        add arg-3 to {fame::%arg-2%}
                        send "{@prefix} &6Hai aggiunto &e%arg-3% Fama &6alla Fama totale di &c%arg-2%&6." to console
                        send "{@prefix} &c%player% &6ha aggiunto &e%arg-3% Fama &6alla tua Fama totale." to arg-2
                        stop
                    else if arg-3 < 0:
                        send "{@error} &cIl numero deve essere positivo!"
                        stop
                
            else if arg-1 is "remove":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/fama remove <&egiocatore&6> <&enumero&6>"
                        stop
                else:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/fama remove <&egiocatore&6> <&enumero&6>"
                        stop
                    else if arg-3 = 0:
                        send "{@error} &cChe senso ha togliere 0 Fama?"
                        stop
                    else if arg-3 > 0:
                        subtract arg-3 from {fame::%arg-2%}
                        send "{@prefix} &6Hai rimosso &e%arg-3% Fama &6dalla Fama totale di &c%arg-2%&6." to console
                        send "{@prefix} &c%player% &6ha rimosso &e%arg-3% Fama &6dalla tua Fama totale." to arg-2
                        stop
                    else if arg-3 < 0:
                        send "{@error} &cIl numero deve essere positivo!"
                        stop

            else if arg-1 is "pay":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@error} &cSolo i giocatori possono eseguire questo comando."
                        stop
                    
            else if arg-1 is "idle":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if {fame.idle} isn't set:
                            set {fame.idle} to true
                            send "{@prefix} &7L'assegnazione automatica della Fama è stata &aattivata&7."
                            stop
                        else:
                            delete {fame.idle}
                            send "{@prefix} &7L'assegnazione automatica della Fama è stata &cdisattivata&7."
                            stop
                else:
                    send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                    stop
            else if arg-1 is "help":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "&e> &7&m------------&r {@prefix} &7&m------------&r &e<"
                        send ""
                        send "&7Comandi che puoi eseguire:"
                        send "&c- &7/fama &acheck <giocatore> &7&o- Controlla quanta Fama ha un giocatore."
                        send "&c- &7/fama &atop &7&o- Controlla la classifica dei giocatori sulla Fama ottenuta."
                        send "&c- &7/fama &areset <giocatore> &7&o- Azzera la tua Fama o quella di un giocatore."
                        send "&c- &7/fama &aset <giocatore> <Fama> &7&o- Imposta il valore della Fama di un giocatore."
                        send "&c- &7/fama &aadd <giocatore> <Fama> &7&o- Aggiungi Fama ad un giocatore."
                        send "&c- &7/fama &aremove <giocatore> <Fama> &7&o- Rimuovi Fama da un giocatore."
                        send "&c- &7/fama &aidle &7&o- Attiva o disattiva l'assegnazione automatica della Fama ai giocatori."
                        send "&c- &7/fama &ainfo &7&o- Visualizza le info dello script."
                        send "&c- &7/fama &ahelp &7&o- Mostra questa lista."
                        send "&c- &7/fama &areload &7&o- Ricarica lo script."
                        send ""
                        send "&e> &7&m--------------------------------&r &e<"
                        stop
                else:
                    send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                    stop
                
            else if arg-1 is "info":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "&a> &9&m------------&r {@prefix} &9&m------------&r &a<"
                        send ""
                        send " &7Info sullo script:"
                        send "   &3Versione dello script: &c{@version}"
                        send "   &3Versione di Minecraft: &a%minecraft version%"
                        send "   &3Ideato e sviluppato da &b_Xedo_"
                        send ""
                        send "&a> &9&m--------------------------------&r &a<"
                        stop
                else:
                    send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                    stop
            
            else if arg-1 is "reload":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &3Ricarico il config..."
                        wait 5 ticks
                        execute console command "/skript reload %script%"
                        send "{@prefix} &aConfig ricaricato!"
                        stop
                else:
                    send "{@error} &cQuesto comando non richiede parametri aggiuntivi."
                    stop
            
            else if arg-1 is not "check", "reset", "set", "add", "remove", "idle", "help", "info" or "reload":
                send "{@error} &cComando sconosciuto."
                send "{@error} &cUtilizzo: &6/fama check <&egiocatore&6>"
                send "{@error} &cUtilizzo: &6/fama top"
                send "{@error} &cUtilizzo: &6/fama reset <&egiocatore&6>"
                send "{@error} &cUtilizzo: &6/fama set <&egiocatore&6> <&eFama&6>"
                send "{@error} &cUtilizzo: &6/fama add <&egiocatore&6> <&eFama&6>"
                send "{@error} &cUtilizzo: &6/fama remove <&egiocatore&6> <&eFama&6>"
                send "{@error} &cUtilizzo: &6/fama idle"
                send "{@error} &cUtilizzo: &6/fama info"
                send "{@error} &cUtilizzo: &6/fama help"
                send "{@error} &cUtilizzo: &6/fama reload"
                stop

on tab complete of "/fama" or "/f":
    if player has permission "fama.commands":
        set tab completions for position 1 to "check", "top", "reset", "set", "add", "remove", "pay", "idle", "info", "help" and "reload"
        if tab arg-1 is "check", "set", "add", "remove" or "pay":
            set tab completions for position 2 to {players::*}
            set tab completions for position 3 to "[<Fama>]"
    else:
        set tab completions for position 1 to "top", "pay", "info" and "help"
        if tab arg-1 is "pay":
            set tab completions for position 2 to {players::*}
            set tab completions for position 3 to "[<Fama>]"

# FUNZIONE PER DIVIDERE I NUMERI GROSSI IN MIGLIAIA CON UN PUNTO E CON UNA VIRGOLA PER I DECIMALI
function regex(n: object) :: text:
    if "%{_n}%" contains ".":
        set {_s::*} to split "%{_n}%" at "."
        set {_n} to "%a({_s::1})%,%last 2 characters of {_s::2}%"
        return "%{_n}%"
    else:
        set {_n} to a("%{_n}%")
        return "%{_n} ? 0%"
        
function a(b: text) :: text:
    if length of {_b} > 3:
        return "%a(first length of {_b} - 3 characters of {_b})%.%last 3 characters of {_b}%"
    return {_b}