on place:
    if player's gamemode is survival or adventure:
# QUERCIA
        if event-block is oak log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped oak log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_oak_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped oak wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_oak_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oak button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oak_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# BETULLA
        if event-block is birch log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped birch log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_birch_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped birch wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_birch_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is birch button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.birch_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# QUERCIA SCURA
        if event-block is dark oak log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped dark oak log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_dark_oak_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped dark oak wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_dark_oak_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark oak button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_oak_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# ABETE
        if event-block is spruce log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.spruce_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.spruce_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped spruce log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_spruce_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped spruce wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_spruce_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.spruce_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {blocksbuild.%player%.spruce_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce slab:
            if {blocks::%player%::*} is not set:
                add 1 to {blocksbuild.%player%.spruce_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce fence:
            if {blocks::%player%::*} is not set:
                add 1 to {blocksbuild.%player%.spruce_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {blocksbuild.%player%.spruce_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce door:
            if {blocks::%player%::*} is not set:
                add 1 to {blocksbuild.%player%.spruce_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {blocksbuild.%player%.spruce_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.spruce_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is spruce button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.spruce_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# ACACIA
        if event-block is acacia log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped acacia log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_acacia_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped acacia wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_acacia_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is acacia button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.acacia_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# GIUNGLA
        if event-block is jungle log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped jungle log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_jungle_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped jungle wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_jungle_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is jungle button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.jungle_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MANGROVIA
        if event-block is mangrove log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped mangrove log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_mangrove_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped mangrove wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_mangrove_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mangrove button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mangrove_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# CILIEGIO
        if event-block is cherry log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped cherry log:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_cherry_log}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped cherry wood:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_cherry_wood}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cherry button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cherry_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# BAMBÙ
        if event-block is bamboo block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped bamboo block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_bamboo_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo mosaic:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_mosaic}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo mosaic stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_mosaic_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo mosaic slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_mosaic_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is bamboo button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bamboo_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# CREMISI
        if event-block is crimson stem:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_stem}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson hyphae:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_hyphae}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped crimson stem:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_crimson_stem}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped crimson hyphae:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_crimson_hyphae}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is crimson button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.crimson_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# DISTORTO
        if event-block is warped stem:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_stem}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped hyphae:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_hyphae}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped warped stem:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_warped_stem}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stripped warped hyphae:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stripped_warped_hyphae}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped planks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_planks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped fence gate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_fence_gate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_door}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_trapdoor}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is warped button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.warped_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PIETRA, CALCITE, TUFO E PIETRA LISCIA
        if event-block is stone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stone pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_pressure plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stone button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is calcite:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.calcite}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is tuff:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.tuff}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth stone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_stone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth stone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_stone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PIETRISCO E PIETRISCO MUSCHIOSO
        if event-block is cobblestone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobblestone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cobblestone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobblestone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cobblestone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobblestone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cobblestone wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobblestone_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy cobblestone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_cobblestone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy cobblestone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_cobblestone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy cobblestone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_cobblestone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy cobblestone wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_cobblestone_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MATTONI DI PIETRA E MATTONI DI PIETRA MUSCHIOSI
        if event-block is stone bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cracked stone bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cracked_stone_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stone brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stone brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is stone brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.stone_brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is chiseled stone bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chiseled_stone_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy stone bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_stone_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy stone brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_stone_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy stone brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_stone_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mossy stone brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mossy_stone_brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# GRANITO E GRANITO LEVIGATO
        if event-block is granite:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.granite}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is granite stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.granite_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is granite slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.granite_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is granite wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.granite_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished granite:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_granite}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished granite stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_granite_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished granite slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_granite_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# DIORITE E DIORITE LEVIGATA
        if event-block is diorite:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.diorite}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is diorite stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.diorite_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is diorite slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.diorite_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is diorite wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.diorite_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished diorite:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_diorite}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished diorite stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_diorite_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished diorite slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_diorite_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# ANDESITE E ANDESITE LEVIGATA
        if event-block is andesite:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.andesite}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is andesite stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.andesite_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is andesite slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.andesite_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is andesite wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.andesite_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished andesite:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_andesite}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished andesite stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_andesite_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished andesite slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_andesite_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PIETRISCO DI ARDESIA PROFONDA E ARDESIA PROFONDA
        if event-block is deepslate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cobbled deepslate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobbled_deepslate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cobbled deepslate stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobbled_deepslate_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cobbled deepslate slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobbled_deepslate_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cobbled deepslate wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cobbled_deepslate_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# ARDESIA PROFONDA CESELLATA E LEVIGATA
        if event-block is chiseled deepslate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chiseled_deepslate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished deepslate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_deepslate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished deepslate stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_deepslate_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished deepslate slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_deepslate_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished deepslate wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_deepslate_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MATTONI DI ARDESIA PROFONDA
        if event-block is deepslate bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cracked deepslate bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cracked_deepslate_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is deepslate brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_bricks_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is deepslate brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_bricks_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is deepslate brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_bricks_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PIASTRELLE DI ARDESIA PROFONDA
        if event-block is deepslate tiles:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_tiles}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cracked deepslate tiles:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cracked_deepslate_tiles}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is deepslate tile stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_tiles_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is deepslate tile slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_tiles_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is deepslate tile wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.deepslate_tiles_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# ARDESIA PROFONDA RINFORZATA
        if event-block is reinforced deepslate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.reinforced_deepslate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MATTONI
        if event-block is bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# FANGO
        if event-block is packed mud:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.packed_mud}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mud bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mud_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mud brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mud_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mud brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mud_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is mud brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.mud_brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# ARENARIA
        if event-block is sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is sandstone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.sandstone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is sandstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.sandstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is sandstone wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.sandstone_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is chiseled sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chiseled_sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth sandstone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_sandstone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth sandstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_sandstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cut sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cut_sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cut sandstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cut_sandstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# ARENARIA ROSSA
        if event-block is red sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is red sandstone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_sandstone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is red sandstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_sandstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is red sandstone wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_sandstone_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is chiseled red sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chiseled_red_sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth red sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_red_sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth red sandstone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_red_sandstone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth red sandstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_red_sandstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cut red sandstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cut_red_sandstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cut red sandstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cut_red_sandstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
            
# PRISMARINO
        if event-block is prismarine:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.prismarine}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is prismarine stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.prismarine_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is prismarine slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.prismarine_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is prismarine wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.prismarine_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MATTONI DI PRISMARINO
        if event-block is prismarine bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.prismarine_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is prismarine brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.prismarine_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is prismarine brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.prismarine_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PRISMARINO SCURO
        if event-block is dark prismarine:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_prismarine}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark prismarine stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_prismarine_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is dark prismarine slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.dark_prismarine_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# NETHERRACK
        if event-block is netherrack:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.netherrack}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MATTONI DEL NETHER
        if event-block is nether bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.nether_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cracked nether bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cracked_nether_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is chiseled nether bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chiseled_nether_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is nether brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.nether_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is nether brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.nether_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is nether brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.nether_brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is nether brick fence:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.nether_brick_fence}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MATTONI DEL NETHER ROSSI
        if event-block is red nether bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_nether_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is red nether brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_nether_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is red nether brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_nether_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is red nether brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.red_nether_brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# BASALTO
        if event-block is basalt:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.basalt}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth basalt:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_basalt}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished basalt:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_basalt}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PIETRANERA
        if event-block is blackstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.blackstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is gilded blackstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.gilded_blackstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is blackstone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.blackstone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is blackstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.blackstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is blackstone wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.blackstone_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PIETRANERA LEVIGATA
        if event-block is chiseled polished blackstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chiseled_polished_blackstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone button:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_button}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# MATTONI DI PIETRANERA LEVIGATA
        if event-block is polished blackstone bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cracked polished blackstone bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cracked_polished_blackstone_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is polished blackstone brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.polished_blackstone_brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PIETRA DELL'END E MATTONI DI PIETRA DELL'END
        if event-block is end stone:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.end_stone}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is end stone bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.end_stone_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is end stone brick stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.end_stone_brick_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is end stone brick slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.end_stone_brick_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is end stone brick wall:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.end_stone_brick_wall}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# PURPUR
        if event-block is purpur block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.purpur_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is purpur pillar:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.purpur_pillar}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is purpur stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.purpur_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is purpur slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.purpur_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# OGGETTI IN FERRO
        if event-block is iron block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.iron_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is iron bars:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.iron_bars}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is iron door:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.iron_bars}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is iron trapdoor:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.iron_bars}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is heavy weighted pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.heavy_weighted_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is chain:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chain}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# OGGETTI IN ORO
        if event-block is gold block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.gold_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is light weighted pressure plate:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.light_weighted_pressure_plate}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# BLOCCHI DI MINERALI
        if event-block is coal block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.coal_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is redstone block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.redstone_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is emerald block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.emerald_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is lapis block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.lapis_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is diamond block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.diamond_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is netherite block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.netherite_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# QUARZO
        if event-block is quartz block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.quartz_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is quartz stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.quartz_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is quartz slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.quartz_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is chiseled quartz block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.chiseled_quartz_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is quartz bricks:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.quartz_bricks}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is quartz pillar:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.quartz_pillar}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth quartz:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_quartz}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth quartz stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_quartz_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is smooth quartz slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.smooth_quartz_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# BLOCCHI DI RAME
    # NORMALI
        if event-block is copper block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.copper_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
    # ESPOSTI
        if event-block is exposed copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.exposed_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is exposed cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.exposed_cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is exposed cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.exposed_cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is exposed cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.exposed_cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
    # CORROSI
        if event-block is weathered copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.weathered_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is weathered cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.weathered_cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is weathered cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.weathered_cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is weathered cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.weathered_cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
    # OSSIDATI
        if event-block is oxidized copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oxidized_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oxidized cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oxidized_cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oxidized cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oxidized_cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is oxidized cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.oxidized_cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}

# BLOCCHI DI RAME CERATI
    # NORMALI
        if event-block is waxed copper block:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_copper_block}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
    # ESPOSTI
        if event-block is waxed exposed copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_exposed_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed exposed cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_exposed_cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed exposed cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_exposed_cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed exposed cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_exposed_cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
    # CORROSI
        if event-block is waxed weathered copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_weathered_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed weathered cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_weathered_cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed weathered cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_weathered_cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed weathered cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_weathered_cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
    # OSSIDATI
        if event-block is waxed oxidized copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_oxidized_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed oxidized cut copper:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_oxidized_cut_copper}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed oxidized cut copper stairs:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_oxidized_cut_copper_stairs}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}
        if event-block is waxed oxidized cut copper slab:
            if {blocks::%player%::*} is not set:
                add 1 to {build.%player%.placed.waxed_oxidized_cut_copper_slab}
                add 1 to {stats.%player%.placed_blocks}
                add 1 to {build.%player%.total_placed}
                add event-location to {blocks::%player%::*}