options:
    animation_speed: 0.001

    wait: 20

    random_x_mob: -0.7 and 0.9
    random_y_mob: -0.7 and -0.8
    random_z_mob: -0.7 and 0.3
    random_x_player: -0.7 and 0.9
    random_y_player: -0.3 and -0.9
    random_z_player: -0.7 and 0.3

    lowest_damage: 1.99
    lowest_damage_color: &7
    low_damage: 2 and 4.99
    low_damage_color: &a
    medium_damage: 5 and 6.99
    medium_damage_color: &e
    high_damage: 7 and 9.99
    high_damage_color: &c
    critical_damage: 10
    critical_damage_color: &4

    fight: &a● &a&lPvP abilitato &a●
    no_fight: &c● &c&lPvP disabilitato &c●
    
    on: &aSì
    off: &cNo
    

function DamageIndicatorPlayers(e: location, i: number, p: player):
    if {settings.%{_p}%.custom.damageindicator.players} is true:
        set {_x} to (random number between {@random_x_player})
        set {_y} to (random number between {@random_y_player})
        set {_z} to (random number between {@random_z_player})
        spawn (armor stand) at {_e} ~ vector({_x},{_y},{_z}):
            set int tag "Invisible" of nbt of entity to 100
            set int tag "NoGravity" of nbt of entity to 100
        set {_a} to (last spawned armor stand)
        if {_i} <= {@lowest_damage}:
            set (display name of {_a}) to "{@lowest_damage_color}%regex({_i})%"
        else if {_i} is between {@low_damage}:
            set (display name of {_a}) to "{@low_damage_color}%regex({_i})%"
        else if {_i} is between {@medium_damage}:
            set (display name of {_a}) to "{@medium_damage_color}%regex({_i})%"
        else if {_i} is between {@high_damage}:
            set (display name of {_a}) to "{@high_damage_color}%regex({_i})%"
        else if {_i} >= {@critical_damage}:
            set (display name of {_a}) to "{@critical_damage_color}%regex({_i})%"
        wait 1 tick
        loop {@wait} times:
            teleport {_a} to (location of {_a} ~ vector(0,{@animation_speed},0))
            wait 1 tick
    else:
        wait {@wait} ticks
    delete ({_a}'s uuid parsed as entity)

function DamageIndicatorMobs(e: location, i: number, p: player):
    if {settings.%{_p}%.custom.damageindicator.mobs} is true:
        set {_x} to (random number between {@random_x_mob})
        set {_y} to (random number between {@random_y_mob})
        set {_z} to (random number between {@random_z_mob})
        spawn (armor stand) at {_e} ~ vector({_x},{_y},{_z}):
            set int tag "Invisible" of nbt of entity to 100
            set int tag "NoGravity" of nbt of entity to 100
        set {_a} to (last spawned armor stand)
        if {_i} <= {@lowest_damage}:
            set (display name of {_a}) to "{@lowest_damage_color}🗡 +%regex({_i})%"
        else if {_i} is between {@low_damage}:
            set (display name of {_a}) to "{@low_damage_color}🗡 +%regex({_i})%"
        else if {_i} is between {@medium_damage}:
            set (display name of {_a}) to "{@medium_damage_color}🗡 +%regex({_i})%"
        else if {_i} is between {@high_damage}:
            set (display name of {_a}) to "{@high_damage_color}🗡 +%regex({_i})%"
        else if {_i} >= {@critical_damage}:
            set (display name of {_a}) to "{@critical_damage_color}🗡 +%regex({_i})%"
        wait 1 tick
        loop {@wait} times:
            teleport {_a} to (location of {_a} ~ vector(0,{@animation_speed},0))
            wait 1 tick
    else:
        wait {@wait} ticks
    delete ({_a}'s uuid parsed as entity)

    
on damage:
    if victim isn't a player, a fireball, a boat, an armor stand or an item frame:
        if attacker is a player:
            if {difficulty.info.hardcore_death::%attacker%} isn't set:
                DamageIndicatorMobs((location of victim),damage,attacker)
    else:
        if {pvp} is "{@fight}":
            if {god.%victim%} is "{@off}":
                if {difficulty.info.hardcore_death::%attacker%} isn't set:
                    DamageIndicatorPlayers((location of victim),damage,attacker)
                    if damage cause is projectile:
                        if gamemode of victim is survival or adventure:
                            if attacker's tool is a bow or a crossbow:
                                if victim is not attacker:
                                    wait 1 tick
                                    send "&8[&6🏹&8] &c%victim% &aha &c%placeholder "auraskills_hp" from victim% ❤" to attacker
                            else if attacker's tool is trident:
                                if victim is not attacker:
                                    wait 1 tick
                                    send "&8[&b🔱&8] &c%victim% &aha &c%placeholder "auraskills_hp" from victim% ❤" to attacker