options:
    profile_item_name: &eProfilo &lSMP

on join:
    set slot 8 of player to nether star named "{@profile_item_name}"

on right click:
    if player is holding a nether star named "{@profile_item_name}":
        if player's offhand isn't air:
            cancel event
        openProfileGui(player)
        #play sound "ui.button.click" with volume 0.2 at player for player # SOSTITUIRE "ui.button.click" CON "%{settings.click_sound.profile.%player%}%"

on inventory click:
    if type of event-inventory is player inventory:
        if index of event-slot is 8:
            cancel event
            #openProfileGui(player)
        if index of event-slot isn't 8:
            if event-item is nether star named "{@profile_item_name}":
                clear event-slot
    if click type is number key:
        if event-slot is 8:
            if event-slot is air:
                set {noswap.%player%} to air
            else:
                set {noswap.%player%} to event-item
            wait 1 tick
            if event-item is nether star named "{@profile_item_name}":
                set event-slot to {noswap.%player%}
                set slot 8 of player's inventory to nether star named "{@profile_item_name}"
        if event-slot is 8:
            cancel event
        if cursor slot of player is nether star named "{@profile_item_name}":
            set cursor slot of player to {noswap.%player%}
            set slot 8 of player's inventory to nether star named "{@profile_item_name}"

on drop:
    if event-item is nether star named "{@profile_item_name}":
        cancel event

on swap hand items:
    if event-player's tool is nether star named "{@profile_item_name}":
        cancel event

every tick:
    loop all players:
        if slot 8 of loop-player isn't nether star named "{@profile_item_name}":
            set slot 8 of loop-player to nether star named "{@profile_item_name}"
        loop all items in the inventory of loop-player:
            if name of loop-item is "{@profile_item_name}":
                if slot 8 of loop-player's inventory isn't loop-item:
                    set loop-item to air
    