on server list ping:
    if {maintenance} is set:
        set motd to "       &e&l%{server.name.CAPS}% &c[%minecraft version%] &7- &6[%{server.version}%&6]%newline%          &4&k0 &6&lMANUTENZIONE IN CORSO! &4&k0"
        set fake max players count to 1
        hide all players from the server list
        #cancel event
    else:
        set motd to "             &e&l%{server.name_CAPS}% &c[%minecraft version%] &7- &4&lINDEV%newline%       &b&lPROGRESS UPDATE! &a&lIN SVILUPPO"
        #set the fake max players count to (number of all players + 1)

#command /motd [<integer>] [<text>]:    # COMANDO CHE PERMETTE LA CREAZIONE E IL SALVATAGGIO DI RIGHE PER IL MOTD MOSTRATO NELLA LISTA DEI SERVER