options:
  # YML
    genre: yaml value "genre" in "settings-%player's uuid%"
    genre_lp: yaml value "genre" in "settings-%loop-player's uuid%"

on command "/tell":
    cancel event
    send "%{server.prefix.main}% &cNon lo sai? Questo comando in questo server è disattivato!"
    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
    wait 30 ticks
    send "%{server.prefix.main}% &cUtilizza &6/msg <&egiocatore&6> <&emessaggio&6> &cper inviare messaggi privati."
    
# CREAZIONE DI UNA VARIABILE CHE CONTIENE UN MESSAGGIO PRIVATO ALLA VOLTA DI UN GIOCATORE E DIVISIONE DEL COMANDO /r CON L'ELIMINAZIONE DELLA VARIABILE CREATA IN PRECEDENZA
command /msg [<offline player>] [<text>]: 
    aliases: /r
    description: "Ti piacciono i messaggi privati?"
    executable by: player, console
    trigger:
        if sender is console:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "&cSpecifica il giocatore a cui vuoi mandare un messaggio!"
                    stop
                    
            else if arg-1 is offline:
                send "&6%arg-1% &cnon è online!"
                stop
                
            else if arg-1 is set:
                if arg-2 isn't set:
                    send "&cCosa vuoi dire a %arg-1%?"
                    stop
                else:
                    if arg-2 is set:
                        send "&6[&eTu &7a &e%arg-1%&6] &c&l> &f%arg-2%"
                        send "&6[&eConsole &7a &eTe&6] &c&l> &f%arg-2%" to arg-1
                        play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                        stop
        else:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "&cSpecifica il giocatore a cui vuoi mandare un messaggio!"
                    stop
                    
            else if arg-1 is offline:
                send "&6%arg-1% &cnon è online!"
                stop
                
            else if arg-1 is player:
                if {@genre} is "%{server.genre.male}%":
                    send "&cChe senso ha scrivere a te stesso?"
                    stop
                else if {@genre} is "%{server.genre.female}%":
                    send "&cChe senso ha scrivere a te stessa?"
                    stop
                
            else if arg-1 is set:
                if arg-2 isn't set:
                    send "&cCosa vuoi dire a %arg-1%?"
                    stop
                else:
                    if arg-2 is set:
                        if player's uuid is "cd1db3e8-73ee-488f-9367-73224ca93ef3":
                            send "&6[&bTu &7a &a%arg-1%&6] &9&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&b%player% &7a &aTe&6]<reset> &9&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else if player's uuid is "da71a28d-8da4-427d-8967-c77757f887f4":
                            send "&6[&cTu &7a &a%arg-1%&6] &4&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&c%player% &7a &aTe&6]<reset> &4&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else if player's uuid is "0809c6c4-6898-415c-90d5-dd6fee334fca":
                            send "&6[&4Tu &7a &a%arg-1%&6] &c&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&4%player% &7a &aTe&6]<reset> &c&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else if player's uuid is "d6c92f76-8c3b-4a1f-ac35-74fba37a0d44":
                            send "&6[&8Tu &7a &a%arg-1%&6] &7&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&8%player% &7a &aTe&6]<reset> &7&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else if player's uuid is "b1cdedbc-5f5a-4d13-9f75-d0c6c24bceec":
                            send "&6[&aTu &7a &3%arg-1%&6] &2&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&a%player% &7a &3Te&6]<reset> &2&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else if player's uuid is "a095c219-f7e9-478e-aff9-110c4a35d653":
                            send "&6[&dTu &7a &c%arg-1%&6] &5&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&d%player% &7a &aTe&6]<reset> &5&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else if player's uuid is "b8d563c2-b3eb-474f-bec2-ddab7cccae0d":
                            send "&6[&5Tu &7a &c%arg-1%&6] &d&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&5%player% &7a &aTe&6]<reset> &d&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else if player's uuid is "cfc5251b-c55b-4a99-b020-23bdb1c2354a":
                            send "&6[&3Tu &7a &c%arg-1%&6] &1&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&3%player% &7a &aTe&6]<reset> &1&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop
                        else:
                            send "&6[&3Tu &7a &f%arg-1%&6] &7&l> &f%arg-2%"
                            send formatted "<tooltip:&fClicca per rispondere rapidamente a %player%><suggest command:/r %player% >&6[&3%player% &7a &aTe&6]<reset> &7&l> &f%arg-2%" to arg-1
                            send "&6[&f%player% a %arg-1%&6] &f&l> &7%arg-2%" to console
                            play sound "entity.experience_orb.pickup" with volume 1 at arg-1 for arg-1
                            stop

on chat:
    loop all players:
        if message contains "%loop-player%":
            if {@genre_lp} is "%{server.genre.male}%":
                replace "%loop-player%" in message with "&9%loop-player%&r"
            else if {@genre_lp} is "%{server.genre.female}%":
                replace "%loop-player%" in message with "&d%loop-player%&r"
            play sound "entity.experience_orb.pickup" with volume 1 at loop-player for loop-player