options:
    prefix: &b[&3&lNICK&b]

  # YML
    data_p: "data-%player's uuid%"
    data_arg2: "data-%{arg2}'s uuid%"
    data_arg3: "data-%arg-3's uuid%"
    data_lp: "data-%loop-player's uuid%"

    nick_p: yaml value "player_info.player.nickname" in "data-%player's uuid%"
    nick_arg2: yaml value "player_info.player.nickname" in "data-%{arg2}'s uuid%"
    nick_arg3: yaml value "player_info.player.nickname" in "data-%arg-3's uuid%"
    nick_lp: yaml value "player_info.player.nickname" in "data-%loop-player's uuid%"

every tick:
    if {nick_list::*} isn't set:
        set {nick_list::*} to "&7Non ci sono soprannomi attivi."
    loop all players:
        if {@nick_lp} isn't set:
            set {@nick_lp} to name of loop-player
            set loop-player's tablist name to loop-player's name
            save yaml {@data_lp}

command /nick [<text>] [<text>] [<offline player>]:
    description: Gestisci i soprannomi dei giocatori.
    executable by: player, console
    trigger:
        if sender is player:
            set {_nick_p} to {@nick_p}
            set {_nick_arg3} to {@nick_arg3}
            if arg-1 isn't set:
                if {@nick_p} isn't player's name:
                    send "{@prefix} &fIl tuo soprannome attuale: &7%{_nick_p}%"
                    send "{@prefix} &cUtilizzo: &6/nick <&eset &6| &eclear&6> <&esoprannome&6> [&egiocatore&6]"
                    stop
                else:
                    send "{@prefix} &cNon possiedi un soprannome!"
                    send "{@prefix} &6Puoi impostarne uno utilizzando &e/nick set <soprannome>"
                    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                    stop
            else if arg-1 is "set":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "nick.set.other":
                            send "{@prefix} &cScegli un soprannome!"
                            send "{@prefix} &6Puoi anche impostarne uno per un altro giocatore con &c/nick set <&esoprannome&c> [&egiocatore&c]&6."
                            stop
                        else:
                            send "{@prefix} &cScegli un soprannome!"
                            stop
                else:
                    if arg-3 isn't set:
                        if player has permission "nick.set.other":
                            if {@nick_p} is player's name:
                                if {nick_list::*} is "&7Non ci sono soprannomi attivi.":
                                    delete {nick_list::*}
                                    set {@nick_p} to arg-2
                                    add {@nick_p} to {nick_list::*}
                                    save yaml {@data_p}
                                    send "{@prefix} &bHai impostato il tuo soprannome."
                                    send "{@prefix} &f%arg-2%"
                                    send "{@prefix} &7Potrai leggerlo quando invierai messaggi in chat (preceduto da un ""&f*&7""), in TAB e gli altri giocatori potranno leggerlo sulla tua testa."
                                    play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                    stop
                                else if {nick_list::*} doesn't contain arg-2:
                                    set {@nick_p} to arg-2
                                    add {@nick_p} to {nick_list::*}
                                    save yaml {@data_p}
                                    send "{@prefix} &bHai impostato il tuo soprannome."
                                    send "{@prefix} &f%arg-2%"
                                    send "{@prefix} &7Potrai leggerlo quando invierai messaggi in chat (preceduto da un ""&f*&7""), in TAB e gli altri giocatori potranno leggerlo sulla tua testa."
                                    play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                    stop
                                else if {nick_list::*} contains arg-2:
                                    send "{@prefix} &6%arg-2% &cè stato già preso da qualcun altro! Scegli un altro soprannome."
                                    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                    stop
                            else:
                                send "{@prefix} &cHai già un soprannome &f(%{_nick_p}%)&c! Rimuovilo prima di poterne impostare un altro."
                                play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                stop
                        else:
                            if {@nick_p} is player's name:
                                if {nick_list::*} is "&7Non ci sono soprannomi attivi.":
                                    delete {nick_list::*}
                                    set {@nick_p} to arg-2
                                    add {@nick_p} to {nick_list::*}
                                    save yaml {@data_p}
                                    send "{@prefix} &bHai impostato il tuo soprannome."
                                    send "{@prefix} &f%arg-2%"
                                    send "{@prefix} &7Potrai leggerlo quando invierai messaggi in chat (preceduto da un ""&f*&7""), in TAB e gli altri giocatori potranno leggerlo sulla tua testa."
                                    play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                    stop
                                else if {nick_list::*} doesn't contain arg-2:
                                    set {@nick_p} to arg-2
                                    add {@nick_p} to {nick_list::*}
                                    save yaml {@data_p}
                                    send "{@prefix} &bHai impostato il tuo soprannome."
                                    send "{@prefix} &f%arg-2%"
                                    send "{@prefix} &7Potrai leggerlo quando invierai messaggi in chat (preceduto da un ""&f*&7""), in TAB e gli altri giocatori potranno leggerlo sulla tua testa."
                                    play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                    stop
                                else if {nick_list::*} contains arg-2:
                                    send "{@prefix} &6%arg-2% &cè stato già preso da qualcun altro! Scegli un altro soprannome."
                                    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                    stop
                            else:
                                send "{@prefix} &cHai già un soprannome! Rimuovilo prima di poterne impostare un altro."
                                play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                stop
                    else:
                        if player has permission "nick.set.other":
                            if {@nick_arg3} is arg-3:
                                if {nick_list::*} is "&7Non ci sono soprannomi attivi.":
                                    delete {nick_list::*}
                                    set {@nick_arg3} to arg-2
                                    add {@nick_arg3} to {nick_list::*}
                                    save yaml {@data_arg3}
                                    send "{@prefix} &aHai impostato &b%arg-2% &acome soprannome per &3%arg-3%&a!" to player
                                    send "{@prefix} &b%player% &ati ha impostato &3%arg-2% &acome soprannome." to arg-3
                                    play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                    stop
                                else if {nick_list::*} doesn't contain arg-2:
                                    set {@nick_arg3} to arg-2
                                    add {@nick_arg3} to {nick_list::*}
                                    save yaml {@data_arg3}
                                    send "{@prefix} &aHai impostato &b%arg-2% &acome soprannome per &3%arg-3%&a!" to player
                                    send "{@prefix} &b%player% &ati ha impostato &3%arg-2% &acome soprannome." to arg-3
                                    play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                    stop
                                else if {nick_list::*} contains arg-2:
                                    send "{@prefix} &6%arg-2% &cè stato già preso da qualcun altro! Scegli un altro soprannome."
                                    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                    stop
                            else:
                                send "{@prefix} &6%arg-3% &cha già un soprannome &f(%{_nick_arg3}%)&c! Rimuovilo prima di poterne impostare un altro."
                                play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                stop
                        else:
                            send "{@prefix} &cComando sconosciuto."
                            send "{@prefix} &cUtilizzo: &6/nick <&eset &6| &eclear&6> <&esoprannome&6>"
                            stop
            else if arg-1 is "clear" or "remove":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "nick.clear.other":
                            if {@nick_p} is player's name:
                                send "{@prefix} &cNon hai nessun soprannome impostato!"
                                play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                stop
                            else:
                                remove {@nick_p} from {nick_list::*}
                                set {@nick_p} to player's name
                                save yaml {@data_p}
                                send "{@prefix} &aHai rimosso il tuo soprannome."
                                play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                send "{@prefix} &6Puoi anche rimuoverlo ad un altro giocatore con &c/nick clear <&egiocatore&c>&6."
                                stop
                        else:
                            if {@nick_p} is player's name:
                                send "{@prefix} &cNon hai impostato nessun soprannome!"
                                play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                stop
                            else:
                                remove {@nick_p} from {nick_list::*}
                                set {@nick_p} to player's name
                                save yaml {@data_p}
                                send "{@prefix} &aHai rimosso il tuo soprannome."
                                play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                stop
                else:
                    if arg-3 isn't set:
                        if player has permission "nick.clear.other":
                            set {_arg2} to arg-2 parsed as offline player
                            if {_arg2} is offline:
                                send "{@prefix} &c%{_arg2}% &6è offline!"
                                stop
                            if {@nick_arg2} is {_arg2}'s name:
                                send "{@prefix} &6%{_arg2}% &cnon ha impostato nessun soprannome!"
                                play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                                stop
                            else:
                                remove {@nick_arg2} from {nick_list::*}
                                set {@nick_arg2} to {_arg2}'s name
                                save yaml {@data_arg2}
                                send "{@prefix} &aHai rimosso il soprannome di &b%{_arg2}%&a." to player
                                send "{@prefix} &b%player% &aha rimosso il tuo soprannome." to {_arg2}
                                play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                                stop
                        else:
                            send "{@prefix} &cComando sconosciuto."
                            send "{@prefix} &cUtilizzo: &6/nick <&eset &6| &eclear&6> <&esoprannome&6>"
                            stop
                    else:
                        if player has permission "nick.clear.other":
                            send "{@prefix} &cQuesto comando non richiede parametri aggiuntivi."
                            stop
                        else:
                            send "{@prefix} &cComando sconosciuto."
                            send "{@prefix} &cUtilizzo: &6/nick <&eset &6| &eclear&6> <&esoprannome&6>"
                            stop
            else if arg-1 is "list":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        if player has permission "nick.list":
                            loop {nick_list::*}:
                                send "{@prefix} &6Soprannomi attivi: &e%{nick_list::*}%"
                                stop
                        else:
                            send "{@prefix} &cComando sconosciuto."
                            send "{@prefix} &cUtilizzo: &6/nick <&eset &6| &eclear&6> <&esoprannome&6>"
                            stop
                else:
                    if player has permission "nick.list":
                        send "{@prefix} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
                    else:
                        send "{@prefix} &cComando sconosciuto."
                        send "{@prefix} &cUtilizzo: &6/nick <&eset &6| &eclear&6> <&esoprannome&6>"
                        stop
            else if arg-1 isn't "set", "clear", "remove" or "list":
                if player has permission "nick.other":
                    send "{@prefix} &cComando sconosciuto."
                    send "{@prefix} &cUtilizzo: &6/nick set <&esoprannome&6> [&egiocatore&6]"
                    send "{@prefix} &cUtilizzo: &6/nick clear [&egiocatore&6]"
                    send "{@prefix} &cUtilizzo: &6/nick list"
                    stop
                else:
                    send "{@prefix} &cComando sconosciuto."
                    send "{@prefix} &cUtilizzo: &6/nick set <&esoprannome&6>"
                    send "{@prefix} &cUtilizzo: &6/nick clear"
                    stop
        else:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &6Scegli il soprannome di un giocatore."
                        send "{@prefix} &cUtilizzo: &6/nick <&eset &6| &eclear&6> <&esoprannome&6> <&egiocatore&6>"
                        stop
            else if arg-1 is "set":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &cComando incompleto."
                        send "{@prefix} &cUtilizzo: &6/nick set <&esoprannome&6> <&egiocatore&6>&c."
                        stop
                else:
                    if arg-3 isn't set:
                        send "{@prefix} &cSolo i giocatori possono gestire il proprio soprannome!"
                        stop
                    else:
                        if {@nick_arg3} is arg-3:
                            if {nick_list::*} is "&7Non ci sono soprannomi attivi.":
                                delete {nick_list::*}
                                set {@nick_arg3} to arg-2
                                add {@nick_arg3} to {nick_list::*}
                                save yaml {@data_arg3}
                                send "{@prefix} &aHai impostato &b%arg-2% &acome soprannome per &3%arg-3%&a!" to console
                                send "{@prefix} &aLa &bconsole &ati ha impostato &3%arg-2% &acome soprannome." to arg-3
                                stop
                            else if {nick_list::*} doesn't contain arg-2:
                                set {@nick_arg3} to arg-2
                                add {@nick_arg3} to {nick_list::*}
                                save yaml {@data_arg3}
                                send "{@prefix} &aHai impostato &b%arg-2% &acome soprannome per &3%arg-3%&a!" to console
                                send "{@prefix} &aLa &bconsole &ati ha impostato &3%arg-2% &acome soprannome." to arg-3
                                stop
                            else if {nick_list::*} contains arg-2:
                                send "{@prefix} &6%arg-2% &cè stato già preso da qualcun altro! Scegli un altro soprannome."
                                stop
                        else:
                            send "{@prefix} &6%arg-3% &cha già un soprannome! Rimuovilo prima di poterne impostare un altro."
                            stop
            else if arg-1 is "clear" or "remove":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        send "{@prefix} &cSolo i giocatori possono gestire il proprio soprannome!"
                        stop
                else:
                    if arg-3 isn't set:
                        set {_arg2} to arg-2 parsed as offline player
                        if {@nick_arg2} is {_arg2}'s name:
                            send "{@prefix} &6%{_arg2}% &cnon ha impostato nessun soprannome!"
                            stop
                        else:
                            remove {@nick_arg2} from {nick_list::*}
                            set {@nick_arg2} to {_arg2}'s name
                            save yaml {@data_arg2}
                            send "{@prefix} &aHai rimosso il soprannome di &b%{_arg2}%&a." to console
                            send "{@prefix} &aLa &bconsole &aha rimosso il tuo soprannome." to {_arg2}
                            stop
                    else:
                        send "{@prefix} &cQuesto comando non richiede parametri aggiuntivi."
                        stop
            else if arg-1 is "list":
                if arg-2 isn't set:
                    if arg-3 isn't set:
                        loop {nick_list::*}:
                            send "{@prefix} &6Soprannomi attivi: &e%{nick_list::*}%"
                            stop
                else:
                    send "{@prefix} &cQuesto comando non richiede parametri aggiuntivi."
                    stop
            else if arg-1 isn't "set", "clear", "remove" or "list":
                send "{@prefix} &cComando sconosciuto."
                send "{@prefix} &cUtilizzo: &6/nick set <&esoprannome&6> <&egiocatore&6>"
                send "{@prefix} &cUtilizzo: &6/nick clear <&egiocatore&6>"
                send "{@prefix} &cUtilizzo: &6/nick list"
                stop

on tab complete of "/nick" or "/nickname":
    set tab completions for position 1 to "set", "list" and "clear"
    if tab arg-1 is "set":
        set tab completions for position 2 to "[<soprannome>]"


# ZONA DEBUG

#on join:
    #delete {nick_list::*}