options:
    fight: &a● &a&lPvP abilitato &a●
    no_fight: &c● &c&lPvP disabilitato &c●

    fight_broadcast: &8[&2🗡&8] &aPvP globale abilitato!
    no_fight_broadcast: &8[&4🗡&8] &cPvP globale disabilitato!

    fight_message: &c&lPrepara le armi. &cÈ il momento di combattere!
    no_fight_message: &a&lRiponi le armi. &aNon dovrai più combattere!

    no_pvp: &8[&4🗡&8] &cIl PvP è disabilitato!

on load:
    if {pvp} is not set:
        set {pvp} to "{@no_fight}"
    if {pvp} is not set:
        set {pvp} to "{@no_fight}"
        
command /pvp:
    permission: pvp.toggle
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    executable by: player, console
    description: Attiva o disattiva il PvP nel server.
    trigger:
        if {pvp} is "{@fight}":
            set {pvp} to "{@no_fight}"
            set {pvp} to "{@no_fight}"
            broadcast "{@no_fight_broadcast}"
            send action bar "{@no_fight_message}" to all players
            stop
        else if {pvp} is "{@no_fight}":
            set {pvp} to "{@fight}"
            set {pvp} to "{@fight}"
            broadcast "{@fight_broadcast}"
            send action bar "{@fight_message}" to all players
            stop

on damage:
    if attacker is a player:
        if victim is a player:
            if {pvp} is "{@no_fight}":
                if damage cause is not fall:
                    cancel event
                    send "{@no_pvp}" to attacker

on projectile collide:
    if shooter of event-projectile is a player:
        if event-entity is a player:
            if {pvp} is "{@no_fight}":
                send "{@no_pvp}" to shooter of event-projectile
                cancel event
            else:
                if projectile is snowball:
                    damage player by 0.00001
                    #create a safe explosion with force 2 at player
                    #push player backwards with force 0.3
                    #push player upwards with force 0.4
                if projectile is egg:
                    damage player by 0.00001
                    #push player upwards with force 0.5
                

# RENDERE LE NOTIFICHE DEL PVP PERSONALIZZABILI DAL MENU DELLE NOTIFICHE TRAMITE LE IMPOSTAZIONI DEL GIOCATORE