options:
    prefix: &4[&e&lSTATUS&4]
    default_status: &cNessuno stato impostato.

    data: "data-%player's uuid%"
    status: yaml value "player_info.player.status.new" in "data-%player's uuid%"
    old_status: yaml value "player_info.player.status.old" in "data-%player's uuid%"
    genre: yaml value "genre"
    settings: "settings-%player's uuid%"

command /status [<text>] [<text>]: #NUOVO PARAMETRO: "SETTEMP" E AGGIUNTA DI UN ULTERIORE PARAMETRO (ARG-3) PER SPECIFICARE IL TEMPO DI SCADENZA DELLO STATO (IN ARRIVO...)
    permission: status.use
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    description: Imposta uno stato personale
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                if {@status} isn't "{@default_status}":
                    set {_status} to yaml value "player_info.player.status.new" in "data-%player's uuid%"
                    send "{@prefix} &fIl tuo stato attuale: &7%{_status}%"
                    stop
                else:
                    send "{@prefix} &cNon hai ancora uno stato."
                    send "{@prefix} &cImpostalo con &6/status set <stato>&c."
                    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                    stop
            else if arg-1 is "set":
                if arg-2 isn't set:
                    send "{@prefix} &cComando incompleto."
                    send "{@prefix} &cUtilizzo: &6/status set <stato>"
                    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                    stop
                else:
                    if {@status} isn't "{@default_status}":
                        #set {_old_status} to yaml value "player_info.player.status.old" in "data-%player's uuid%"
                        set {@old_status} to {@status}
                        set {@status} to arg-2
                        set {_status} to yaml value "player_info.player.status.new" in "data-%player's uuid%"
                        send "{@prefix} &aHai aggiornato il tuo stato."
                        send "{@prefix} &7%{_status}%"
                        play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                        save yaml {@data}
                        stop
                    else:
                        set {@status} to arg-2
                        set {@old_status} to "{@default_status}"
                        send "{@prefix} &aHai impostato il tuo stato."
                        set {_status} to yaml value "player_info.player.status.new" in "data-%player's uuid%"
                        send "{@prefix} &7%{_status}%"
                        play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                        save yaml {@data}
                        stop
            else if arg-1 is "delete":
                if arg-2 isn't set:
                    if {@status} isn't "{@default_status}":
                        if {@genre} in {@settings} is "%{server.genre.male}%":
                            send formatted "{@prefix} &cSei sicuro di voler eliminare il tuo stato? <suggest command:sì>&2&l[SÌ]<reset> <suggest command:no>&4&l[NO]<reset>"
                        else if {@genre} in {@settings} is "%{server.genre.female}%":
                            send formatted "{@prefix} &cSei sicura di voler eliminare il tuo stato? <suggest command:sì>&2&l[SÌ]<reset> <suggest command:no>&4&l[NO]<reset>"
                        play sound "entity.player.levelup" with volume 1 and pitch 2 at player for player
                        set {status.%player%.confirm} to true
                        stop
                    else:
                        send "{@prefix} &cNon puoi eliminare il tuo stato se prima non ne imposti uno!"
                        play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                        stop
                else:
                    send "{@prefix} &cQuesto comando non necessita di ulteriori parametri."
                    stop
            else if arg-1 isn't "set" or "delete":
                send "{@prefix} &cComando sconosciuto."
                send "{@prefix} &cUtilizzo: &6/status set <stato>"
                send "{@prefix} &cUtilizzo: &6/status delete"
                stop
        else:
            send "{@prefix} &cSolo i giocatori possono eseguire questo comando."
            stop

on tab complete of "/status":
    set tab completions for position 1 to "set" and "delete"
    if tab arg-1 is "set":
        set tab completions for position 2 to "[<stato>]"
        
on chat:
    if {status.%player%.confirm} is true:
        cancel event
        if message is "si", "sì", "yes", "s" or "y":
            set {@old_status} to {@status}
            set {@status} to "{@default_status}"
            send "{@prefix} &aStato eliminato con successo." to player
            play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
            delete {status.%player%.confirm}
            save yaml {@data}
        else if message is "no" or "n":
            send "{@prefix} &aRicevuto." to player
            play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
            delete {status.%player%.confirm}
        else:
            send "{@prefix} &cNon capisco cosa intendi con &f%message%&c!"
            if {@genre} in {@settings} is "%{server.genre.male}%":
                send ""
                send formatted "{@prefix} &cSei sicuro di voler eliminare il tuo stato? <suggest command:sì>&2&l[SÌ]<reset> <suggest command:no>&4&l[NO]<reset>"
            if {@genre} in {@settings} is "%{server.genre.female}%":
                send ""
                send formatted "{@prefix} &cSei sicura di voler eliminare il tuo stato? <suggest command:sì>&2&l[SÌ]<reset> <suggest command:no>&4&l[NO]<reset>"
            play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
