options:
    confirm_sound: block.note_block.pling
    error_sound: entity.enderman.teleport

    more_info: &eClicca per esplorare.
    wiki_link: &eClicca per visitare la Wiki dell'SMP.
    gui_config: &cLa GUI è in fase di creazione.

    gui_glass_pane: yaml value "personalization.gui_background.enabled" in "settings-%{_p}'s uuid%"
    genre: yaml value "genre"
    file: "settings-%{_p}'s uuid%"

command /wiki:
    executable by: player, console
    trigger:
        if sender is player:
            send ""
            send "&a&lWIKI DELL'SMP"
            send "&fClicca sull'argomento che ti interessa per aprire la relativa pagina."
            send ""
            send " &9&l● Server"
            send "  &b● <link:https://wiki.ultrasmp.org/disagiosmp>&b&nIntroduzione"
            send "  &b● <link:https://wiki.ultrasmp.org/disagiosmp/il-server/profilo-smp>&b&nProfilo SMP"
            send "  &b● <link:https://wiki.ultrasmp.org/disagiosmp/il-server/fama-e-reputazioni>&b&nFama e Reputazioni"
            send "  &b● <link:https://wiki.ultrasmp.org/disagiosmp/il-server/abilita>&b&nAbilità"
            send "  &b● <link:https://wiki.ultrasmp.org/disagiosmp/il-server/medaglie>&b&nMedaglie"
            send "  &b● <link:https://wiki.ultrasmp.org/disagiosmp/il-server/impostazioni>&b&nImpostazioni"
            send ""
            send " &9&l● Aggiornamenti e Novità"
            send "  &b● <link:https://wiki.ultrasmp.org/disagiosmp/aggiornamenti-e-novita/changelog>&b&nChangelog"
            send ""
            stop
        else:
            send ""
            send "&a&lWIKI DELL'SMP"
            send "&fClicca sull'argomento che ti interessa per aprire la relativa pagina."
            send ""
            send " &9&l● Server"
            send "  &b● &b&nIntroduzione&f: https://wiki.ultrasmp.org/disagiosmp"
            send "  &b● &b&nProfilo SMP&f: https://wiki.ultrasmp.org/disagiosmp/il-server/profilo-smp"
            send "  &b● &b&nFama e Reputazioni&f: https://wiki.ultrasmp.org/disagiosmp/il-server/fama-e-reputazioni"
            send "  &b● &b&nAbilità&f: https://wiki.ultrasmp.org/disagiosmp/il-server/abilita"
            send "  &b● &b&nMedaglie&f: https://wiki.ultrasmp.org/disagiosmp/il-server/medaglie"
            send "  &b● &b&nImpostazioni&f: https://wiki.ultrasmp.org/disagiosmp/il-server/impostazioni"
            send ""
            send " &9&l● Aggiornamenti e Novità"
            send "  &b● &b&nChangelog&f: https://wiki.ultrasmp.org/disagiosmp/aggiornamenti-e-novita/changelog"
            send ""
            stop

function openMainWikiGUI(p: player):
    if {@gui_glass_pane} is true:
        if {@genre} in {@file} is "%{server.genre.male}%":
            set {_gui} to a new chest inventory with 6 rows named "Wiki dell'SMP [BETA]"
            set slot 0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 37, 38, 41, 42, 43, 44, 45, 46, 47, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
            set slot 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
            set slot 4 of {_gui} to book named "&eWiki dell'SMP &c[BETA]" with lore "&7Vuoi saperne di più su una o più", "&7funzionalità presenti nel server?", "&7Questa guida ti saprà aiutare per", "&7qualsiasi cosa... basta cercare!", "&f" and "{@gui_config}"#with lore "&7Clicca sulle seguenti categorie", "&7per scoprire i vari argomenti", "&7ed essere reindirizzato nella" and "&7loro rispettiva pagina."
            set slot 22 of {_gui} to paper named "&cWiki in creazione!" with lore "&7Questa GUI è in fase di creazione,", "&7pertanto dovrai aspettare prima", "&7di poterla utilizzare.", "&f" and "{@wiki_link}"
            set slot 48 of {_gui} to arrow named "&aIndietro" with lore "&7Torna a Profilo &7&lSMP"
            set slot 49 of {_gui} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
            open {_gui} to {_p}
        else if {@genre} in {@file} is "%{server.genre.female}%":
            set {_gui} to a new chest inventory with 6 rows named "Wiki dell'SMP [BETA]"
            set slot 0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 37, 38, 41, 42, 43, 44, 45, 46, 47, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
            set slot 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
            set slot 4 of {_gui} to book named "&eWiki dell'SMP &c[BETA]" with lore "&7Vuoi saperne di più su una o più", "&7funzionalità presenti nel server?", "&7Questa guida ti saprà aiutare per", "&7qualsiasi cosa... basta cercare!", "&f" and "{@gui_config}"#with lore "&7Clicca sulle seguenti categorie", "&7per scoprire i vari argomenti", "&7ed essere reindirizzata nella" and "&7loro rispettiva pagina."
            set slot 22 of {_gui} to paper named "&cWiki in creazione!" with lore "&7Questa GUI è in fase di creazione,", "&7pertanto dovrai aspettare prima", "&7di poterla utilizzare.", "&f" and "{@wiki_link}"
            set slot 48 of {_gui} to arrow named "&aIndietro" with lore "&7Torna a Profilo &7&lSMP"
            set slot 49 of {_gui} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
            open {_gui} to {_p}
    else:
        if {@genre} in {@file} is "%{server.genre.male}%":
            set {_gui} to a new chest inventory with 6 rows named "Wiki dell'SMP [BETA]"
            set slot 4 of {_gui} to book named "&eWiki dell'SMP &c[BETA]" with lore "&7Vuoi saperne di più su una o più", "&7funzionalità presenti nel server?", "&7Questa guida ti saprà aiutare per", "&7qualsiasi cosa... basta cercare!", "&f" and "{@gui_config}"#with lore "&7Clicca sulle seguenti categorie", "&7per scoprire i vari argomenti", "&7ed essere reindirizzato nella" and "&7loro rispettiva pagina."
            set slot 22 of {_gui} to paper named "&cWiki in creazione!" with lore "&7Questa GUI è in fase di creazione,", "&7pertanto dovrai aspettare prima", "&7di poterla utilizzare.", "&f" and "{@wiki_link}"
            set slot 48 of {_gui} to arrow named "&aIndietro" with lore "&7Torna a Profilo &7&lSMP"
            set slot 49 of {_gui} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
            open {_gui} to {_p}
        else if {@genre} in {@file} is "%{server.genre.female}%":
            set {_gui} to a new chest inventory with 6 rows named "Wiki dell'SMP [BETA]"
            set slot 4 of {_gui} to book named "&eWiki dell'SMP &c[BETA]" with lore "&7Vuoi saperne di più su una o più", "&7funzionalità presenti nel server?", "&7Questa guida ti saprà aiutare per", "&7qualsiasi cosa... basta cercare!", "&f" and "{@gui_config}"#with lore "&7Clicca sulle seguenti categorie", "&7per scoprire i vari argomenti", "&7ed essere reindirizzata nella" and "&7loro rispettiva pagina."
            set slot 22 of {_gui} to paper named "&cWiki in creazione!" with lore "&7Questa GUI è in fase di creazione,", "&7pertanto dovrai aspettare prima", "&7di poterla utilizzare.", "&f" and "{@wiki_link}"
            set slot 48 of {_gui} to arrow named "&aIndietro" with lore "&7Torna a Profilo &7&lSMP"
            set slot 49 of {_gui} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
            open {_gui} to {_p}

on inventory click:
    if name of event-inventory is "Wiki dell'SMP [BETA]":
        if type of event-inventory is chest inventory:
            if index of event-slot isn't 22, 48 or 49:
                cancel event
            else if index of event-slot is 22:
                if click type is left mouse button:
                    cancel event
                    close player's inventory
                    send formatted "%{server.prefix.main}% &aIntanto che la GUI sta essendo configurata, consulta la Wiki dell'SMP <link:https://wiki.ultrasmp.org>&b&nqui&a."
                    play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
                else:
                    cancel event
            else if index of event-slot is 48:
                if click type is left mouse button:
                    cancel event
                    openProfileGui(player)
                else:
                    cancel event
            else if index of event-slot is 49:
                if click type is left mouse button:
                    cancel event
                    close player's inventory
                else:
                    cancel event