#========================================================================
# ANTI XRAY PER LA VERSIONE 1.19.X DI MINECRAFT
#
# Supporto Discord: https://discord.gg/bEDGQxc
#
# Youtube: https://www.youtube.com/c/SoulStriker
#=========================================================================
#PlaceHolders with PlaceHolderAPI: "/papi ecloud download Skript"

#Iron Ore - %skript_iore.{player}%
#Deepslate Iron Ore - %skript_diore.{player}%
#Copper Ore - %skript_core.{player}%
#Deepslate Copper Ore - %skript_dcore.{player}%
#Gold Ore - %skript_gore.{player}%
#Deepslate Gold Ore - %skript_dgore.{player%}
#Lapis Ore - %skript_lore.{player}%
#Deepslate Lapis Ore - %skript_dlore.{player}%
#Redstone Ore - %skript_rore.{player}%
#Deepslate Redstone Ore - %skript_drore.{player}%
#Diamond Ore - %skript_dore.{player}%
#Deepslate Diamond Ore - %skript_ddore.{player}%
#Emerald Ore - %skript_eore.{player}%
#Deepslate Emerald Ore - %skript_deore.{player}%

#-------------- INIZIO CONFIGURAZIONE --------------#

    #--------------------------------------------#
    #         CONFIGURAZIONE PRINCIPALE          #
    #--------------------------------------------#
options:
    
    prefix: &8[&4&lAXR&8]
    
    truemsg: &7[&a✔ Abilitato&7]
    
    falsemsg: &7[&c✘ Disabilitato&7]
    
    iron_alert_msg: &7ha trovato &f%{icounter.%arg-player%}% Ferro &7in &e%{timer}% &7secondi!
    
    deepslate_iron_alert_msg: &7ha trovato &f%{dicounter.%arg-player%}% Ferro in ardesia profonda &7in &e%{timer}% &7secondi!
    
    gold_alert_msg: &7ha trovato &6%{gcounter.%arg-player%}% Oro &7in &e%{timer}% &7secondi!
    
    deepslate_gold_alert_msg: &7ha trovato &f%{dgcounter.%arg-player%}% Oro in ardesia profonda &7in &e%{timer}% &7secondi!
    
    copper_alert_msg: &7ha trovato &f%{ccounter.%arg-player%}% Rame &7in &e%{timer}% &7secondi!
    
    deepslate_copper_alert_msg: &7ha trovato &f%{dccounter.%arg-player%}% Rame in ardesia profonda &7in &e%{timer}% &7secondi!
    
    redstone_alert_msg: &7ha trovato &4%{rcounter.%arg-player%}% Redstone &7in &e%{timer}% &7secondi!
    
    deepslate_redstone_alert_msg: &7ha trovato &4%{drcounter.%arg-player%}% Redstone in ardesia profonda &7in &e%{timer}% &7secondi!
    
    lapis_alert_msg: &7ha trovato &1%{lcounter.%arg-player%}% Lapislazzuli &7in &e%{timer}% &7secondi!
    
    deepslate_lapis_alert_msg: &7ha trovato &1%{dlcounter.%arg-player%}% Lapislazzuli in ardesia profonda &7in &e%{timer}% &7secondi!
    
    diamond_alert_msg: &7ha trovato &b%{dcounter.%arg-player%}% Diamanti &7in &e%{timer}% &7secondi!
    
    deepslate_diamond_alert_msg: &7ha trovato &b%{ddcounter.%arg-player%}% Diamanti in ardesia profonda &7in &e%{timer}% &7secondi!
    
    emerald_alert_msg: &7ha trovato &a%{ecounter.%arg-player%}% Smeraldi &7in &e%{timer}% &7secondi!
    
    deepslate_emerald_alert_msg: &7ha trovato &a%{decounter.%arg-player%}% Smeraldi in ardesia profonda &7in &e%{timer}% &7secondi!

    ancient_debris_msg: &7ha trovato &f%{ncounter.%arg-player%}% Detriti Antichi &7in &e%{timer}% &7secondi!
    
    #message that will appear when you hover over the alert message
    
    alert_hover_msg: &7Clicca per &6teletrasportarti &7da (&e%arg-player%&7)
    
    Versione: 2.2.6
    
    Versione_MC: 1.19

    #Command to execute when you click on the alert message.    
    #Whoever clicks on the alerts will need permission for the following command(s).
    
    #to disable commands put `#` in front. It might load with an error, but it will still work properly!    
    #example -> #alert_command1: vanish %player% <- 
    
    alert_command1: /tp %arg-player%
    #only use a "/" in front for the 1st command!
    
    alert_command2: gamemode spectator %player%
    alert_command3: vanish %player%
    
    #--------------------------------------------#
    #           CONFIGURAZIONE SUONI             #
    #--------------------------------------------#
    #Make sure you have the right sounds for your server version!
    #https://www.planetminecraft.com/blog/all-minecraft-sound-id-s-1-11-2/
    
    enabled_sound: entity.player.levelup
    disabled_sound: entity.item.break
    error_sound: entity.endermen.teleport
    
    #=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
    #--------------------------------------------#
    #       SISTEMA RILEVAMENTO AUTOMATICO       #
    #--------------------------------------------#
    
    #Auto-detection must be enabled in the GUI for this to work!
    #autokick for which ore type and how many is mined within the timer amount.
    #if it reaches that amount spefic amount for any ore, they will get punished.
    
    #!!USE "%arg-player%" for the player's name!!
    
    auto_alert_message: &e%arg-player% &6potrebbe star usando la XRay!
    
    auto_command1: kick %arg-player% &8[&4&lAXR&8] &c&lDisattiva la XRay o verrai bannato/a!
    auto_command2: add another command 
    auto_command3: add another command
    auto_command4: add another command
    
    #how many times should autokick happen before the next punishment.
    #example: two times the autokick will happen, then on the 3rd time, it will go to the next punishment.
    
    autokicktime: 3
    
    auto_next_message: &e%arg-player% &cha raggiunto il limite massimo di avvertimenti! 
    
    auto_next_command1: ir forcebackup player %arg-player%
    auto_next_command2: minecraft:clear %arg-player%
    auto_next_command3: tempban %arg-player% 4h Come punizione per aver utilizzato l'XRay (nonostante fosse vietato!), abbiamo deciso di temp-bannarti. Potrai rientrare SOLO dopo aver disattivato l'XRay!
    auto_next_command4: add another command here
    
    #-------------- FINE CONFIGURAZIONE --------------#
#==========================================================================

#========================================================================== 
    #--------------------------------------------#
    #             AVVIO DEL SISTEMA              #
    #--------------------------------------------#
on load:
    wait 6 tick
    send "&8[&4&lAXR&8] &9Anti-XRay caricato e pronto! Versione MC: {@Versione_MC}" to console
    if {timer} is not set:
        set {timer} to 30
    if {iron_amount_mined_in_x_sec} is not set:
        set {iron_amount_mined_in_x_sec} to 20
    if {deepslate_iron_amount_mined_in_x_sec} is not set:
        set {deepslate_iron_amount_mined_in_x_sec} to 20
    if {copper_amount_mined_in_x_sec} is not set:
        set {copper_amount_mined_in_x_sec} to 15
    if {deepslate_copper_amount_mined_in_x_sec} is not set:
        set {deepslate_copper_amount_mined_in_x_sec} to 15
    if {nether_amount_mined_in_x_sec} is not set:
        set {nether_amount_mined_in_x_sec} to 3
    if {lapis_amount_mined_in_x_sec} is not set:
        set {lapis_amount_mined_in_x_sec} to 11
    if {deepslate_lapis_amount_mined_in_x_sec} is not set:
        set {deepslate_lapis_amount_mined_in_x_sec} to 11
    if {redstone_amount_mined_in_x_sec} is not set:
        set {redstone_amount_mined_in_x_sec} to 16
    if {deepslate_redstone_amount_mined_in_x_sec} is not set:
        set {deepslate_redstone_amount_mined_in_x_sec} to 16
    if {gold_amount_mined_in_x_sec} is not set:
        set {gold_amount_mined_in_x_sec} to 15
    if {deepslate_gold_amount_mined_in_x_sec} is not set:
        set {deepslate_gold_amount_mined_in_x_sec} to 15
    if {emerald_amount_mined_in_x_sec} is not set:
        set {emerald_amount_mined_in_x_sec} to 3
    if {deepslate_emerald_amount_mined_in_x_sec} is not set:
        set {deepslate_emerald_amount_mined_in_x_sec} to 3
    if {diamond_amount_mined_in_x_sec} is not set:
        set {diamond_amount_mined_in_x_sec} to 5
    if {deepslate_diamond_amount_mined_in_x_sec} is not set:
        set {deepslate_diamond_amount_mined_in_x_sec} to 5
		
    if {detect_iron_amount_mined_in_x_sec} is not set:
        set {detect_iron_amount_mined_in_x_sec} to 30
    if {detect_deepslate_iron_amount_mined_in_x_sec} is not set:
        set {detect_deepslate_iron_amount_mined_in_x_sec} to 30
    if {detect_copper_amount_mined_in_x_sec} is not set:
        set {detect_copper_amount_mined_in_x_sec} to 30
    if {detect_deepslate_copper_amount_mined_in_x_sec} is not set:
        set {detect_deepslate_copper_amount_mined_in_x_sec} to 30
    if {detect_gold_amount_mined_in_x_sec} is not set:
        set {detect_gold_amount_mined_in_x_sec} to 25
    if {detect_deepslate_gold_amount_mined_in_x_sec} is not set:
        set {detect_deepslate_gold_amount_mined_in_x_sec} to 25
    if {detect_diamond_amount_mined_in_x_sec} is not set:
        set {detect_diamond_amount_mined_in_x_sec} to 13
    if {detect_deepslate_diamond_amount_mined_in_x_sec} is not set:
        set {detect_deepslate_diamond_amount_mined_in_x_sec} to 13
    if {detect_emerald_amount_mined_in_x_sec} is not set:
        set {detect_emerald_amount_mined_in_x_sec} to 7
    if {detect_deepslate_emerald_amount_mined_in_x_sec} is not set:
        set {detect_deepslate_emerald_amount_mined_in_x_sec} to 7
    if {detect_debris_amount_mined_in_x_sec} is not set:
        set {detect_debris_amount_mined_in_x_sec} to 7
    if {counter.name} or {autokick.name} or {orealerts.name} or {obf.name} or {con.name} is not set:
        set {counter.name} or {autokick.name} or {orealerts.name} or {obf.name} or {con.name} to "&8[&eDisattivato&8]"
    if {airon.name} or {adiron.name} or {agold.name} or {adgold.name} or {adiamond.name} or {addiamond.name} or {aemerald.name} or {ademerald.name} or {autoiron.name} or {autodeepslateiron.name} or {autogold.name} or {autodeepslategold.name} or {autoemerald.name} or {autodeepslateemerald.name} or {autodiamond.name} or {autodeepslatediamond.name} or {autodebris.name} is not set:
        set {airon.name} or {adiron.name} or {agold.name} or {adgold.name} or {adiamond.name} or {addiamond.name} or {aemerald.name} or {ademerald.name} or {autoiron.name} or {autodeepslateiron.name} or {autogold.name} or {autodeepslategold.name} or {autoemerald.name} or {autodeepslateemerald.name} or {autodiamond.name} or {autodeepslatediamond.name} or {autodebris.name} to "&8[&eAttivato&8]"
    if {anether.name} or {alapis.name} or {adlapis.name} or {aredstone.name} or {adredstone.name} or {offorealerts.name} is not set:
        set {anether.name} or {alapis.name} or {adlapis.name} or {aredstone.name} or {adredstone.name} to "&8[&eAttivato&8]"
    loop all players:
        if {dore.%loop-player%} or {ddore.%loop-player%} or {core.%loop-player%} or {dcore.%loop-player%} or {eore.%loop-player%} or {deore.%loop-player%} or {gore.%loop-player%} or {dgore.%loop-player%} or {iore.%loop-player%} or {diore.%loop-player%} or {lore.%loop-player%} or {dlore.%loop-player%} or {rore.%loop-player%} or {drore.%loop-player%} or {nore.%loop-player%} is not set:
            set {dore.%loop-player%} or {ddore.%loop-player%} or {core.%loop-player%} or {dcore.%loop-player%} or {eore.%loop-player%} or {deore.%loop-player%} or {gore.%loop-player%} or {dgore.%loop-player%} or {iore.%loop-player%} or {diore.%loop-player%} or {lore.%loop-player%} or {dlore.%loop-player%} or {rore.%loop-player%} or {drore.%loop-player%} or {nore.%loop-player%} to 0
        if {offdore::%loop-player%} or {offddore::%loop-player%} or {offcore::%loop-player%} or {offdcore::%loop-player%} or {offeore::%loop-player%} or {offdeore::%loop-player%} or {offgore::%loop-player%} or {offdgore::%loop-player%} or {offiore::%loop-player%} or {offdiore::%loop-player%} or {offnore::%loop-player%} is not set:
            set {offdore::%loop-player%} or {offddore::%loop-player%} or {offcore::%loop-player%} or {offdcore::%loop-player%} or {offeore::%loop-player%} or {offdeore::%loop-player%} or {offgore::%loop-player%} or {offdgore::%loop-player%} or {offiore::%loop-player%} or {offdiore::%loop-player%} or {offnore::%loop-player%} to 0
on join:
    if {dore.%player%} or {ddore.%player%} or {core.%player%} or {dcore.%player%} or {eore.%player%} or {deore.%player%} or {gore.%player%} or {dgore.%player%} or {iore.%player%} or {diore.%player%} or {lore.%player%} or {dlore.%player%} or {rore.%player%} or {drore.%player%} or {nore.%player%} is not set:
        set {dore.%player%} or {ddore.%player%} or {core.%player%} or {dcore.%player%} or {eore.%player%} or {deore.%player%} or {gore.%player%} or {dgore.%player%} or {iore.%player%} or {diore.%player%} or {lore.%player%} or {dlore.%player%} or {rore.%player%} or {drore.%player%} or {nore.%player%} to 0
    if {offdore::%player%} or {offddore::%player%} or {offcore::%player%} or {offdcore::%player%} or {offeore::%player%} or {offdeore::%player%} or {offgore::%player%} or {offdgore::%player%} or {offiore::%player%} or {offdiore::%player%} or {offnore.%player%} is not set:
        set {offdore::%player%} or {offddore::%player%} or {offcore::%player%} or {offdcore::%player%} or {offeore::%player%} or {offdeore::%player%} or {offgore::%player%} or {offdgore::%player%} or {offiore::%player%} or {offdiore::%player%} or {offnore.%player%} to 0
    wait 5 seconds
    if player has permission "axr.alerts":
        if {offorealerts} is true:
            if {offalerts::*} is set:
                send " "
                message formatted "{@prefix} &7Gli avvisi offline sono stati &etriggerati! <tooltip:&eVisualizza gli avvisi Offline><cmd:/offlineaxr>&7[&eCLICCA QUI&7]" to player
                send " "
    #--------------------------------------------#
    #                    CHAT                    #
    #--------------------------------------------#
on chat:
    if {timeset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {timer} to {_timer}
        send "&8[&4&lAXR&8] &7Hai &amodificato &7il timer a &7(&6&l%{timer}%&7) &7secondi!"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {timeset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    if {offlinelookup.%player%} is true:
        cancel event
        set {_p} to message parsed as offline player
        execute player command "/ofa lookup %{_p}%"
        delete {offlinelookup.%player%}
    if {worldset.%player%} is true:
        cancel event
        set {enabled.world} to message parsed as world
        if {eworld::*} contains {enabled.world}:
            send "&cERRORE&6>> &a%{enabled.world}% &cè già aggiunto!"
            delete {worldset.%player%}
            wait 10 ticks
            execute player command "/axr world"
        else:
            send "&8[&4&lAXR&8] &7Hai &aabilitato &7(&a&l%{enabled.world}%&7)"
            add {enabled.world} to {eworld::*}
            play sound "{@enabled_sound}" with volume 1 at player   
            wait 5 ticks
            delete {worldset.%player%}
            delete {all::*}
            wait 1 ticks
            execute player command "/axr world"
    if {rworldset.%player%} is true:
        cancel event
        set {remove.world} to message parsed as world
        if {eworld::*} contains {remove.world}:
            send "&8[&4&lAXR&8] &7Hai &crimosso &7(&c&l%{remove.world}%&7)"
            play sound "{@enabled_sound}" with volume 1 at player   
            wait 5 ticks
            remove {remove.world} from {eworld::*}
            delete {rworldset.%player%}
            delete {all::*}
            wait 1 ticks
            execute player command "/axr world"
        else:
            send "&cERROR&6>> &a%{remove.world}% &cnon è abilitato!"
            delete {rworldset.%player%}
            wait 10 ticks
            execute player command "/axr world"             
    if {talk.%player%} is true:
        cancel event
        set {_number} to message parsed as number
        set {hideradius} to {_number}
        send "&8[&4&lAXR&8] &7Hai &amodificato &7il raggio a &7(&6&l%{hideradius}%&7)"
        play sound "{@enabled_sound}" with volume 1 at player
        wait 5 ticks
        delete {talk.%player%}
        wait 1 ticks
        execute player command "/axr axrhsettings"
    if {lookup.%player%} is true:
        cancel event
        set {_p} to message parsed as offline player
        wait 1 tick
        if {_p} is online:
            send "&8[&4&lAXR&8] &7Sto controllando &e%{_p}%&7..."
            play sound "{@enabled_sound}" with volume 1 at player
            wait 5 ticks
            delete {lookup.%player%}
            wait 1 ticks
            execute player command "/axr orecount ores %{_p}%"
            stop
        if {_p} has played before:
            send "&8[&4&lAXR&8] &7Sto controllando &e%{_p}%&7..."
            play sound "{@enabled_sound}" with volume 1 at player
            wait 5 ticks
            delete {lookup.%player%}
            wait 1 ticks
            execute player command "/axr orecount ores %{_p}%"
            stop
        if {_p} has not played before:
            send "&8[&4&lAXR&8] &c&lERRORE &e>> &7Quel giocatore non è mai entrato!"
            delete {lookup.%player%}
            play sound "{@error_sound}" with volume 1 at player
            stop
#--- FERRO ---#
    if {ironset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {iron_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{iron_amount_mined_in_x_sec}% &7per &fFerro"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {ironset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- FERRO IN ARDESIA PROFONDA ---#
    if {deepslateironset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {deepslate_iron_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{deepslate_iron_amount_mined_in_x_sec}% &7per &fFerro in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslateironset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- RAME ---#
    if {copperset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {copper_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{copper_amount_mined_in_x_sec}% &7per &dRame"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {copperset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- RAME IN ARDESIA PROFONDA ---#
    if {deepslatecopperset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {deepslate_copper_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{deepslate_copper_amount_mined_in_x_sec}% &7per &dRame in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslatecopperset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- ORO ---#
    if {goldset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {gold_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &6&l%{gold_amount_mined_in_x_sec}% &7per &6Oro"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {goldset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- ORO IN ARDESIA PROFONDA ---#
    if {deepslategoldset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {deepslate_gold_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &6&l%{deepslate_gold_amount_mined_in_x_sec}% &7per &6Oro in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslategoldset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- SMERALDO ---#
    if {emeraldset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {emerald_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &a&l%{emerald_amount_mined_in_x_sec}% &7per &aSmeraldo"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {emeraldset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- SMERALDO IN ARDESIA PROFONDA ---#
    if {deepslateemeraldset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {deepslate_emerald_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &a&l%{deepslate_emerald_amount_mined_in_x_sec}% &7per &aSmeraldo in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslateemeraldset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- DIAMANTE ---#
    if {diamondset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {diamond_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &b&l%{diamond_amount_mined_in_x_sec}% &7per &bDiamante"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {diamondset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- DIAMANTE IN ARDESIA PROFONDA ---#  
    if {deepslatediamondset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {deepslate_diamond_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &b&l%{deepslate_diamond_amount_mined_in_x_sec}% &7per &bDiamante in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslatediamondset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
# --- REDSTONE ---#
    if {redset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {redstone_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &4&l%{redstone_amount_mined_in_x_sec}% &7per &cRedstone"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {redset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- REDSTONE IN ARDESIA PROFONDA ---#
    if {deepslateredset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {deepslate_redstone_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &4&l%{deepslate_redstone_amount_mined_in_x_sec}% &7per &cRedstone in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslateredset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- LAPISLAZZULI ---#  
    if {lapisset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {lapis_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &1&l%{lapis_amount_mined_in_x_sec}% &7per &1Lapislazzuli"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {lapisset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- LAPISLAZZULI IN ARDESIA PROFONDA ---#  
    if {deepslatelapisset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {deepslate_lapis_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &1&l%{deepslate_lapis_amount_mined_in_x_sec}% &7per &1Lapislazzuli in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslatelapisset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- DETRITI ANTICHI ---#
    if {netherset.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {nether_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{nether_amount_mined_in_x_sec}% &7per &fDetriti antichi"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {netherset.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- FERRO (AUTOMATICO) ---#
    if {ironauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_iron_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{detect_iron_amount_mined_in_x_sec}% &7per &fFerro"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {ironauto.%player%}
        wait 1 ticks
        
#--- FERRO IN ARDESIA PROFONDA (AUTOMATICO) ---#    
    if {deepslateironauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_deepslate_iron_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{detect_deepslate_iron_amount_mined_in_x_sec}% &7per &fFerro in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslateironauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- RAME (AUTOMATICO) ---#
    if {copperauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_copper_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{detect_copper_amount_mined_in_x_sec}% &7per &dRame"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {copperauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- RAME IN ARDESIA PROFONDA (AUTOMATICO) ---# 
    if {deepslatecopperauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_deepslate_copper_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{detect_deepslate_copper_amount_mined_in_x_sec}% &7per &dRame"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslatecopperauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- ORO (AUTOMATICO) ---#  
    if {goldauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_gold_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &6&l%{detect_gold_amount_mined_in_x_sec}% &7per &6Oro"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {goldauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- ORO IN ARDESIA PROFONDA (AUTOMATICO) ---#
    if {deepslategoldauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_deepslate_gold_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &6&l%{detect_deepslate_gold_amount_mined_in_x_sec}% &7per &6Oro in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslategoldauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
#--- SMERALDO (AUTOMATICO) ---# 
    if {emeraldauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_emerald_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &a&l%{detect_emerald_amount_mined_in_x_sec}% &7per &aSmeraldo"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {emeraldauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- SMERALDO IN ARDESIA PROFONDA (AUTOMATICO) ---#
    if {deepslateemeraldauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_deepslate_emerald_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &a&l%{detect_deepslate_emerald_amount_mined_in_x_sec}% &7per &aSmeraldo in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslateemeraldauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- DIAMANTE (AUTOMATICO) ---#
    if {diamondauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_diamond_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &b&l%{detect_diamond_amount_mined_in_x_sec}% &7per &bDiamante"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {diamondauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- DIAMANTE IN ARDESIA PROFONDA (AUTOMATICO) ---#
    if {deepslatediamondauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_deepslate_diamond_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &b&l%{detect_deepslate_diamond_amount_mined_in_x_sec}% &7per &bDiamante in ardesia profonda"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {deepslatediamondauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
    
#--- DETRITI ANTICHI (AUTOMATICO ---#
    if {debrisauto.%player%} is true:
        cancel event
        set {_timer} to message parsed as number
        set {detect_debris_amount_mined_in_x_sec} to {_timer}
        send "&8[&4&lAXR&8] &7Quantità impostata a &f&l%{detect_debris_amount_mined_in_x_sec}% &7per &fDetriti antichi"
        play sound "{@enabled_sound}" with volume 1 at player   
        wait 5 ticks
        delete {debrisauto.%player%}
        wait 1 ticks
        execute player command "/axr axrasettings"
        
            #--------------------------------------------#
            #               GUI: PRINCIPALE              #
            #--------------------------------------------#
command /axr [<text>] [<text>] [<offline player>]:
    executable by: player, console
    trigger:
        if arg-1 is not set:
            if player doesn't have permission "axr.admin":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 and pitch 0 at player
                stop
            if player has permission "axr.admin":
                wait 5 ticks
                open chest with 3 row named "&8[&4&lAnti-XRay&8]" to player
                format slot 0 of player with gray stained glass pane named " " to be unstealable
                format slot 1 of player with gray stained glass pane named " " to be unstealable
                format slot 2 of player with gray stained glass pane named " " to be unstealable
                format slot 3 of player with gray stained glass pane named " " to be unstealable
                format slot 4 of player with gray stained glass pane named " " to be unstealable
                format slot 5 of player with gray stained glass pane named " " to be unstealable
                format slot 6 of player with gray stained glass pane named " " to be unstealable
                format slot 7 of player with gray stained glass pane named " " to be unstealable
                format slot 8 of player with gray stained glass pane named " " to be unstealable
                format slot 9 of player with gray stained glass pane named " " to be unstealable
                format slot 10 of player with empty map named "&e&lAvvisi Offline&7" to close then run [execute player command "/ofa"]
                format slot 11 of player with gray stained glass pane named " " to be unstealable
                format slot 12 of player with emerald ore named "&a&lConta Minerali" to close then run [execute player command "/axr axrcounter"]
                format slot 13 of player with gray stained glass pane named " " to be unstealable
                format slot 14 of player with diamond ore named "&c&lImpostazioni Avvisi" to close then run [execute player command "/axr axrasettings"]
                format slot 15 of player with gray stained glass pane named " " to be unstealable
                format slot 16 of player with compass named "&b&lMondi" with lore "&7Scegli quali &2mondi &7vuoi &aabilitare" to close then run [execute player command "/axr world"]
                format slot 17 of player with gray stained glass pane named " " to be unstealable
                format slot 18 of player with gray stained glass pane named " " to be unstealable
                format slot 19 of player with gray stained glass pane named " " to be unstealable
                format slot 20 of player with gray stained glass pane named " " to be unstealable
                format slot 21 of player with gray stained glass pane named " " to be unstealable
                format slot 22 of player with gray stained glass pane named " " to be unstealable
                format slot 23 of player with gray stained glass pane named " " to be unstealable
                format slot 24 of player with gray stained glass pane named " " to be unstealable
                format slot 25 of player with gray stained glass pane named " " to be unstealable
                format slot 26 of player with gray stained glass pane named " " to be unstealable
            #--------------------------------------------#
            #             GUI: CONTA MINERALI            #
            #--------------------------------------------#
        if arg-1 is "addworld":
            if arg-2 is not set:
                send " "
                send "&eLista dei mondi&7: &2%{all::*}%"
                send "&7Utilizza &6/axraddworld &7(&amondo&7)"
                send " "
            if arg-2 is set:
                set {enabled.world} to arg-1 parsed as world
                if {eworld::*} contains {enabled.world}:
                    send "&cERRORE&6>> &a%{enabled.world}% &cè già stato aggiunto!"
                if {eworld::*} does not contain {enabled.world}:
                    send "&8[&4&lAXR&8] &7Hai &aabilitato &7(&a&l%{enabled.world}%&7)"
                    add {enabled.world} to {eworld::*}
                    play sound "{@enabled_sound}" with volume 1 at player
        if arg-1 is "removeworld":
            if arg-1 is not set:
                send " "
                send "&aLista dei mondi abilitati&7: &e%{eworld::*}%"
                send "&7Utilizza &6/axrremoveworld &7(&cmondo&7)"
                send " "
            if arg-1 is set:
                set {remove.world} to arg-1 parsed as world
                if {eworld::*} does not contain {remove.world}:
                    send "&cERRORE&6>> &a%{remove.world}% &cnon è abilitato!"
                if {eworld::*} contains {remove.world}:
                    send "&8[&4&lAXR&8] &7Hai &crimosso &7(&c&l%{remove.world}%&7)"
                    remove {remove.world} from {eworld::*}
                    play sound "{@enabled_sound}" with volume 1 at player
                    stop
        if arg-1 is "axrcounter":
            if player doesn't have permission "axr.admin":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.admin":
                wait 5 ticks
                open chest with 4 rows named "&8[&2&lConta Minerali&8]" to player
                format slot 0 of player with gray stained glass pane named " " to be unstealable
                format slot 1 of player with gray stained glass pane named " " to be unstealable
                format slot 2 of player with gray stained glass pane named " " to be unstealable
                format slot 3 of player with gray stained glass pane named " " to be unstealable
                format slot 4 of player with gray stained glass pane named " " to be unstealable
                format slot 5 of player with gray stained glass pane named " " to be unstealable
                format slot 6 of player with gray stained glass pane named " " to be unstealable
                format slot 7 of player with gray stained glass pane named " " to be unstealable
                format slot 8 of player with gray stained glass pane named " " to be unstealable
                format slot 9 of player with gray stained glass pane named " " to be unstealable
                format slot 10 of player with gray stained glass pane named " " to be unstealable
                format slot 11 of player with emerald ore named "&aConta minerali&f: %{counter.name}%" to close then run [execute player command "/axr orecount"]
                format slot 12 of player with gray stained glass pane named " " to be unstealable
                format slot 13 of player with gray stained glass pane named " " to be unstealable
                format slot 14 of player with gray stained glass pane named " " to be unstealable
                format slot 15 of player with compass named "&5Minerali scavati" with lore "&eControlla quanti minerali" and "&eha scavato un giocatore" to close then run [execute player command "/manage lookup"]
                format slot 16 of player with gray stained glass pane named " " to be unstealable
                format slot 17 of player with gray stained glass pane named " " to be unstealable
                format slot 18 of player with gray stained glass pane named " " to be unstealable
                format slot 19 of player with gray stained glass pane named " " to be unstealable
                format slot 20 of player with gray stained glass pane named " " to be unstealable
                format slot 21 of player with gray stained glass pane named " " to be unstealable
                format slot 22 of player with gray stained glass pane named " " to be unstealable
                format slot 23 of player with gray stained glass pane named " " to be unstealable
                format slot 24 of player with gray stained glass pane named " " to be unstealable
                format slot 25 of player with gray stained glass pane named " " to be unstealable
                format slot 26 of player with gray stained glass pane named " " to be unstealable
                format slot 27 of player with gray stained glass pane named " " to be unstealable
                format slot 28 of player with gray stained glass pane named " " to be unstealable
                format slot 29 of player with gray stained glass pane named " " to be unstealable
                format slot 30 of player with gray stained glass pane named " " to be unstealable
                format slot 31 of player with arrow named "&fTorna a &8[&4&lAnti-XRay&8]" to close then run [execute player command "/axr"]
                format slot 32 of player with gray stained glass pane named " " to be unstealable
                format slot 33 of player with gray stained glass pane named " " to be unstealable
                format slot 34 of player with gray stained glass pane named " " to be unstealable
                format slot 35 of player with gray stained glass pane named " " to be unstealable
            #--------------------------------------------#
            #                 GUI: MONDI                 #
            #--------------------------------------------#
        if arg-1 is "world":
            if player doesn't have permission "axr.admin":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.admin":
                wait 5 ticks
                loop all worlds:
                    set {all::*} to worlds
                open chest with 4 rows named "&8[&9&lMondi&8]" to player
                set {_skull} to "_Xedo_" parsed as offline player
                set {_dem} to "Demon" parsed as offline player
                set {_gren} to "glew" parsed as offline player
                format slot 0 of player with gray stained glass pane named " " to be unstealable
                format slot 1 of player with gray stained glass pane named " " to be unstealable
                format slot 2 of player with gray stained glass pane named " " to be unstealable
                format slot 3 of player with gray stained glass pane named " " to be unstealable
                format slot 4 of player with gray stained glass pane named " " to be unstealable
                format slot 5 of player with gray stained glass pane named " " to be unstealable
                format slot 6 of player with gray stained glass pane named " " to be unstealable
                format slot 7 of player with gray stained glass pane named " " to be unstealable
                format slot 8 of player with gray stained glass pane named " " to be unstealable
                format slot 9 of player with gray stained glass pane named " " to be unstealable
                format slot 10 of player with gray stained glass pane named " " to be unstealable
                format slot 11 of player with skull of {_gren} named "&8(&a&l+&8)" with lore "&aAggiungi &7un mondo" to close then run [execute player command "/manage world"]
                format slot 12 of player with skull of {_dem} named "&8(&c&l-&8)" with lore "&cRimuovi &7un mondo" to close then run [execute player command "/manage rworld"]
                format slot 13 of player with gray stained glass pane named " " to be unstealable
                format slot 14 of player with gray stained glass pane named " " to be unstealable
                format slot 15 of player with skull of {_skull} named "&eMondi disponibili&7:" with lore "&7%{all::*}%" and " " and "&eMondi aggiunti&7:" and "&2%{eworld::*}%" to be unstealable
                format slot 16 of player with gray stained glass pane named " " to be unstealable
                format slot 17 of player with gray stained glass pane named " " to be unstealable
                format slot 18 of player with gray stained glass pane named " " to be unstealable
                format slot 19 of player with gray stained glass pane named " " to be unstealable
                format slot 20 of player with gray stained glass pane named " " to be unstealable
                format slot 21 of player with gray stained glass pane named " " to be unstealable
                format slot 22 of player with gray stained glass pane named " " to be unstealable
                format slot 23 of player with gray stained glass pane named " " to be unstealable
                format slot 24 of player with gray stained glass pane named " " to be unstealable
                format slot 25 of player with gray stained glass pane named " " to be unstealable
                format slot 26 of player with gray stained glass pane named " " to be unstealable
                format slot 27 of player with gray stained glass pane named " " to be unstealable
                format slot 28 of player with gray stained glass pane named " " to be unstealable
                format slot 29 of player with gray stained glass pane named " " to be unstealable
                format slot 30 of player with gray stained glass pane named " " to be unstealable
                format slot 31 of player with arrow named "&fTorna a &8[&4&lAnti-XRay&8]" to close then run [execute player command "/axr"]
                format slot 32 of player with gray stained glass pane named " " to be unstealable
                format slot 33 of player with gray stained glass pane named " " to be unstealable
                format slot 34 of player with gray stained glass pane named " " to be unstealable
                format slot 35 of player with gray stained glass pane named " " to be unstealable
            #--------------------------------------------#
            #          GUI: IMPOSTAZIONI AVVISI          #
            #--------------------------------------------#
        if arg-1 is "axrasettings":
            if player doesn't have permission "axr.admin":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.admin":
                wait 5 ticks
                open chest with 6 rows named "&8[&4&lImpostazioni Avvisi&8]" to player
                format slot 0 of player with gray stained glass pane named " " to be unstealable
                format slot 1 of player with gray stained glass pane named " " to be unstealable
                format slot 2 of player with gray stained glass pane named " " to be unstealable
                format slot 3 of player with gray stained glass pane named " " to be unstealable
                format slot 4 of player with clock named "&aTimer&f: &c%{timer}% secondi" with lore "&7Imposta un &ctimer&7 per controllare" and "&7la quantità di minerali scavati" and "&7entro &c%{timer}%&7 secondi!" and " " and "&7Clicca per &cmodificare&7." to close then run [execute player command "/axr timer"]
                format slot 5 of player with gray stained glass pane named " " to be unstealable
                format slot 6 of player with gray stained glass pane named " " to be unstealable
                format slot 7 of player with gray stained glass pane named " " to be unstealable
                format slot 8 of player with gray stained glass pane named " " to be unstealable
                format slot 9 of player with a eye of ender named "&eAvvisi minerali&f: %{orealerts.name}%" with lore "&7Avvisi per i &eminerali &7scavati in &c&n%{timer}%&7 secondi!" to close then run [execute player command "/axr alerts all"]
                format slot 10 of player with a iron ore named "&fFerro: %{airon.name}%" with lore "&fQuantità: &b%{iron_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage iron"]
                format slot 11 of player with a copper ore named "&dRame&f: %{acopper.name}%" with lore "&fQuantità: &b%{copper_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage copper"]
                format slot 12 of player with a gold ore named "&6Oro&f: %{agold.name}%" with lore "&6Quantità: &b%{gold_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage gold"]
                format slot 13 of player with a redstone ore named "&cRedstone&f: %{aredstone.name}%" with lore "&cQuantità: &b%{redstone_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage redstone"]
                format slot 14 of player with a lapis lazuli ore named "&1Lapislazzuli&f: %{alapis.name}%" with lore "&1Quantità: &b%{lapis_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage lapis"]
                format slot 15 of player with a emerald ore named "&aSmeraldo&f: %{aemerald.name}%" with lore "&aQuantità: &b%{emerald_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage emerald"]
                format slot 16 of player with a diamond ore named "&bDiamante&f: %{adiamond.name}%" with lore "&bQuantità: &b%{diamond_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage diamond"]
                format slot 17 of player with a Ancient Debris named "&fDetriti Antichi&f: %{anether.name}%" with lore "&fQuantità: &b%{nether_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage nether"]
                format slot 18 of player with gray stained glass pane named " " to be unstealable
                format slot 19 of player with deepslate iron ore named "&fFerro in ardesia profonda: %{adiron.name}%" with lore "&fQuantità: &b%{deepslate_iron_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage deepiron"]
                format slot 20 of player with a deepslate copper ore named "&dRame in ardesia profonda&f: %{adcopper.name}%" with lore "&fQuantità: &b%{deepslate_copper_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage deepcopper"]
                format slot 21 of player with a deepslate gold ore named "&6Oro in ardesia profonda&f: %{adgold.name}%" with lore "&6Quantità: &b%{deepslate_gold_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage deepgold"]
                format slot 22 of player with a deepslate redstone ore named "&cRedstone in ardesia profonda&f: %{adredstone.name}%" with lore "&cQuantità: &b%{deepslate_redstone_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage deepredstone"]
                format slot 23 of player with a deepslate lapis lazuli ore named "&1Lapislazzuli in ardesia profonda&f: %{adlapis.name}%" with lore "&1Quantità: &b%{deepslate_lapis_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage deeplapis"]
                format slot 24 of player with a deepslate emerald ore named "&aSmeraldo in ardesia profonda&f: %{ademerald.name}%" with lore "&aQuantità: &b%{deepslate_emerald_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage deepemerald"]
                format slot 25 of player with a deepslate diamond ore named "&bDiamante in ardesia profonda&f: %{addiamond.name}%" with lore "&bQuantità: &b%{deepslate_diamond_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage deepdiamond"]
                format slot 26 of player with gray stained glass pane named " " to be unstealable
                format slot 27 of player with iron bars named "&cRiconoscimento automatico&f: %{autokick.name}%" with lore "&7Gli &eavvisi minerali&7 devono essere &aabilitati" and "&7per far sì che questa funzione funzioni." and " " and "&cPunisci &7per minerali scavati in &c&n%{timer}%&7 secondi!" and " " and "&7Cambia &cpunizioni &7in &aaxr.sk" to close then run [execute player command "/alerts auto"]
                format slot 28 of player with gray stained glass pane named " " to be unstealable
                format slot 29 of player with a iron ore named "&fFerro: %{autoiron.name}%" with lore "&fQuantità: &b%{detect_iron_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autoiron"]
                format slot 30 of player with a copper ore named "&dRame&f: %{autocopper.name}%" with lore "&fQuantità: &b%{detect_copper_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autocopper"]
                format slot 31 of player with a gold ore named "&6Oro&f: %{autogold.name}%" with lore "&6Quantità: &b%{detect_gold_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autogold"]
                format slot 32 of player with a emerald ore named "&aSmeraldo&f: %{autoemerald.name}%" with lore "&aQuantità: &b%{detect_emerald_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autoemerald"]
                format slot 33 of player with a diamond ore named "&bDiamante&f: %{autodiamond.name}%" with lore "&bQuantità: &b%{detect_diamond_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autodiamond"]
                format slot 34 of player with Ancient Debris named "&fDetriti Antichi&f: %{autodebris.name}%" with lore "&fQuantità: &b%{detect_debris_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autodebris"]
                format slot 35 of player with gray stained glass pane named " " to be unstealable
                format slot 36 of player with nether star named "&6Avvisi in console&f: %{con.name}%" with lore "&7Manda gli avvisi minerali" and "&7alla &6&nconsole&7 del server" to close then run [execute player command "/alerts console"]
                format slot 37 of player with gray stained glass pane named " " to be unstealable
                format slot 38 of player with a deepslate iron ore named "&fFerro in ardesia profonda: %{autodeepslateiron.name}%" with lore "&fQuantità: &b%{detect_deepslate_iron_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autodeepiron"]
                format slot 39 of player with a deepslate copper ore named "&dRame in ardesia profonda&f: %{autodeepslatecopper.name}%" with lore "&fQuantità: &b%{detect_deepslate_copper_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autodeepcopper"]
                format slot 40 of player with a deepslate gold ore named "&6Oro in ardesia profonda&f: %{autodeepslategold.name}%" with lore "&6Quantità: &b%{detect_deepslate_gold_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autodeepgold"]
                format slot 41 of player with a deepslate emerald ore named "&aSmeraldo in ardesia profonda&f: %{autodeepslateemerald.name}%" with lore "&aQuantità: &b%{detect_deepslate_emerald_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autodeepemerald"]
                format slot 42 of player with a deepslate diamond ore named "&bDiamante in ardesia profonda&f: %{autodeepslatediamond.name}%" with lore "&bQuantità: &b%{detect_deepslate_diamond_amount_mined_in_x_sec}%" and "&7Timer&f: &c&n%{timer}%&7 secondi!" and " " and "&7Clicca per &a&nmodificare" to close then run [execute player command "/manage autodeepdiamond"]
                format slot 43 of player with gray stained glass pane named " " to be unstealable
                format slot 44 of player with gray stained glass pane named " " to be unstealable
                format slot 45 of player with gray stained glass pane named " " to be unstealable
                format slot 46 of player with gray stained glass pane named " " to be unstealable
                format slot 47 of player with gray stained glass pane named " " to be unstealable
                format slot 48 of player with gray stained glass pane named " " to be unstealable
                format slot 49 of player with arrow named "&fTorna a &8[&4&lAnti-XRay&8]" to close then run [execute player command "/axr"]
                format slot 50 of player with gray stained glass pane named " " to be unstealable
                format slot 51 of player with gray stained glass pane named " " to be unstealable
                format slot 52 of player with gray stained glass pane named " " to be unstealable
                format slot 53 of player with gray stained glass pane named " " to be unstealable
                
        if arg-1 is "alerts" or "a":
            if player doesn't have permission "axr.admin":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.admin":
                if arg-2 is not set:
                    send "{@prefix} &eInserisci &7(&eall&7)"
                    send " "
                    send "{@prefix} &eUtilizza /axr alerts &7(&eall&7)"
                    send " "
                if arg-2 is "all":
                    if {axr.alert} is not set:
                        set {axr.alert} to true
                        send "&6&l>> &eAvvisi Minerali&f: {@truemsg}"
                        set {airon.name} to "{@truemsg}"
                        set {adiron.name} to "{@truemsg}"
                        set {acopper.name} to "{@truemsg}"
                        set {adcopper.name} to "{@truemsg}"
                        set {agold.name} to "{@truemsg}"
                        set {adgold.name} to "{@truemsg}"
                        set {aemerald.name} to "{@truemsg}"
                        set {ademerald.name} to "{@truemsg}"
                        set {adiamond.name} to "{@truemsg}"
                        set {addiamond.name} to "{@truemsg}"
                        set {orealerts.name} to "{@truemsg}"
                        set {aredstone.name} to "{@truemsg}"
                        set {adredstone.name} to "{@truemsg}"
                        set {alapis.name} to "{@truemsg}"
                        set {adlapis.name} to "{@truemsg}"
                        set {anether.name} to "{@truemsg}"
                        play sound "{@enabled_sound}" with volume 1 at player
                        wait 2 ticks
                        execute player command "/axr axrasettings"
                        stop
                    else:
                        delete {axr.alert} 
                        send "&6&l>> &eAvvisi Minerali&f: {@falsemsg}"
                        set {orealerts.name} to "{@falsemsg}"
                        set {agold.name} to "{@falsemsg}"
                        set {adgold.name} to "{@falsemsg}"
                        set {acopper.name} to "{@falsemsg}"
                        set {adcopper.name} to "{@falsemsg}"
                        set {aemerald.name} to "{@falsemsg}"
                        set {ademerald.name} to "{@falsemsg}"
                        set {adiamond.name} to "{@falsemsg}"
                        set {addiamond.name} to "{@falsemsg}"
                        set {autokick.name} to "{@falsemsg}"
                        set {airon.name} to "{@falsemsg}"
                        set {adiron.name} to "{@falsemsg}"
                        set {aredstone.name} to "{@falsemsg}"
                        set {adredstone.name} to "{@falsemsg}"
                        set {offorealerts.name} to "{@falsemsg}"
                        set {alapis.name} to "{@falsemsg}"
                        set {adlapis.name} to "{@falsemsg}"
                        set {anether.name} to "{@falsemsg}"
                        play sound "{@disabled_sound}" with volume 1 at player
                        delete {autokick}
                        wait 2 tick
                        execute player command "/axr axrasettings"
                        stop
        if arg-1 is "timer":
            if player doesn't have permission "axr.admin":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.admin":
                if arg-2 is not set:
                    if {axr.alert} is false:
                        send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ndisabilitati&7!"
                        play sound "{@error_sound}" with volume 1 at player
                        stop
                    if {axr.alert} is not set:
                        send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ndisabilitati&7!"
                        play sound "{@error_sound}" with volume 1 at player
                        stop
                    if {axr.alert} is true:
                        send " "
                        send "&7Il timer è utilizzato per gli &eAvvisi Minerali &7e &cRiconoscimento automatico"
                        send " "
                        wait 2 ticks
                        send "&8[&4&lAXR&8] &eDigita la durata del timer in chat!"
                        set {timeset.%player%} to true
                        stop
        if arg-1 is "orecount" or "oc":
            if arg-2 is not set:
                if player doesn't have permission "axr.admin":
                    send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                    play sound "{@error_sound}" with volume 1 at player
                    stop
                if player has permission "axr.admin":
                    if {axr.count} is not set:
                        send "&6&l>> &5Avvisi Minerali&f: {@truemsg}"
                        set {counter.name} to "{@truemsg}"
                        play sound "{@enabled_sound}" with volume 1 at player
                        set {axr.count} to true
                        execute player command "/axr axrcounter"
                        stop
                    if {axr.count} is true:
                        set {axr.count} to false
                        send "&6&l>> &5Avvisi Minerali&f: {@falsemsg}"
                        play sound "{@disabled_sound}" with volume 1 at player
                        set {counter.name} to "{@falsemsg}"
                        wait 1 tick
                        execute player command "/axr axrcounter"
                        stop
                    if {axr.count} is false:
                        set {axr.count} to true
                        send "&6&l>> &5Avvisi Minerali&f: {@truemsg}"
                        play sound "{@enabled_sound}" with volume 1 at player
                        set {counter.name} to "{@truemsg}"
                        wait 1 tick
                        execute player command "/axr axrcounter"
                        stop
            #--------------------------------------------#
            #         MINERALI SCAVATI GIOCATORE         #
            #--------------------------------------------#
            if arg-2 is "ores":
                if player doesn't have permission "axr.admin" or "axr.orecount":
                    send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                    play sound "{@error_sound}" with volume 1 at player
                    stop
                if player has permission "axr.orecount" or "axr.admin":
                    if arg-3 is not set:
                        send "{@prefix} &eUtilizza &6/axr orecount ores [giocatore]"
                        play sound "{@error_sound}" with volume 1 at player
                        stop
                    if arg-3 is set:
                        if {axr.count} is false:
                            send "{@prefix} &6Hai &cdisabilitato &6il contatore di minerali"
                            play sound "{@error_sound}" with volume 1 at player
                            stop
                        if {axr.count} is true:
                            open chest with 4 rows named "Minerali scavati di &c%arg-3%" to player
                            format slot 0 of player with gray stained glass pane named " " to be unstealable
                            format slot 1 of player with gray stained glass pane named " " to be unstealable
                            format slot 2 of player with arg-3's skull named "&c&l%arg-3%" with lore "&e&lMinerali totali" with lore "&fFerro: &b%{iore.%arg-3%}%" and "&fFerro in ardesia profonda: &b%{diore.%arg-3%}%" and "&dRame&f: &b%{core.%arg-3%}%" and "&dRame in ardesia profonda&f: &b%{dcore.%arg-3%}%" and "&6Oro&f: &b%{gore.%arg-3%}%" and "&6Oro in ardesia profonda&f: &b%{dgore.%arg-3%}%" and "&cRedstone&f: &b%{rore.%arg-3%}%" and "&cRedstone in ardesia profonda&f: &b%{drore.%arg-3%}%" and "&1Lapislazzuli&f: &b%{lore.%arg-3%}%" and "&1Lapislazzuli in ardesia profonda&f: &b%{lore.%arg-3%}%" and "&aSmeraldo&f: &b%{eore.%arg-3%}%" and "&aSmeraldo in ardesia profonda&f: &b%{deore.%arg-3%}%" and "&bDiamante&f: &b%{dore.%arg-3%}%" and "&bDiamante in ardesia profonda&f: &b%{ddore.%arg-3%}%" and "&fDetriti Antichi: &b%{nore.%arg-3%}%" to be unstealable
                            format slot 3 of player with gray stained glass pane named " " to be unstealable
                            format slot 4 of player with gray stained glass pane named " " to be unstealable
                            format slot 5 of player with gray stained glass pane named " " to be unstealable
                            format slot 6 of player with paper named "&e&lAzzera contatore" with lore "&4&lATTENZIONE!" and "&7Quest'operazione &c&lazzererà &7il" and "&7contatore dei minerali scavati!" to close then run [execute player command "/axr orecount clear %arg-3%"]
                            format slot 7 of player with gray stained glass pane named " " to be unstealable
                            format slot 8 of player with gray stained glass pane named " " to be unstealable
                            format slot 9 of player with gray stained glass pane named " " to be unstealable
                            format slot 10 of player with iron ore named "&fFerro: &b%{iore.%arg-3%}%" to be unstealable
                            format slot 11 of player with copper ore named "&dRame&f: &b%{core.%arg-3%}%" to be unstealable
                            format slot 12 of player with a gold ore named "&6Oro&f: &b%{gore.%arg-3%}%" to be unstealable
                            format slot 13 of player with redstone ore named "&cRedstone&f: &b%{rore.%arg-3%}%" to be unstealable
                            format slot 14 of player with a lapis lazuli ore named "&1Lapislazzuli&f: &b%{lore.%arg-3%}%" to be unstealable
                            format slot 15 of player with a emerald ore named "&aSmeraldo&f: &b%{eore.%arg-3%}%" to be unstealable
                            format slot 16 of player with a diamond ore named "&bDiamante&f: &b%{dore.%arg-3%}%" to be unstealable
                            format slot 17 of player with a ancient debris named "&fDetriti Antichi: &b%{nore.%arg-3%}%" to be unstealable
                            format slot 18 of player with gray stained glass pane named " " to be unstealable
                            format slot 19 of player with deepslate iron ore named "&fFerro in ardesia profonda: &b%{diore.%arg-3%}%" to be unstealable
                            format slot 20 of player with deepslate copper ore named "&dRame in ardesia profonda&f: &b%{dcore.%arg-3%}%" to be unstealable
                            format slot 21 of player with deepslate gold ore named "&6Oro in ardesia profonda&f: &b%{dgore.%arg-3%}%" to be unstealable
                            format slot 22 of player with deepslate redstone ore named "&cRedstone in ardesia profonda&f: &b%{drore.%arg-3%}%" to be unstealable
                            format slot 23 of player with deepslate lapis lazuli ore named "&1Lapislazzuli in ardesia profonda&f: &b%{dlore.%arg-3%}%" to be unstealable
                            format slot 24 of player with deepslate emerald ore named "&aSmeraldo in ardesia profonda&f: &b%{deore.%arg-3%}%" to be unstealable
                            format slot 25 of player with deepslate diamond ore named "&bDiamante in ardesia profonda&f: &b%{ddore.%arg-3%}%" to be unstealable
                            format slot 26 of player with gray stained glass pane named " " to be unstealable
                            format slot 27 of player with gray stained glass pane named " " to be unstealable
                            format slot 28 of player with gray stained glass pane named " " to be unstealable
                            format slot 29 of player with gray stained glass pane named " " to be unstealable
                            format slot 30 of player with gray stained glass pane named " " to be unstealable
                            format slot 31 of player with arrow named "&fTorna a &8[&4&lAnti-XRay&8]" to close then run [execute player command "/axr"]
                            format slot 32 of player with gray stained glass pane named " " to be unstealable
                            format slot 33 of player with gray stained glass pane named " " to be unstealable
                            format slot 34 of player with gray stained glass pane named " " to be unstealable
                            format slot 35 of player with gray stained glass pane named " " to be unstealable
                            
            if arg-2 is "clear":
                if player doesn't have permission "axr.admin":
                    send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                    play sound "{@error_sound}" with volume 1 at player
                    stop
                if player has permission "axr.admin":                   
                    if arg-3 is not set:
                        send "{@prefix} &eUtilizza &6/axr orecount clear [giocatore]"
                        play sound "{@error_sound}" with volume 1 at player
                        stop
                    if arg-3 is set:
                        if {axr.count} is false:
                            send "{@prefix} &6Hai &cdisabilitato &6il contatore di minerali!"
                            play sound "{@error_sound}" with volume 1 at player
                            stop
                        if {axr.count} is true:
                            send "&7Il contatore di minerali di &6&l%arg-3% &7è stato &cazzerato&7!"
                            set {iore.%arg-3%} to 0
                            set {diore.%arg-3%} to 0
                            set {core.%arg-3%} to 0
                            set {dcore.%arg-3%} to 0
                            set {dore.%arg-3%} to 0
                            set {ddore.%arg-3%} to 0
                            set {eore.%arg-3%} to 0
                            set {deore.%arg-3%} to 0
                            set {gore.%arg-3%} to 0
                            set {dgore.%arg-3%} to 0
                            set {rore.%arg-3%} to 0
                            set {drore.%arg-3%} to 0
                            set {lore.%arg-3%} to 0
                            set {dlore.%arg-3%} to 0
                            set {nore.%arg-3%} to 0
        if arg-1 is "help":
            if player doesn't have permission "axr.orecount":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.orecount":
                send "&b========= {@prefix} &aLISTA COMANDI &b========="
                send "{@prefix} &e/axr &7- &3Apri la GUI"
                send "{@prefix} &e/offlineaxr &7- &3Mostra i dati offline"
                send "{@prefix} &e/axr alerts &7- &aAttiva &3o &cdisattiva &3gli avvisi dell'Anti-XRay"
                send "{@prefix} &e/axr orecount &7- &aAttiva &3o &cdisattiva &3il contatore di minerali"
                send "{@prefix} &e/axr orecount ores [giocatore] &7- &3Controlla la quantità di minerali scavati dal giocatore"
                send "{@prefix} &e/axr orecount clear [giocatore] &7- &3Azzera il contatore di minerali"
                send "{@prefix} &e/axr reload &7- &3Ricarica il config"
                send "{@prefix} &e/axr help &7- &3Mostra questa lista"
                stop
        if arg-1 is "reload" or "rl":
            if player doesn't have permission "axr.admin":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.admin":               
                send "&7Sto ricaricando l'&aAnti-XRay&7..."
                wait 1 second
                make console execute command "/skript reload %script%"
                wait 1 second
                send "&aAnti-XRay &7ricaricato e pronto!"
                send "{@prefix} &7È stata ricaricata la versione &a{@Versione} &7per Minecraft &a{@Versione_MC}."
                stop
        if arg-1 is "alertclick":
            if player doesn't have permission "axr.alerts":
                send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if player has permission "axr.alerts":
                execute player command "{@alert_command2}"
                execute player command "{@alert_command3}"
                stop
                
            #--------------------------------------------#
            #             IMPOSTAZIONI VARIE             #
            #--------------------------------------------#
command /manage [<text>]:
    permission: axr.admin
    permission message: &8[&4&lAXR&8] &c&lACCESSO NEGATO!
    trigger:
        wait 2 ticks
        if arg-1 is "iron":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per il &fFerro &7in &4%{timer}% &7secondi!"
                send " "
                set {ironset.%player%} to true              
                stop
        if arg-1 is "deepiron":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per il &fFerro in ardesia profonda &7in &4%{timer}% &7secondi!"
                send " "
                set {deepslateironset.%player%} to true             
                stop
        if arg-1 is "world":
            send " "
            send "&8[&4&lAXR&8] &2Scrivi in chat &7in che mondo vuoi &aabilitare &7l'Anti-XRay"
            send "&8[&4&lAXR&8] &7Mondi disponibili: &e%{all::*}%"
            send " "
            set {worldset.%player%} to true         
            stop
        if arg-1 is "rworld":
            send " "
            send "&8[&4&lAXR&8] &2Scrivi in chat &7in quale mondo vuoi &cdisabilitare &7l'Anti-XRay"
            send "&8[&4&lAXR&8] &aMondi disponibili: &e%{eworld::*}%"
            send " "
            set {rworldset.%player%} to true            
            stop
        if arg-1 is "copper":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per il &dRame &7in &c%{timer}% &7secondi!"
                send " "
                set {copperset.%player%} to true                
                stop
        if arg-1 is "deepcopper":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per il &dRame in ardesia profonda &7in &c%{timer}% &7secondi!"
                send " "
                set {deepslatecopperset.%player%} to true               
                stop
        if arg-1 is "gold":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per l'&6Oro &7in &c%{timer}% &7secondi!"
                send " "
                set {goldset.%player%} to true              
                stop
        if arg-1 is "deepgold":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per l'&6Oro in ardesia profonda &7in &c%{timer}% &7secondi!"
                send " "
                set {deepslategoldset.%player%} to true             
                stop
        if arg-1 is "lookup":
            if {axr.count} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &5Avvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.count} is false:
                send "&8[&4&lAXR&8] &c&lERRORE>> &c&lERRORE>> &7Il &5Contatore di minerali &7è &c&ndisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.count} is true:
                send " "
                send "&8[&4&lAXR&8] &7Inserisci il nome del giocatore che vuoi &econtrollare&7!"
                send " "
                set {lookup.%player%} to true               
                stop
        if arg-1 is "lapis":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per i &1Lapislazzuli &7in &c%{timer}% &7secondi!"
                send " "
                set {lapisset.%player%} to true             
                stop
        if arg-1 is "deeplapis":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per i &1Lapislazzuli in ardesia profonda &7in &c%{timer}% &7secondi!"
                send " "
                set {deepslatelapisset.%player%} to true                
                stop
        if arg-1 is "nether":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitate&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per i &fDetriti Antichi &7in &c%{timer}% &7secondi!"
                send " "
                set {netherset.%player%} to true                
                stop
        if arg-1 is "redstone":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per la &cRedstone &7in &c%{timer}% &7secondi!"
                send " "
                set {redset.%player%} to true               
                stop
        if arg-1 is "deepredstone":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per la &cRedstone in ardesia profonda &7in &c%{timer}% &7secondi!"
                send " "
                set {deepslateredset.%player%} to true              
                stop
        if arg-1 is "emerald":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitate&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per lo &aSmeraldo &7in &c%{timer}% &7secondi!"
                send " "
                set {emeraldset.%player%} to true               
                stop
        if arg-1 is "deepemerald":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitate&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per lo &aSmeraldo in ardesia profonda &7in &c%{timer}% &7secondi!"
                send " "
                set {deepslateemeraldset.%player%} to true              
                stop
        if arg-1 is "diamond":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per il &bDiamante &7in &c%{timer}% &7secondi!"
                send " "
                set {diamondset.%player%} to true               
                stop
        if arg-1 is "deepdiamond":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                send " "
                send "&8[&4&lAXR&8] &7Cambia la quantità degli avvisi per il &bDiamante in ardesia profonda &7in &c%{timer}% &7secondi!"
                send " "
                set {deepslatediamondset.%player%} to true              
                stop
        if arg-1 is "autoiron":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &cRiconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &fFerro &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {ironauto.%player%} to true             
                    stop
        if arg-1 is "autodeepiron":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &cRiconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &fFerro in ardesia profonda &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {deepslateironauto.%player%} to true                
                    stop
        if arg-1 is "autocopper":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &cRiconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &dRame &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {copperauto.%player%} to true               
                    stop
        if arg-1 is "autodeepcopper":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &cRiconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &dRame in ardesia profonda &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {deepslatecopperauto.%player%} to true              
                    stop
        if arg-1 is "autogold":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &criconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &6Oro &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {goldauto.%player%} to true             
                    stop
        if arg-1 is "autodeepgold":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &criconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &6Oro in ardesia profonda &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {deepslategoldauto.%player%} to true                
                    stop
        if arg-1 is "autoemerald":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &criconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &aSmeraldo &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {emeraldauto.%player%} to true              
                    stop
        if arg-1 is "autodeepemerald":
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &criconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &aSmeraldo in ardesia profonda &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {deepslateemeraldauto.%player%} to true             
                    stop
        if arg-1 is "autodiamond":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &criconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &bDiamante &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {diamondauto.%player%} to true              
                    stop
        if arg-1 is "autodeepdiamond":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &criconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &bDiamante in ardesia profonda &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {deepslatediamondauto.%player%} to true             
                    stop
        if arg-1 is "autodebris":
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {autokick} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Il &criconoscimento automatico &7è &c&ldisabilitato&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is true:
                    send " "
                    send "&8[&4&lAXR&8] &7Cambia la quantità di &fDetriti Antichi &7per il riconoscimento automatico in &c%{timer}% &7secondi!"
                    send " "
                    set {debrisauto.%player%} to true               
                    stop
                    
            #--------------------------------------------#
            #         CONTROLLO GIOCATORI OFFLINE        #
            #--------------------------------------------#
command /lookup [<offlineplayer>]:
    executable by: player
    trigger:
        if player doesn't have permission "axr.admin":
            send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
            play sound "{@error_sound}" with volume 1 at player
            stop
        if player has permission "axr.admin":
            if arg-1 is not set:
                send "&8[&4&lAXR&8] &cUtilizza &e/lookup &7(&egiocatore&7)"
            if arg-1 is set:
                if {axr.count} is not set:
                    send "&6&l>> &5Contatore Minerali&f: {@falsemsg}"
                    play sound "{@error_sound}" with volume 1 at player
                    stop
                if {axr.count} is false:
                    send "&6&l>> &5Contatore Minerali&f: {@falsemsg}"
                    play sound "{@error_sound}" with volume 1 at player
                    stop
                if {axr.count} is true:
                    execute player command "/axr orecount ores %arg-1%"
command /alerts [<text>]:
    permission: axr.admin
    permission message: &8[&4&lAXR&8] &c&lACCESSO NEGATO!
    trigger:
        wait 1 tick
        if arg-1 is "auto":
            if {axr.alert} is not set:
                send "&6&l>> &eAvvisi Minerali:&f &7prima &cdevi &aabilitarlo!"
                set {autokick.name} to "{@falsemsg}"
                set {autogold.name} to "{@falsemsg}"
                set {autodeepslategold.name} to "{@falsemsg}"
                set {autoiron.name} to "{@falsemsg}"
                set {autodeepslateiron.name} to "{@falsemsg}"
                set {autocopper.name} to "{@falsemsg}"
                set {autodeepslatecopper.name} to "{@falsemsg}"
                set {autodiamond.name} to "{@falsemsg}"
                set {autodeepslatediamond.name} to "{@falsemsg}"
                set {autoemerald.name} to "{@falsemsg}"
                set {autodeepslateemerald.name} to "{@falsemsg}"
                set {autodebris.name} to "{@falsemsg}"
                send "&6&l>> &cRiconoscimento automatico&f: {@falsemsg}"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {axr.alert} is true:
                if {autokick} is not set:
                    set {autokick} to true
                    set {autokick.name} to "{@truemsg}"
                    set {autogold.name} to "{@truemsg}"
                    set {autodeepslategold.name} to "{@truemsg}"
                    set {autoiron.name} to "{@truemsg}"
                    set {autodeepslateiron.name} to "{@truemsg}"
                    set {autocopper.name} to "{@truemsg}"
                    set {autodeepslatecopper.name} to "{@truemsg}"
                    set {autodiamond.name} to "{@truemsg}"
                    set {autodeepslatediamond.name} to "{@truemsg}"
                    set {autoemerald.name} to "{@truemsg}"
                    set {autodeepslateemerald.name} to "{@truemsg}"
                    set {autodebris.name} to "{@truemsg}"
                    send "&6&l>> &cRiconoscimento automatico&f: {@truemsg}"
                    execute player command "/axr axrasettings"
                    play sound "{@enabled_sound}" with volume 1 at player
                    stop
                else:
                    delete {autokick}
                    set {autokick.name} to "{@falsemsg}"
                    set {autokick.name} to "{@falsemsg}"
                    set {autogold.name} to "{@falsemsg}"
                    set {autodeepslategold.name} to "{@falsemsg}"
                    set {autoiron.name} to "{@falsemsg}"
                    set {autodeepslateiron.name} to "{@falsemsg}"
                    set {autocopper.name} to "{@falsemsg}"
                    set {autodeepslatecopper.name} to "{@falsemsg}"
                    set {autodiamond.name} to "{@falsemsg}"
                    set {autodeepslatediamond.name} to "{@falsemsg}"
                    set {autoemerald.name} to "{@falsemsg}"
                    set {autodeepslateemerald.name} to "{@falsemsg}"
                    set {autodebris.name} to "{@falsemsg}"
                    send "&6&l>> &cRiconoscimento automatico&f: {@falsemsg}"
                    execute player command "/axr axrasettings"
                    play sound "{@disabled_sound}" with volume 1 at player
                    stop
        if arg-1 is "console":
            if {con} is not set:
                set {con} to true
                set {con.name} to "{@truemsg}"
                send "&6&l>> &6Avvisi in console&f: {@truemsg}"
                execute player command "/axr axrasettings"
                play sound "{@enabled_sound}" with volume 1 at player
                stop
            else:
                delete {con}
                set {con.name} to "{@falsemsg}"
                send "&6&l>> &6Avvisi in console&f: {@falsemsg}"
                execute player command "/axr axrasettings"
                play sound "{@disabled_sound}" with volume 1 at player
                stop
        if arg-1 is "counter":
            execute player command "/axr orecount"
            wait 1 ticks
            execute player command "/axr"
            stop
                    
command /offlineaxr [<text>] [<offlineplayer>]:
    executable by: console, player
    aliases: /offaxr, /ofaxr, /ofa
    trigger:
        if sender doesn't have permission "axr.alerts":
            send "&8[&4&lAXR&8] &c&lACCESSO NEGATO!"
            play sound "{@error_sound}" with volume 1 at player
            stop
            #--------------------------------------------#
            #             GUI: AVVISI OFFLINE            #
            #--------------------------------------------#
        if arg-1 is not set:
            if {axr.alert} is true:
                wait 3 tick
                open chest with 4 rows named "&8[&6&lAvvisi Offline&8]" to player
                format slot 0 of player with gray stained glass pane named " " to be unstealable
                format slot 1 of player with gray stained glass pane named " " to be unstealable
                format slot 2 of player with gray stained glass pane named " " to be unstealable
                format slot 3 of player with gray stained glass pane named " " to be unstealable
                format slot 4 of player with gray stained glass pane named " " to be unstealable
                format slot 5 of player with gray stained glass pane named " " to be unstealable
                format slot 6 of player with gray stained glass pane named " " to be unstealable
                format slot 7 of player with gray stained glass pane named " " to be unstealable
                format slot 8 of player with gray stained glass pane named " " to be unstealable
                format slot 9 of player with gray stained glass pane named " " to be unstealable
                format slot 10 of player with empty map named "&6Avvisi Offline&f: %{offorealerts.name}%" with lore " " and "&7Gli &eAvvisi Minerali &7devono essere &aabilitati" and " " and "&eAvvisi Minerali&f: %{orealerts.name}%" to close then run [execute player command "/offlineaxr toggle"]
                format slot 11 of player with gray stained glass pane named " " to be unstealable
                format slot 12 of player with book named "&6Avvisi giocatori offline" with lore "&eGuarda la lista dei giocatori" and "&eper gli avvisi offline" to close then run [execute player command "/ofa list"]
                format slot 13 of player with gray stained glass pane named " " to be unstealable
                format slot 14 of player with compass named "&6Controlla giocatori offline" with lore "&eControlla i minerali scavati" and "&edei giocatori offline" to close then run [execute player command "/ofa offlinelookup"]
                format slot 15 of player with gray stained glass pane named " " to be unstealable
                format slot 16 of player with paper named "&e&lCancella dati offline" with lore "&4&lATTENZIONE!" and "&7Cancella &c&lTUTTI &7i dati offline" to close then run [execute player command "/offlineaxr clearall"]
                format slot 17 of player with gray stained glass pane named " " to be unstealable
                format slot 18 of player with gray stained glass pane named " " to be unstealable
                format slot 19 of player with gray stained glass pane named " " to be unstealable
                format slot 20 of player with gray stained glass pane named " " to be unstealable
                format slot 21 of player with gray stained glass pane named " " to be unstealable
                format slot 22 of player with gray stained glass pane named " " to be unstealable
                format slot 23 of player with gray stained glass pane named " " to be unstealable
                format slot 24 of player with gray stained glass pane named " " to be unstealable
                format slot 25 of player with gray stained glass pane named " " to be unstealable
                format slot 26 of player with gray stained glass pane named " " to be unstealable
                format slot 27 of player with gray stained glass pane named " " to be unstealable
                format slot 28 of player with gray stained glass pane named " " to be unstealable
                format slot 29 of player with gray stained glass pane named " " to be unstealable
                format slot 30 of player with gray stained glass pane named " " to be unstealable
                format slot 31 of player with arrow named "&fTorna a &8[&4&lAnti-XRay&8]" to close then run [execute player command "/axr"]
                format slot 32 of player with gray stained glass pane named " " to be unstealable
                format slot 33 of player with gray stained glass pane named " " to be unstealable
                format slot 34 of player with gray stained glass pane named " " to be unstealable
                format slot 35 of player with gray stained glass pane named " " to be unstealable
            if {axr.alert} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &eAvvisi Minerali &7sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
        if arg-1 is set:
            if arg-1 is "toggle":
                if {offorealerts} is not set:
                    set {offorealerts} to true
                    set {offorealerts.name} to "{@truemsg}"
                    send "&6&l>> &6Minerali offline&f: {@truemsg}"
                    play sound "{@enabled_sound}" with volume 1 at player
                    wait 2 ticks
                    execute player command "/ofa"
                    stop
                else:
                    delete {offorealerts}
                    set {offorealerts.name} to "{@falsemsg}"
                    send "&6&l>> &6Minerali Offline&f: {@falsemsg}"
                    wait 2 ticks
                    execute player command "/ofa"
                    play sound "{@disabled_sound}" with volume 1 at player
                    stop
            if {offorealerts} is false:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &6Avvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {offorealerts} is not set:
                send "&8[&4&lAXR&8] &c&lERRORE>> &7Gli &6Avvisi Minerali &7 sono &c&ldisabilitati&7!"
                play sound "{@error_sound}" with volume 1 at player
                stop
            if {offorealerts} is true:
                if sender has permission "axr.alerts":
                    if arg-1 is "teleport":
                        teleport player to {offloc::%arg-2%}
                if sender has permission "axr.alerts":
                    if arg-1 is not set:
                        send "&8[&4&lAXR&8] &e/offlineaxr &7[&elist&7/&eclear&7/&elookup&7] &7(&egiocatore&7)"
                    if arg-1 is "list":
                        send "&8[&4&lAXR&8] &cLista offline&7: &e%{offalerts::*}%"
                    if arg-1 is "clear":
                        if arg-2 is not set:
                            send " "
                            send "&8[&4&lAXR&8] &7Digita il nome del &egiocatore &7a cui vuoi cancellare tutti i dati"
                            send "&8[&4&lAXR&8] &e/ofa clear &7(&egiocatore&7)"
                            send " "
                        if arg-2 is set:
                            if {offalerts::*} does not contain arg-2:
                                send "&8[&4&lAXR&8] &cQuesto giocatore non è in lista!"         
                            if {offalerts::*} contains arg-2:
                                send " "
                                remove arg-2 from {offalerts::*}
                                send "&8[&4&lAXR&8] &7Hai cancellato i dati offline di &c%arg-2%&7!"
                                delete {offdore::%arg-2%} and {offeore::%arg-2%} and {offgore::%arg-2%} and {offiore::%arg-2%} and {offnore::%arg-2%} and {offloc::%arg-2%}
                                wait 1 tick
                                set {offdore::%arg-2%} and {offeore::%arg-2%} and {offgore::%arg-2%} and {offiore::%arg-2%} and {offnore::%arg-2%} to 0
    
                    if arg-1 is "clearall":
                        send "&8[&4&lAXR&8] &cTutti i dati offline sono stati cancellati!"
                        clear {offalerts::*}
                        play sound "block.beacon.deactivate" with volume 1 at player
                    if arg-1 is "offlinelookup":
                        send " "
                        send "&8[&4&lAXR&8] &7Inserisci il nome del giocatore che vuoi &econtrollare&7!"
                        send " "
                        set {offlinelookup.%player%} to true
            #--------------------------------------------#
            #    MINERALI SCAVATI GIOCATORE (OFFLINE)    #
            #--------------------------------------------#
                    if arg-1 is "lookup":
                        if arg-2 is not set:
                            send "&8[&4&lAXR&8] &e/offlineaxr &7[&elist&7/&eclear&7/&elookup] &7(&eplayer&7)"
                        if arg-2 is set:
                            wait 1 tick
                            if {offalerts::*} does not contain arg-2:
                                send "&8[&4&lAXR&8] &cQuel giocatore non è in lista!"
                                play sound "{@error_sound}" with volume 1 at player
                            if {offalerts::*} contains arg-2:
                                if {offdore::%arg-2%} or {offddore::%arg-2%} or {offcore::%arg-2%} or {offdcore::%arg-2%} or {offeore::%arg-2%} or {offdeore::%arg-2%} or {offgore::%arg-2%} or {offdgore::%arg-2%} or {offiore::%arg-2%} or {offdiore::%arg-2%} or {offnore::%arg-2%} is not set:
                                    set {offdore::%arg-2%} and {offddore::%arg-2%} and {offcore::%arg-2%} and {offdcore::%arg-2%} and {offeore::%arg-2%} and {offdeore::%arg-2%} and {offgore::%arg-2%} and {offdgore::%arg-2%} and {offiore::%arg-2%} and {offdiore::%arg-2%} and {offnore::%arg-2%} to 0
                                open chest with 4 rows named "&6Cont. Offline: &c&l%arg-2%" to player
                                format slot 0 of player with arg-2's skull named "&c&l%arg-2%" with lore "&eClicca &7per teletrasportarti" to close then run [execute player command "offlineaxr teleport %arg-2%"]
                                format slot 1 of player with gray stained glass pane named " " to be unstealable
                                format slot 2 of player with gray stained glass pane named " " to be unstealable
                                format slot 3 of player with gray stained glass pane named " " to be unstealable
                                format slot 4 of player with gray stained glass pane named " " to be unstealable
                                format slot 5 of player with gray stained glass pane named " " to be unstealable
                                format slot 6 of player with gray stained glass pane named " " to be unstealable
                                format slot 7 of player with gray stained glass pane named " " to be unstealable
                                format slot 8 of player with paper named "&e&lAzzera contatore di minerali" with lore "&4&lAttenzione! &7- &7Quest'azione &cazzererà &7il contatore di minerali" to close then run [execute player command "/offlineaxr clear %arg-2%"]
                                format slot 9 of player with gray stained glass pane named " " to be unstealable
                                format slot 10 of player with a iron ore named "&fFerro: &b%{offiore::%arg-2%}%" to be unstealable
                                format slot 11 of player with a copper ore named "&dRame: &b%{offcore::%arg-2%}%" to be unstealable
                                format slot 12 of player with a gold ore named "&6Oro: &b%{offgore::%arg-2%}%" to be unstealable
                                format slot 13 of player with a emerald ore named "&aSmeraldo: &b%{offeore::%arg-2%}%" to be unstealable
                                format slot 14 of player with a diamond ore named "&bDiamante: &b%{offdore::%arg-2%}%" to be unstealable
                                format slot 15 of player with gray stained glass pane named " " to be unstealable
                                format slot 16 of player with a ancient debris named "&fDetriti antichi: &b%{offnore::%arg-2%}%" to be unstealable
                                format slot 17 of player with gray stained glass pane named " " to be unstealable
                                format slot 18 of player with gray stained glass pane named " " to be unstealable
                                format slot 19 of player with a deepslate iron ore named "&fFerro in ardesia profonda: &b%{offdiore::%arg-2%}%" to be unstealable
                                format slot 20 of player with a deepslate copper ore named "&dRame in ardesia profonda: &b%{offdcore::%arg-2%}%" to be unstealable
                                format slot 21 of player with a deepslate gold ore named "&6Oro in ardesia profonda: &b%{offdgore::%arg-2%}%" to be unstealable
                                format slot 22 of player with a deepslate emerald ore named "&aSmeraldo in ardesia profonda: &b%{offdeore::%arg-2%}%" to be unstealable
                                format slot 23 of player with a deepslate diamond ore named "&bDiamante in ardesia profonda: &b%{offddore::%arg-2%}%" to be unstealable
                                format slot 24 of player with gray stained glass pane named " " to be unstealable
                                format slot 25 of player with gray stained glass pane named " " to be unstealable
                                format slot 26 of player with gray stained glass pane named " " to be unstealable
                                format slot 27 of player with compass named "&fTorna a &8[&4&lAnti-XRay&8]" to close then run [execute player command "/axr"]
                                format slot 28 of player with gray stained glass pane named " " to be unstealable
                                format slot 29 of player with gray stained glass pane named " " to be unstealable
                                format slot 30 of player with gray stained glass pane named " " to be unstealable
                                format slot 31 of player with gray stained glass pane named " " to be unstealable
                                format slot 32 of player with gray stained glass pane named " " to be unstealable
                                format slot 33 of player with gray stained glass pane named " " to be unstealable
                                format slot 34 of player with gray stained glass pane named " " to be unstealable
                                format slot 35 of player with arrow named "&fTorna a &8[&6&lAvvisi Offline&8]" to close then run [execute player command "/ofa"]
                                if sender is console:
                                    send "&6===================================================="
                                    send "&eResoconto del contatore offline per &c&l%arg-2%&e:" to console
                                    send " " to console
                                    send "&7- &fFerro: &b%{offiore::%arg-2%}%" to console
                                    send "&7- &fFerro in ardesia profonda: &b%{offdiore::%arg-2%}%" to console
                                    send "&7- &dRame: &b%{offcore::%arg-2%}%" to console
                                    send "&7- &dRame in ardesia profonda: &b%{offdcore::%arg-2%}%" to console
                                    send "&7- &6Oro: &b%{offgore::%arg-2%}%" to console
                                    send "&7- &6Oro in ardesia profonda: &b%{offdgore::%arg-2%}%" to console
                                    send "&7- &bDiamante: &b%{offdore::%arg-2%}%" to console
                                    send "&7- &bDiamante in ardesia profonda: &b%{offddore::%arg-2%}%" to console
                                    send "&7- &aSmeraldo: &b%{offeore::%arg-2%}%" to console
                                    send "&7- &aSmeraldo in ardesia profonda: &b%{offdeore::%arg-2%}%" to console
                                    send "&7- &fDetriti antichi: &f%{offnore::%arg-2%}%" to console
                                    send "&6===================================================="
                
command /timer [<player>] [<integer>]:
    executable by: console
    trigger:
        if arg-1 is set:
            set {time.%arg-player%} to arg 2
            set {countdown.%arg-player%} to true
            if {autocount.%arg-player%} is not set:
                set {autocount.%arg-player%} to 1
            if {icounter.%arg-player%} is not set:
                set {icounter.%arg-player%} to 0
            if {dicounter.%arg-player%} is not set:
                set {dicounter.%arg-player%} to 0
            if {ccounter.%arg-player%} is not set:
                set {ccounter.%arg-player%} to 0
            if {dccounter.%arg-player%} is not set:
                set {dccounter.%arg-player%} to 0
            if {dcounter.%arg-player%} is not set:
                set {dcounter.%arg-player%} to 0
            if {ddcounter.%arg-player%} is not set:
                set {ddcounter.%arg-player%} to 0
            if {ecounter.%arg-player%} is not set:
                set {ecounter.%arg-player%} to 0
            if {decounter.%arg-player%} is not set:
                set {decounter.%arg-player%} to 0
            if {gcounter.%arg-player%} is not set:
                set {gcounter.%arg-player%} to 0
            if {dgcounter.%arg-player%} is not set:
                set {dgcounter.%arg-player%} to 0
            if {rcounter.%arg-player%} is not set:
                set {rcounter.%arg-player%} to 0
            if {drcounter.%arg-player%} is not set:
                set {drcounter.%arg-player%} to 0
            if {lcounter.%arg-player%} is not set:
                set {lcounter.%arg-player%} to 0
            if {dlcounter.%arg-player%} is not set:
                set {dlcounter.%arg-player%} to 0
            if {ncounter.%arg-player%} is not set:
                set {ncounter.%arg-player%} to 0
            wait 1 tick
            loop arg-2 times:
                if {countdown.%arg-player%} is true:
                    remove 1 from {time.%arg-player%}
                    wait 1 second
                if {autokick} is true:
                    if {dmined.%arg-player%} is greater or equal to {detect_diamond_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 second
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {dmined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {ddmined.%arg-player%} is greater or equal to {detect_deepslate_diamond_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 second
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {ddmined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {cmined.%arg-player%} is greater or equal to {detect_copper_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 second
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {cmined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {dcmined.%arg-player%} is greater or equal to {detect_deepslate_copper_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 second
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {dcmined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {nmined.%arg-player%} is greater or equal to {detect_debris_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 second
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {nmined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {gmined.%arg-player%} is greater or equal to {detect_gold_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 seconds
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {gmined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {dgmined.%arg-player%} is greater or equal to {detect_deepslate_gold_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 seconds
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {dgmined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {imined.%arg-player%} is greater or equal to {detect_iron_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 seconds
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {imined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {dimined.%arg-player%} is greater or equal to {detect_deepslate_iron_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 seconds
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}" 
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {dimined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {emined.%arg-player%} is greater or equal to {detect_emerald_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 seconds
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}"
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {emined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                    if {demined.%arg-player%} is greater or equal to {detect_deepslate_emerald_amount_mined_in_x_sec}:
                        if {autocount.%arg-player%} is equal to {@autokicktime}:
                            loop all players:
                                if loop-player has permission "axr.alerts":
                                    send "{@prefix} {@auto_next_message}" to loop-player
                            execute console command "{@auto_next_command1}" 
                            wait 2 ticks
                            execute console command "{@auto_next_command2}"
                            wait 2 ticks
                            execute console command "{@auto_next_command3}"
                            wait 2 ticks
                            execute console command "{@auto_next_command4}"
                            delete {autocount.%arg-player%}
                        loop all players:
                            if loop-player has permission "axr.alerts":
                                send "{@prefix} {@auto_alert_message}" to loop-player   
                        wait 2 seconds
                        execute console command "{@auto_command1}"
                        wait 2 ticks
                        execute console command "{@auto_command2}"
                        wait 2 ticks
                        execute console command "{@auto_command3}"
                        wait 2 ticks
                        execute console command "{@auto_command4}"
                        delete {demined.%arg-player%}
                        add 1 to {autocount.%arg-player%}
                if {time.%arg-player%} is 0:
                    loop all players:
                        if loop-player has permission "axr.alerts":
                            set {_online} to 1
                            if {gcounter.%arg-player%} is greater or equal to {gold_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@gold_alert_msg}" to loop-player
                            if {dgcounter.%arg-player%} is greater or equal to {deepslate_gold_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@deepslate_gold_alert_msg}" to loop-player
                            if {icounter.%arg-player%} is greater or equal to {iron_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@iron_alert_msg}" to loop-player 
                            if {dicounter.%arg-player%} is greater or equal to {deepslate_iron_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@deepslate_iron_alert_msg}" to loop-player
                            if {dcounter.%arg-player%} is greater or equal to {diamond_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@diamond_alert_msg}" to loop-player
                            if {ddcounter.%arg-player%} is greater or equal to {deepslate_diamond_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@deepslate_diamond_alert_msg}" to loop-player
                            if {ecounter.%arg-player%} is greater or equal to {emerald_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@emerald_alert_msg}" to loop-player  
                            if {decounter.%arg-player%} is greater or equal to {deepslate_emerald_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@deepslate_emerald_alert_msg}" to loop-player
                            if {lcounter.%arg-player%} is greater or equal to {lapis_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@lapis_alert_msg}" to loop-player
                            if {dlcounter.%arg-player%} is greater or equal to {deepslate_lapis_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@deepslate_lapis_alert_msg}" to loop-player
                            if {ncounter.%arg-player%} is greater or equal to {nether_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@ancient_debris_msg}" to loop-player                                 
                            if {rcounter.%arg-player%} is greater or equal to {redstone_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@redstone_alert_msg}" to loop-player
                            if {drcounter.%arg-player%} is greater or equal to {deepslate_redstone_amount_mined_in_x_sec}:
                                message formatted "{@prefix} <tooltip:{@alert_hover_msg}><cmd:{@alert_command1}>&e%arg-player% <tooltip:&7Clicca per &aabilitare &7altri comandi><cmd:/axr alertclick>{@deepslate_redstone_alert_msg}" to loop-player
                        
                    if {gcounter.%arg-player%} is greater or equal to {gold_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offgore::%arg-player%} to {gcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offgore::%arg-player%} to {gcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &6Oro&f: &6%{gcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {dgcounter.%arg-player%} is greater or equal to {deepslate_gold_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offdgore::%arg-player%} to {dgcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offdgore::%arg-player%} to {dgcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &6Oro in ardesia profonda&f: &6%{dgcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {icounter.%arg-player%} is greater or equal to {iron_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offiore::%arg-player%} to {icounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offiore::%arg-player%} to {icounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &fFerro: %{icounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {dicounter.%arg-player%} is greater or equal to {deepslate_iron_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offdiore::%arg-player%} to {dicounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offdiore::%arg-player%} to {dicounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &fFerro in ardesia profonda: %{dicounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {ccounter.%arg-player%} is greater or equal to {copper_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offcore::%arg-player%} to {ccounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offcore::%arg-player%} to {ccounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &dRame: %{ccounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {dccounter.%arg-player%} is greater or equal to {deepslate_copper_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offdcore::%arg-player%} to {dccounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offdcore::%arg-player%} to {dccounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &dRame in ardesia profonda: %{dccounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {dcounter.%arg-player%} is greater or equal to {diamond_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offdore::%arg-player%} to {dcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offdore::%arg-player%} to {dcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &bDiamanti&f: &b%{dcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console       
                    if {ddcounter.%arg-player%} is greater or equal to {deepslate_diamond_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offddore::%arg-player%} to {ddcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offddore::%arg-player%} to {ddcounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &bDiamanti in ardesia profonda&f: &b%{ddcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console  
                    if {ecounter.%arg-player%} is greater or equal to {emerald_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offeore::%arg-player%} to {ecounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offeore::%arg-player%} to {ecounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &aSmeraldi&f: &a%{ecounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {decounter.%arg-player%} is greater or equal to {deepslate_emerald_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offdeore::%arg-player%} to {decounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                            else:
                                set {offdeore::%arg-player%} to {decounter.%arg-player%}
                                set {offloc::%arg-player%} to arg-player's location
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &aSmeraldi in ardesia profonda&f: &a%{decounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {rcounter.%arg-player%} is greater or equal to {redstone_amount_mined_in_x_sec}:
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &4Redstone&f: &a%{rcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {drcounter.%arg-player%} is greater or equal to {deepslate_redstone_amount_mined_in_x_sec}:
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &4Redstone in ardesia profonda&f: &a%{drcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {lcounter.%arg-player%} is greater or equal to {lapis_amount_mined_in_x_sec}:
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &1Lapislazzuli&f: &a%{lcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {dlcounter.%arg-player%} is greater or equal to {deepslate_lapis_amount_mined_in_x_sec}:
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &1Lapislazzuli in ardesia profonda&f: &a%{dlcounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console
                    if {ncounter.%arg-player%} is greater or equal to {nether_amount_mined_in_x_sec}:
                        if {_online} is not set:
                            if {offalerts::*} does not contain arg-player:
                                add arg-player to {offalerts::*}
                                set {offnore::%arg-player%} to {ncounter.%arg-player%} 
                            else:
                                set {offnore::%arg-player%} to {ncounter.%arg-player%}
                        if {con} is true:
                            send "{@prefix} &e%arg-player% &7ha trovato &fDetriti Antichi&f: &a%{ncounter.%arg-player%}% &7in &e%{timer}% &7secondi!" to console

                    wait 1 ticks
                    delete {countdown.%arg-player%}
                    delete {time.%arg-player%}
                    wait 5 ticks
                    delete {gmined.%arg-player%} and {dgmined.%arg-player%} and {cmined.%arg-player%} and {dcmined.%arg-player%} and {dmined.%arg-player%} and {ddmined.%arg-player%} and {imined.%arg-player%} and {dimined.%arg-player%} and {emined.%arg-player%} and {demined.%arg-player%} and {dcounter.%arg-player%} and {ddcounter.%arg-player%} and {ecounter.%arg-player%} and {decounter.%arg-player%} and {icounter.%arg-player%} and {dicounter.%arg-player%} and {gcounter.%arg-player%} and {dgcounter.%arg-player%} and {ccounter.%arg-player%} and {dccounter.%arg-player%}
                    delete {nmined.%arg-player%} and {lmined.%arg-player%} and {dlmined.%arg-player%} and {rmined.%arg-player%} and {drmined.%arg-player%} and {ncounter.%arg-player%} and {lcounter.%arg-player%} and {dlcounter.%arg-player%} and {rcounter.%arg-player%} and {drcounter.%arg-player%}
                    
on place:
    if {eworld::*} contains world of player:
        if player's gamemode is survival:
            if event-block is iron ore or deepslate iron ore or gold ore or deepslate gold ore or emerald ore or deepslate emerald ore or copper ore or deepslate copper ore or diamond ore or deepslate diamond ore or redstone ore or deepslate redstone ore or ancient debris or lapis lazuli ore or deepslate lapis lazuli ore:
                add event-location to {block::*}
                stop

on mine of iron ore or deepslate iron ore or gold ore or deepslate gold ore or emerald ore or deepslate emerald ore or copper ore or deepslate copper ore or diamond ore or deepslate diamond ore or redstone ore or deepslate redstone ore or ancient debris or lapis lazuli ore or deepslate lapis lazuli ore:
    if {eworld::*} contains world of player:
        if {axr.alert} is true:
            if player's gamemode is not creative:
                if {block::*} does not contain event-location:
                    if {countdown.%player%} is not set:                 
                        execute console command "/timer %player% %{timer}%" 
                if {block::*} contains event-location:
                    remove event-location from {block::*}
on mine of iron ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {iore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {imined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {icounter.%player%}
on mine of deepslate iron ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {diore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {dimined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {dicounter.%player%}
on mine of ancient debris:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {nore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {nmined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {ncounter.%player%}

on mine of gold ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {gore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {gmined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {gcounter.%player%}
on mine of deepslate gold ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {dgore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {dgmined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {dgcounter.%player%}
on mine of emerald ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {eore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {emined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {ecounter.%player%}
on mine of deepslate emerald ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {deore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {demined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {decounter.%player%}
on mine of diamond ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {dore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {dmined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {dcounter.%player%}
on mine of deepslate diamond ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {ddore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {ddmined.%player%}
                    if {countdown.%player%} is true:
                        if player doesn't have permission "axr.exempt":
                            add 1 to {ddcounter.%player%}
on mine of copper ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {core.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {cmined.%player%}
                    if {countdown.%player%} is true:
                        add 1 to {ccounter.%player%}
on mine of deepslate copper ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {dcore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {dcmined.%player%}
                    if {countdown.%player%} is true:
                        add 1 to {dccounter.%player%}
on mine of redstone ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {rore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {rmined.%player%}
                    if {countdown.%player%} is true:
                        add 1 to {rcounter.%player%}
on mine of deepslate redstone ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {drore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {drmined.%player%}
                    if {countdown.%player%} is true:
                        add 1 to {drcounter.%player%}
on mine of lapis lazuli ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {lore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {lmined.%player%}
                    if {countdown.%player%} is true:
                        add 1 to {lcounter.%player%}
                        add 1 to {drcounter.%player%}
on mine of deepslate lapis lazuli ore:
    if {eworld::*} contains world of player:
        if player's gamemode is not creative:
            if {axr.count} is true:
                add 1 to {dlore.%player%}
            if {axr.alert} is true:
                if {block::*} does not contain event-location:
                    add 1 to {dlmined.%player%}
                    if {countdown.%player%} is true:
                        add 1 to {dlcounter.%player%}