options:
    fall: &x&f&b&a&6&0&0A&x&e&c&9&7&0&0u&x&d&d&8&8&0&0t&x&c&e&7&a&0&0u&x&b&e&6&b&0&0n&x&a&f&5&c&0&0n&x&a&0&4&d&0&0o
    winter: &x&0&0&b&0&f&bI&x&2&1&b&3&f&2n&x&4&1&b&6&e&8v&x&6&2&b&a&d&fe&x&8&2&b&d&d&6r&x&a&3&c&0&c&cn&x&c&3&c&3&c&3o
    spring: &x&0&4&f&b&2&bP&x&0&4&f&2&4&6r&x&0&3&e&9&6&0i&x&0&3&e&0&7&bm&x&0&2&d&7&9&5a&x&0&2&c&e&b&0v&x&0&1&c&5&c&ae&x&0&1&b&c&e&5r&x&0&0&b&3&f&fa&a
    summer: &x&f&b&e&2&0&0E&x&f&c&c&7&0&0s&x&f&d&a&c&0&0t&x&f&d&9&2&0&0a&x&f&e&7&7&0&0t&x&f&f&5&c&0&0e

    helmet: "{custom_name:'{""bold"":true,""color"":""aqua"",""text"":""Cappello pesante""}',lore:['{""color"":""green"",""italic"":false,""text"":""Indistruttibile""}','{""text"":"""",""color"":""white"",""bold"":true}','{""color"":""gray"",""text"":""Un ottimo modo per giocare""}','{""color"":""gray"",""text"":""l\'SMP al calduccio.""}'],unbreakable:{show_in_tooltip:false},enchantment_glint_override:true,hide_additional_tooltip:{}}"
    chestplate: "{custom_name:'{""bold"":true,""color"":""aqua"",""text"":""Giacca pesante""}',lore:['{""color"":""green"",""italic"":false,""text"":""Indistruttibile""}','{""text"":"""",""color"":""white"",""bold"":true}','{""color"":""gray"",""text"":""Un ottimo modo per giocare""}','{""color"":""gray"",""text"":""l\'SMP al calduccio.""}'],unbreakable:{show_in_tooltip:false},enchantment_glint_override:true,hide_additional_tooltip:{}}"
    leggings: "{custom_name:'{""bold"":true,""color"":""aqua"",""text"":""Pantaloni pesanti""}',lore:['{""color"":""green"",""italic"":false,""text"":""Indistruttibile""}','{""text"":"""",""color"":""white"",""bold"":true}','{""color"":""gray"",""text"":""Un ottimo modo per giocare""}','{""color"":""gray"",""text"":""l\'SMP al calduccio.""}'],unbreakable:{show_in_tooltip:false},enchantment_glint_override:true,hide_additional_tooltip:{}}"
    boots: "{custom_name:'{""bold"":true,""color"":""aqua"",""text"":""Stivali da neve""}',lore:['{""color"":""green"",""italic"":false,""text"":""Indistruttibile""}','{""text"":"""",""color"":""white"",""bold"":true}','{""color"":""gray"",""text"":""Un ottimo modo per giocare""}','{""color"":""gray"",""text"":""l\'SMP al calduccio.""}'],unbreakable:{show_in_tooltip:false},enchantment_glint_override:true,hide_additional_tooltip:{}}"

command /winterkit:
    executable by: player, console
    trigger:
        if sender is player:
            set {_rs_season} to placeholder "rs_season_%{server.world.overworld}%" from player
            if {_rs_season} isn't "{@winter}":
                send "%{server.prefix.main}% &cPuoi utilizzare questo comando soltanto in inverno!"
                play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                stop
            else:
                if player's inventory has enough space for 4 diamond sword:
                    if {winterkit.%player%} isn't set:
                        give 1 leather helmet with nbt from {@helmet} to player
                        give 1 leather chestplate with nbt from {@chestplate} to player
                        give 1 leather leggings with nbt from {@leggings} to player
                        give 1 leather boots with nbt from {@boots} to player
                        send "%{server.prefix.main}% &aCon questo set di armatura sarai al sicuro dal freddo dell'inverno!"
                        send "%{server.prefix.main}% &6Fai attenzione a dove lo metti, non puoi richiederne un altro."
                        play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player
                        set {winterkit.%player%} to true
                        stop
                    else:
                        send "%{server.prefix.main}% &cHai già ottenuto questo set di armatura!"
                        play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                        stop
                else:
                    send "%{server.prefix.main}% &cPer questo kit sono richiesti almeno &64 slot liberi &cnel tuo inventario!"
                    send "%{server.prefix.main}% &cFai spazio e riprova."
                    play sound "entity.enderman.teleport" with volume 1 and pitch 0 at player for player
                    stop
        else:
            send "%{server.prefix.main}% &cSolo i giocatori possono eseguire questo comando!"
            stop


# ZONA DEBUG
options:
    debug_prefix: &8[&4&lDEBUG&8]

command /resetwinterkit [<offline player>]:
    permission: debug.commands
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    trigger:
        if arg-1 isn't set:
            delete {winterkit.%player%}
            send "{@debug_prefix} &aDa adesso è come se non avessi mai avuto l'armatura per l'inverno."
            stop
        else:
            if arg-1 isn't player:
                delete {winterkit.%arg-1%}
                send "{@debug_prefix} &aDa adesso è come se &e%arg-1% &anon avesse mai avuto l'armatura per l'inverno."
                stop
            else:
                send "{@debug_prefix} &cPer indicare il tuo personaggio è sufficiente eseguire il comando senza parametri."
                stop
