on load:
    if {pvp_status} is not set:
        set {pvp_status} to "&c● &c&lPvP disabilitato &c●"
        
command /pvp:
    permission: pvp.toggle
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    executable by: player, console
    description: Attiva o disattiva il PvP nel server.
    trigger:
        if {pvp} is true:
            delete {pvp}
            set {pvp_status} to "&c● &c&lPvP disabilitato &c●"
            broadcast "&8[&4🗡&8] &cPvP globale disabilitato!"
            send action bar "&a&lRiponi le armi. &aNon dovrai più combattere!" to all players
            stop
        else:
            set {pvp} to true
            set {pvp_status} to "&a● &a&lPvP abilitato &a●"
            broadcast "&8[&2🗡&8] &aPvP globale abilitato!"
            send action bar "&c&lPrepara le armi. &cÈ il momento di combattere!" to all players
            stop

on damage:
    if attacker is a player:
        if victim is a player:
            if {pvp} is not set:
                if damage cause is not fall:
                    cancel event
                    send "&8[&4🗡&8] &cIl PvP è disabilitato!" to attacker