options:
    prefix_enabled: &a[&2&lFly&a]
    prefix_disabled: &6[&c&lFly&6]
    prefix_error: &7[&c&lFly&7]
    warn: &6[&c&l!&6]

    error_sound: play sound "entity.enderman.teleport" with volume 1 and pitch 0

  # YML
    settings: "settings-%player's uuid%"
    data: "data-%{_p}'s uuid%"
    data_p2: "data-%{_p2}'s uuid%"
    genre: yaml value "genre" in "settings-%{_p}'s uuid%"
    fly: yaml value "player_info.player.fly" in "data-%{_p}'s uuid%"
    fly_p2: yaml value "player_info.player.fly" in "data-%{_p2}'s uuid%"
    fly_ab: yaml value "actionbar.flymode.enabled" in "settings-%loop-player's uuid%"

on join:
    wait 1 tick
    CheckFlyOnLogin(player)

on death of player:
    CheckFlyOnDeath(victim)

on player world change:
    CheckFlyOnWorldChange(player)

command /flytimer:
    executable by: player, console
    trigger:
        if {event.flymode.remain_time} > 1:
            send "{@warn} &aIl volo è abilitato per altri &e%{event.flymode.remain_time}% giorni&a."
            stop
        else if {event.flymode.remain_time} = 1:
            send "{@warn} &aIl volo è abilitato per &eun altro giorno&a."
            stop
        else if {event.flymode.remain_time} isn't set:
            send "{@prefix_error} &cNon è attivo nessun evento! Riprova più tardi."
            {@error_sound} at player for player
            stop

command /fly [<offline player>]:
    description: "Perché camminare quando puoi volare?"
    permission: fly.use
    permission message: %{server.prefix.main}% &cComando sconosciuto.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                ToggleFlySelf(player)
                    
            else: 
                if arg-1 is offline:
                    send "{@prefix_error} &6%arg-1% &cè offline." to player
                    {@error_sound} at player for player
                    stop
                else:
                    ToggleFlyOthersPlayer(player,arg-1)
        else:
            if arg-1 isn't set:
                send "{@prefix_error} &cSolo i giocatori possono eseguire questo comando."
                stop
                    
            else:
                if arg-1 is offline:
                    send "{@prefix_error} &6%arg-1% &cè offline." to console
                    stop
                else:
                    ToggleFlyOthersConsole(arg-1)


function CheckFlyOnLogin(p: player):
    if {_p}'s gamemode is survival or adventure:
        if {@fly} is true:
            if {_p} doesn't have permission "fly.keep" or "fly.*":
                set {_p}'s flight mode to false
                set {@fly} to false
                save yaml {@data}
                wait 2 seconds
                send "" to {_p}
                send "{@warn} &7Prima di uscire dal server potevi volare. Adesso non puoi più. {@warn}" to {_p}
                send "" to {_p}
            else:
                wait 2 seconds
                set {_p}'s flight mode to true
                send "" to {_p}
                send "{@prefix_enabled} &aPuoi ancora volare!" to {_p}
                send "" to {_p}

function CheckFlyOnDeath(p: player):
    if {@fly} is true:
        if {_p} doesn't have permission "fly.keep" or "fly.*":
            set {_p}'s flight mode to false
            set {@fly} to false
            save yaml {@data}
            if {@genre} is "%{server.genre.male}%":
                send "" to {_p}
                send "{@warn} &cSei morto con il volo abilitato! &cNon puoi più volare. {@warn}" to {_p}
                send "" to {_p}
            else if {@genre} is "%{server.genre.female}%":
                send "" to {_p}
                send "{@warn} &cSei morta con il volo abilitato! &cNon puoi più volare. {@warn}" to {_p}
                send "" to {_p}
        else:
            set {_p}'s flight mode to true # REMINDER: DA SPOSTARE IN "on respawn"
            send "" to {_p}
            send "{@prefix_enabled} &aPuoi volare anche dopo la morte, fantastico!" to {_p}
            send "" to {_p}

function CheckFlyOnWorldChange(p: player):
    if {_p} doesn't have permission "fly.keep" or "fly.*":
        if {@fly} is true:
            set {_p}'s flight mode to false
            set {@fly} to false
            save yaml {@data}
            wait 1 second
            send "" to {_p}
            send "{@warn} &cHai cambiato dimensione con il volo abilitato! Non puoi più volare. {@warn}" to {_p}
            send "" to {_p}

function ToggleFlySelf(p: player):
    if {_p} has permission "fly.use" or "fly.*":
        if {@fly} is true:
            set {_p}'s flight mode to false
            set {@fly} to false
            save yaml {@data}
            send "{@prefix_disabled} &cVolo disabilitato." to {_p}
            stop
        else:
            set {_p}'s flight mode to true
            set {@fly} to true
            save yaml {@data}
            send "{@prefix_enabled} &aVolo abilitato." to {_p}
            stop
    else:
        send "%{server.prefix.main}% &cComando sconosciuto." to {_p}
        stop

function ToggleFlyOthersPlayer(p1: player, p2: player):
    if {_p1} has permission "fly.use.other" or "fly.*":
        if {@fly_p2} is true:
            set {_p2}'s flight mode to false
            set {@fly_p2} to false
            save yaml {@data_p2}
            send "{@prefix_disabled} &cHai tolto le ali a &6%{_p2}%&c." to {_p1}
            send "{@prefix_disabled} &6%{_p1}% &cti ha tolto le ali. Da adesso non potrai più volare!" to {_p2}
            stop
        else:
            set {_p2}'s flight mode to true
            set {@fly_p2} to true
            save yaml {@data_p2}
            send "{@prefix_enabled} &aHai donato un paio d'ali a &e%{_p2}%&a." to {_p1}
            send "{@prefix_enabled} &e%{_p1}% &ati ha donato un paio di ali. Adesso puoi volare!" to {_p2}
            stop
    else:
        send "{@prefix_error} &cNon hai i permessi per farlo!" to {_p1}
        stop
        
function ToggleFlyOthersConsole(p: player):
    if {@fly} is true:
        set {_p}'s flight mode to false
        set {@fly} to false
        save yaml {@data}
        send "{@prefix_disabled} &cHai tolto le ali a &6%{_p}%&c." to console
        send "{@prefix_disabled} &cLa &6console &cti ha tolto le ali. Da adesso non potrai più volare!" to {_p}
        stop
    else:
        set {_p}'s flight mode to true
        set {@fly} to true
        save yaml {@data}
        send "{@prefix_enabled} &aHai donato un paio d'ali a &e%{_p}%&a." to console
        send "{@prefix_enabled} &aLa &econsole &ati ha donato un paio di ali. Adesso puoi volare!" to {_p}
        stop

function ToggleNoFlyGM(p: player):
    set {_p}'s flight mode to false
    set {@fly} to false
    save yaml {@data}

function ToggleFlyGM(p: player):
    set {_p}'s flight mode to true
    set {@fly} to true
    save yaml {@data}

every 10 ticks:
    loop all players:    
        if {@fly_ab} is true:
            if gamemode of loop-player isn't creative or spectator:
                if loop-player isn't flying:
                    send action bar "&a&lA TERRA &7| &bVelocità del passo: &e%walkspeed of loop-player%" to loop-player
                else:
                    send action bar "&c&lIN VOLO &7| &aVelocità di volo: &6%flyspeed of loop-player%" to loop-player