options:
    prefix: &6[&a&lGM&6]
    
    gm0: &fSopravvivenza
    gm1: &fCreativa
    gm2: &fAvventura
    gm3: &fSpettatore

    error_sound: entity.enderman.teleport
    
    no_flags: "{hide_additional_tooltip:{}}"

    data: "data-%{_p}'s uuid%"
    gamemode: yaml value "player_info.player.gamemode.info" in "data-%{_p}'s uuid%"
    gamemode_id: yaml value "player_info.player.gamemode.id" in "data-%{_p}'s uuid%"

# SOPRAVVIVENZA: iron sword with nbt from {@no_flags}
# CREATIVA: grass block
# AVVENTURA: empty map
# SPETTATORE: ender eye

command /gamemode [<text>] [<offline player>]:
    aliases: /gm
    permission: gm.use
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    description: Modifica la modalità di gioco di un giocatore.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "{@prefix} &cComando incompleto."
                    send "{@prefix} &cUtilizzo: &6/gm <&esurvival&6> [&egiocatore&6]"
                    send "{@prefix} &cUtilizzo: &6/gm <&ecreative&6> [&egiocatore&6]"
                    send "{@prefix} &cUtilizzo: &6/gm <&eadventure&6> [&egiocatore&6]"
                    send "{@prefix} &cUtilizzo: &6/gm <&espectator&6> [&egiocatore&6]"
                    stop

            else if arg-1 is "survival", "s" or "0":
                if arg-2 isn't set:
                    if gamemode of player isn't survival:
                        SetSurvivalGamemode(player)
                        ToggleNoFlyGM(player)
                        send "{@prefix} &aSei in modalità &csopravvivenza&a."
                        stop
                    else:
                        send "{@prefix} &cSei già in modalità &asopravvivenza&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                    else:
                        if gamemode of arg-2 isn't survival:
                            SetSurvivalGamemode(arg-2)
                            ToggleNoFlyGM(arg-2)
                            send "{@prefix} &aModalità &csopravvivenza &aimpostata per &e%arg-2%&a." to player
                            send "{@prefix} &aSei in modalità &csopravvivenza&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &asopravvivenza&c!"
                            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                            stop
                        
            else if arg-1 is "creative", "c" or "1":
                if arg-2 isn't set:
                    if gamemode of player isn't creative:
                        SetCreativeGamemode(player)
                        ToggleFlyGM(player)
                        send "{@prefix} &aSei in modalità &ccreativa&a."
                        stop
                    else:
                        send "{@prefix} &cSei già in modalità &acreativa&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                    else:
                        if gamemode of arg-2 isn't creative:
                            SetCreativeGamemode(arg-2)
                            ToggleFlyGM(arg-2)
                            send "{@prefix} &aModalità &ccreativa &aimpostata per &e%arg-2%&a." to player
                            send "{@prefix} &aSei in modalità &ccreativa&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &acreativa&c!"
                            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                            stop

            else if arg-1 is "adventure", "a" or "2":
                if arg-2 isn't set:
                    if gamemode of player isn't adventure:
                        SetAdventureGamemode(player)
                        ToggleNoFlyGM(player)
                        send "{@prefix} &aSei in modalità &cavventura&a."
                        stop
                    else:
                        send "{@prefix} &cSei già in modalità &aavventura&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                    else:
                        if gamemode of arg-2 isn't adventure:
                            SetAdventureGamemode(arg-2)
                            ToggleNoFlyGM(arg-2)
                            send "{@prefix} &aModalità &cavventura &aimpostata per &e%arg-2%&a." to player
                            send "{@prefix} &aSei in modalità &cavventura&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &aavventura&c!"
                            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                            stop

            else if arg-1 is "spectator", "sp" or "3":
                if arg-2 isn't set:
                    if gamemode of player isn't spectator:
                        SetSpectatorGamemode(player)
                        ToggleFlyGM(player)
                        send "{@prefix} &aSei in modalità &cspettatore&a."
                        stop
                    else:
                        send "{@prefix} &cSei già in modalità &aspettatore&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
                    else:
                        if gamemode of arg-2 isn't spectator:
                            SetSpectatorGamemode(arg-2)
                            ToggleFlyGM(arg-2)
                            send "{@prefix} &aModalità &cavventura &aimpostata per &e%arg-2%&a." to player
                            send "{@prefix} &aSei in modalità &cavventura&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &aspettatore&c!"
                            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                            stop

            else if arg-1 isn't "survival", "s", "0", "creative", "c", "1", "adventure", "a", "2", "spectator", "sp" or "3":
                send "{@prefix} &cComando sconosciuto."
                send "{@prefix} &cUtilizzo: &6/gm <&esurvival&6> [&egiocatore&6]"
                send "{@prefix} &cUtilizzo: &6/gm <&ecreative&6> [&egiocatore&6]"
                send "{@prefix} &cUtilizzo: &6/gm <&eadventure&6> [&egiocatore&6]"
                send "{@prefix} &cUtilizzo: &6/gm <&espectator&6> [&egiocatore&6]"
                stop
                
        else:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "{@prefix} &cComando sconosciuto."
                    send "{@prefix} &cUtilizzo: &6/gm <&esurvival&6> <&egiocatore&6>"
                    send "{@prefix} &cUtilizzo: &6/gm <&ecreative&6> <&egiocatore&6>"
                    send "{@prefix} &cUtilizzo: &6/gm <&eadventure&6> <&egiocatore&6>"
                    send "{@prefix} &cUtilizzo: &6/gm <&espectator&6> <&egiocatore&6>"
                    stop

            else if arg-1 is "survival", "s" or "0":
                if arg-2 isn't set:
                    send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                    send "{@prefix} &cSpecifica il nome di un giocatore!"
                    stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        stop
                    else:
                        if gamemode of arg-2 isn't survival:
                            SetSurvivalGamemode(arg-2)
                            ToggleNoFlyGM(arg-2)
                            send "{@prefix} &aModalità &csopravvivenza &aimpostata per &e%arg-2%&a." to console
                            send "{@prefix} &aSei in modalità &csopravvivenza&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &asopravvivenza&c!"
                            stop

            else if arg-1 is "creative", "c" or "1":
                if arg-2 isn't set:
                    send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                    send "{@prefix} &cSpecifica il nome di un giocatore!"
                    stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        stop
                    else:
                        if gamemode of arg-2 isn't creative:
                            SetCreativeGamemode(arg-2)
                            ToggleFlyGM(arg-2)
                            send "{@prefix} &aModalità &ccreativa &aimpostata per &e%arg-2%&a." to console
                            send "{@prefix} &aSei in modalità &ccreativa&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &acreativa&c!"
                            stop

            else if arg-1 is "adventure", "a" or "2":
                if arg-2 isn't set:
                    send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                    send "{@prefix} &cSpecifica il nome di un giocatore!"
                    stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        stop
                    else:
                        if gamemode of arg-2 isn't adventure:
                            SetAdventureGamemode(arg-2)
                            ToggleNoFlyGM(arg-2)
                            send "{@prefix} &aModalità &cavventura &aimpostata per &e%arg-2%&a." to console
                            send "{@prefix} &aSei in modalità &cavventura&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &aavventura&c!"
                            stop

            else if arg-1 is "spectator", "sp" or "3":
                if arg-2 isn't set:
                    send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                    send "{@prefix} &cSpecifica il nome di un giocatore!"
                    stop
                else:
                    if arg-2 is offline:
                        send "{@prefix} &6%arg-2% &cè offline."
                        stop
                    else:
                        if gamemode of arg-2 isn't spectator:
                            SetSpectatorGamemode(arg-2)
                            ToggleFlyGM(arg-2)
                            send "{@prefix} &aModalità &cavventura &aimpostata per &e%arg-2%&a." to console
                            send "{@prefix} &aSei in modalità &cavventura&a." to arg-2
                            stop
                        else:
                            send "{@prefix} &6%arg-2% &cè già in modalità &aspettatore&c!"
                            stop

            else if arg-1 isn't "survival", "s", "0", "creative", "c", "1", "adventure", "a", "2", "spectator", "sp" or "3":
                send "{@prefix} &cComando sconosciuto."
                send "{@prefix} &cUtilizzo: &6/gm <&esurvival&6> <&egiocatore&6>"
                send "{@prefix} &cUtilizzo: &6/gm <&ecreative&6> <&egiocatore&6>"
                send "{@prefix} &cUtilizzo: &6/gm <&eadventure&6> <&egiocatore&6>"
                send "{@prefix} &cUtilizzo: &6/gm <&espectator&6> <&egiocatore&6>"
                stop

on tab complete of "/gamemode" or "/gm":
    set tab completions for position 1 to "survival", "creative", "adventure" and "spectator"
    
command /gms [<offline player>]:
    permission: gms.use
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    description: Imposta la modalità di gioco di un giocatore in sopravvivenza.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop 
                else:
                    if gamemode of arg-1 isn't survival:
                        SetSurvivalGamemode(arg-1)
                        ToggleNoFlyGM(arg-1)
                        send "{@prefix} &aModalità &csopravvivenza &aimpostata per &e%arg-1%&a." to player
                        send "{@prefix} &aSei in modalità &csopravvivenza&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &asopravvivenza&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
            else:
                if gamemode of player isn't survival:
                    SetSurvivalGamemode(player)
                    ToggleNoFlyGM(player)
                    send "{@prefix} &aSei in modalità &csopravvivenza&a."
                    stop
                else:
                    send "{@prefix} &cSei già in modalità &asopravvivenza&c!"
                    play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                    stop
        else:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop
                else:
                    if gamemode of arg-1 isn't survival:
                        SetSurvivalGamemode(arg-1)
                        ToggleNoFlyGM(arg-1)
                        send "{@prefix} &aModalità &csopravvivenza &aimpostata per &e%arg-1%&a." to console
                        send "{@prefix} &aSei in modalità &csopravvivenza&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &asopravvivenza&c!"
                        stop
            else:
                send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                stop
                
command /gmc [<offline player>]:
    permission: gmc.use
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    description: Imposta la modalità di gioco di un giocatore in creativa.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop 
                else:
                    if gamemode of arg-1 isn't creative:
                        SetCreativeGamemode(arg-1)
                        ToggleFlyGM(arg-1)
                        send "{@prefix} &aModalità &ccreativa &aimpostata per &e%arg-1%&a." to player
                        send "{@prefix} &aSei in modalità &ccreativa&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &acreativa&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
            else:
                if gamemode of player isn't creative:
                    SetCreativeGamemode(player)
                    ToggleFlyGM(player)
                    send "{@prefix} &aSei in modalità &ccreativa&a."
                    stop
                else:
                    send "{@prefix} &cSei già in modalità &acreativa&c!"
                    play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                    stop
        else:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop
                else:
                    if gamemode of arg-1 isn't creative:
                        SetCreativeGamemode(arg-1)
                        ToggleFlyGM(arg-1)
                        send "{@prefix} &aModalità &ccreativa &aimpostata per &e%arg-1%&a." to console
                        send "{@prefix} &aSei in modalità &ccreativa&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &acreativa&c!"
                        stop
            else:
                send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                stop
            
command /gma [<offline player>]:
    permission: gma.use
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    description: Imposta la modalità di gioco di un giocatore in avventura.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop 
                else:
                    if gamemode of arg-1 isn't adventure:
                        SetAdventureGamemode(arg-1)
                        ToggleNoFlyGM(arg-1)
                        send "{@prefix} &aModalità &cavventura &aimpostata per &e%arg-1%&a." to player
                        send "{@prefix} &aSei in modalità &cavventura&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &aavventura&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
            else:
                if gamemode of player isn't adventure:
                    SetAdventureGamemode(player)
                    ToggleNoFlyGM(player)
                    send "{@prefix} &aSei in modalità &cavventura&a."
                    stop
                else:
                    send "{@prefix} &cSei già in modalità &aavventura&c!"
                    play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                    stop
        else:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop
                else:
                    if gamemode of arg-1 isn't adventure:
                        SetAdventureGamemode(arg-1)
                        ToggleNoFlyGM(arg-1)
                        send "{@prefix} &aModalità &cavventura &aimpostata per &e%arg-1%&a." to console
                        send "{@prefix} &aSei in modalità &cavventura&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &aavventura&c!"
                        stop
            else:
                send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                stop
            
command /gmsp [<offline player>]:
    permission: gmsp.use
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    description: Imposta la modalità di gioco di un giocatore in spettatore.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop 
                else:
                    if gamemode of arg-1 isn't spectator:
                        SetSpectatorGamemode(arg-1)
                        ToggleFlyGM(arg-1)
                        send "{@prefix} &aModalità &cspettatore &aimpostata per &e%arg-1%&a." to player
                        send "{@prefix} &aSei in modalità &cspettatore&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &aspettatore&c!"
                        play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                        stop
            else:
                if gamemode of player isn't spectator:
                    SetSpectatorGamemode(player)
                    ToggleFlyGM(player)
                    send "{@prefix} &aSei in modalità &cspettatore&a."
                    stop
                else:
                    send "{@prefix} &cSei già in modalità &aspettatore&c!"
                    play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
                    stop
        else:
            if arg-1 is set:
                if arg-1 is offline:
                    send "{@prefix} &6%arg-1% &cè offline."
                    stop
                else:
                    if gamemode of arg-1 isn't spectator:
                        SetSpectatorGamemode(arg-1)
                        ToggleFlyGM(arg-1)
                        send "{@prefix} &aModalità &cspettatore &aimpostata per &e%arg-1%&a." to console
                        send "{@prefix} &aSei in modalità &cspettatore&a." to arg-1
                        stop
                    else:
                        send "{@prefix} &6%arg-1% &cè già in modalità &aspettatore&c!"
                        stop
            else:
                send "{@prefix} &cSolo i giocatori possono cambiare la propria modalità di gioco."
                stop

function SetSurvivalGamemode(p: player):
    set {_p}'s gamemode to survival
    set {@gamemode} to "{@gm0}"
    set {@gamemode_id} to iron sword with nbt from {@no_flags}
    save yaml {@data}

function SetCreativeGamemode(p: player):
    set {_p}'s gamemode to creative
    set {@gamemode} to "{@gm1}"
    set {@gamemode_id} to grass block
    save yaml {@data}

function SetAdventureGamemode(p: player):
    set {_p}'s gamemode to adventure
    set {@gamemode} to "{@gm2}"
    set {@gamemode_id} to empty map
    save yaml {@data}

function SetSpectatorGamemode(p: player):
    set {_p}'s gamemode to spectator
    set {@gamemode} to "{@gm3}"
    set {@gamemode_id} to ender eye
    save yaml {@data}