options:
    prefix_enabled: &a[&2&lGod&a]
    prefix_disabled: &6[&c&lGod&6]
    prefix_error: &7[&c&lGod&7]
    warn: &6[&c&l!&6]

    error_sound: play sound "entity.enderman.teleport" with volume 1 and pitch 0

  # YML
    settings: "settings-%player's uuid%"
    data: "data-%{_p}'s uuid%"
    data_p2: "data-%{_p2}'s uuid%"
    genre: yaml value "genre" in "settings-%{_p}'s uuid%"
    god_player: yaml value "player_info.player.god" in "data-%player's uuid%"
    god: yaml value "player_info.player.god" in "data-%{_p}'s uuid%"
    god_p2: yaml value "player_info.player.god" in "data-%{_p2}'s uuid%"
    god_ab: yaml value "actionbar.godmode.enabled" in "settings-%loop-player's uuid%"

on join:
    wait 1 tick
    CheckGodOnLogin(player)
            
on food level change:
    if {@god_player} is true:
        cancel event

command /god [<offline player>]:
    description: "I pericoli per te non sono più un problema!"
    permission: command.god
    permission message: %{server.prefix.main}% &cComando sconosciuto.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                ToggleGodSelf(player)
            else:
                if arg-1 is offline:
                    send "{@prefix_error} &6%arg-1% &cè offline." to player
                    {@error_sound} at player for player
                    stop
                else:
                    ToggleGodOthersPlayer(player,arg-1)
        else:
            if arg-1 isn't set:
                send "{@prefix_error} &cSolo i giocatori possono eseguire questo comando."
                stop
            else:
                if arg-1 is offline:
                    send "{@prefix_error} &6%arg-1% &cè offline."
                    stop
                else:
                    ToggleGodOthersConsole(arg-1)


function CheckGodOnLogin(p: player):
    if {@god} is true:
        if {_p} doesn't have permission "god.keep" or "god.*":
            make {_p} vulnerable
            set {@god} to false
            save yaml {@data}
            wait 2 seconds
            send "" to {_p}
            send "{@warn} &7Prima di uscire dal server eri immortale. Adesso non lo sei più. {@warn}" to {_p}
            send "" to {_p}
        else:
            wait 2 seconds
            send "" to {_p}
            send "{@prefix_enabled} &aSei ancora immortale!" to {_p}
            send "" to {_p}

function ToggleGodSelf(p: player):
    if {_p} has permission "god.use" or "god.*":
        if {@god} is true:
            make {_p} vulnerable
            set {@god} to false
            save yaml {@data}
            send "{@prefix_disabled} &cModalità Dio disattivata! &6I mob potranno ferirti." to {_p}
            stop
        else:
            make {_p} invulnerable
            set {@god} to true
            save yaml {@data}
            heal {_p}
            feed {_p}
            send "{@prefix_enabled} &aModalità Dio attivata! &bI mob ti ignoreranno." to {_p}
            stop
    else:
        send "%{server.prefix.main}% &cComando sconosciuto." to {_p}

function ToggleGodOthersPlayer(p1: player, p2: player):
    if {_p1} has permission "god.use.other" or "god.*":
        if {@god_p2} is true:
            make {_p2} vulnerable
            set {@god_p2} to false
            save yaml {@data_p2}
            send "{@prefix_disabled} &cHai tolto l'immortalità a &6%{_p2}%&c." to {_p1}
            send "{@prefix_disabled} &6%{_p1}% &cti ha tolto l'immortalità! &6I mob potranno ferirti." to {_p2}
            stop
        else:
            make {_p2} invulnerable
            set {@god_p2} to true
            save yaml {@data_p2}
            heal {_p2}
            feed {_p2}
            send "{@prefix_enabled} &aHai reso &e%{_p2}% &aimmortale." to {_p1}
            send "{@prefix_enabled} &e%{_p1}% &ati ha reso immortale! &bI mob ti ignoreranno." to {_p2}
            stop
    else:
        send "{@prefix_error} &cNon hai i permesso per farlo!" to {_p1}
        stop

function ToggleGodOthersConsole(p: player):
    if {@god} is true:
        make {_p} vulnerable
        set {@god} to false
        save yaml {@data}
        send "{@prefix_disabled} &cHai tolto l'immortalità a &6%{_p}%&c." to console
        send "{@prefix_disabled} &cLa &6console &cti ha tolto l'immortalità! &6I mob potranno ferirti." to {_p}
        stop
    else:
        make {_p} invulnerable
        set {@god} to true
        save yaml {@data}
        heal {_p}
        feed {_p}
        send "{@prefix_enabled} &aHai reso &e%{_p}% &aimmortale." to console
        send "{@prefix_enabled} &aLa &econsole &ati ha dato l'immortalità! &bI mob ti ignoreranno." to {_p}
        stop

every 10 ticks:
    loop all players:
        if {@god_ab} is true:
            if gamemode of loop-player isn't creative or spectator:
                send action bar "&aFormidabile! &bNon subirai più danni!" to loop-player