options:
    prefix: &8[&4&lTP&8]

    confirm_sound: block.note_block.pling
    error_sound: entity.enderman.teleport

  # YML
    genre: yaml value "genre" in "settings-%player's uuid%"

command /teleport [<offline player>] [<offline player>]:
    permission: teleport.use
    permission message: {@prefix} &cComando sconosciuto.
    description: "TELETRASPORTO!"
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "{@prefix} &cUtilizzo: &6/teleport <giocatore1> <giocatore2>"
                    stop
                else:
                    send "{@prefix} &cUtilizzo: &6/teleport <giocatore1> <giocatore2>"
                    stop
            else if arg-1 is player:
                if arg-2 isn't set:
                    if {@genre} is "%{server.genre.male}%":
                        send "{@prefix} &cNon puoi teletrasportarti da te stesso!"
                        stop
                    else if {@genre} is "%{server.genre.female}%":
                        send "{@prefix} &cNon puoi teletrasportarti da te stessa!"
                        stop
                if arg-2 is player:
                    if {@genre} is "%{server.genre.male}%":
                        send "{@prefix} &cNon puoi teletrasportare te stesso da te stesso!"
                        stop
                    else if {@genre} is "%{server.genre.female}%":
                        send "{@prefix} &cNon puoi teletrasportare te stessa da te stessa!"
                        stop
                else if arg-2 isn't player:
                    if {@genre} is "%{server.genre.male}%":
                        teleport player at arg-2's location
                        send "{@prefix} &7Ti ho portato da &c%arg-2%&7."
                        stop
                    else if {@genre} is "%{server.genre.female}%":
                        send "{@prefix} &7Ti ho portata da &c%arg-2%&7."
                        stop
            else if arg-1 is offline:
                send "{@prefix} &c%arg-1% &6non è online!"
                stop
            else if arg-1 is online:
                if arg-2 isn't set:
                    if {@genre} is "%{server.genre.male}%":
                        teleport player at arg-1's location
                        send "{@prefix} &7Ti ho portato da &c%arg-1%&7."
                        stop
                    else if {@genre} is "%{server.genre.female}%":
                        teleport player at arg-1's location
                        send "{@prefix} &7Ti ho portata da &c%arg-1%&7."
                        stop
                else if arg-2 is offline:
                    send "{@prefix} &c%arg-2% &6non è online!"
                    stop
                else if arg-2 is online:
                    teleport arg-1 at arg-2's location
                    send "{@prefix} &7Hai portato &c%arg-1% &7da &c%arg-2%&7."
                    stop
        else:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "{@prefix} &cUtilizzo: &6/teleport <giocatore1> <giocatore2>"
                    stop
                else:
                    send "{@prefix} &cUtilizzo: &6/teleport <giocatore1> <giocatore2>"
                    stop
            else if arg-1 is offline:
                send "{@prefix} &c%arg-1% &6non è online!"
                stop
            else if arg-1 is online:
                if arg-2 isn't set:
                    send "{@prefix} &cDa chi vuoi portare %arg-1%?"
                    stop
                if arg-2 = arg-1:
                    send "{@prefix} &cNon puoi teletrasportare %arg-1% da %arg-2%!"
                    stop
                else if arg-2 is offline:
                    send "{@prefix} &c%arg-2% &6non è online!"
                    stop
                else if arg-2 is online:
                    teleport arg-1 at arg-2's location
                    send "{@prefix} &7Hai portato &c%arg-1% &7da &c%arg-2%&7."
                    stop