options:
    error_sound: entity.enderman.teleport
    check_sound: entity.player.levelup

    lclick_info: &bClic sinistro per consultare il suo profilo in-game.
    rclick_info: &9Clic destro per consultare il suo profilo NameMC.
    click_teleport: &eClicca per teletrasportarti.

    no_flags: "{hide_additional_tooltip:{}}"
    glinted: "{enchantment_glint_override:true}"

    total_medals: 15

  # YML
    data: "data-%player's uuid%"
    data_p: "data-%{_p}'s uuid%"
    genre: yaml value "genre" in "settings-%{_arg}'s uuid%"
    gui_background: yaml value "personalization.gui_background.enabled" in "settings-%{_p}'s uuid%"
    
    nick: yaml value "player_info.player.nickname" in "data-%{_p}'s uuid%"
    nick_arg: yaml value "player_info.player.nickname" in "data-%arg-1's uuid%"
    gamemode: yaml value "player_info.player.gamemode.info" in "data-%{_p}'s uuid%"
    gamemode_gui_arg: yaml value "player_info.player.gamemode.info" in "data-%{_arg}'s uuid%"
    gamemode_arg: yaml value "player_info.player.gamemode.info" in "data-%arg-1's uuid%"
    gamemode_id_arg: yaml value "player_info.player.gamemode.id" in "data-%{_arg}'s uuid%"
    status: yaml value "player_info.player.status.new" in "data-%{_p}'s uuid%"
    status_arg: yaml value "player_info.player.status.new" in "data-%arg-1's uuid%"
    god: yaml value "player_info.player.god" in "data-%{_p}'s uuid%"
    god_arg: yaml value "player_info.player.god" in "data-%arg-1's uuid%"
    fly: yaml value "player_info.player.fly" in "data-%{_p}'s uuid%"
    fly_arg: yaml value "player_info.player.fly" in "data-%arg-1's uuid%"
    freeze: yaml value "player_info.player.freeze" in "data-%{_p}'s uuid%"
    freeze_arg: yaml value "player_info.player.freeze" in "data-%arg-1's uuid%"
    
command /whois [<offline player>]:
    permission: whois.use
    permission message: &4[&6&lS&e&lM&6&lP&4] &cComando sconosciuto.
    description: Visualizza tutte le informazioni necessarie di un giocatore.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                send "%{server.prefix.main}% &cUtilizzo: &6/whois <giocatore>"
                stop
            else if arg-1 is online:
                set {whois.%player%.arg} to arg-1
                OnlineWhoIsGUI(player,{whois.%player%.arg})
                stop
            else if arg-1 has played before:
                set {whois.%player%.arg} to arg-1
                OfflineWhoIsGUI(player,{whois.%player%.arg})
                stop
            else:
                send "%{server.prefix.main}% &cNon ho trovato informazioni per &6%arg-1%&c."
                stop
        else:
            if arg-1 isn't set:
                send "%{server.prefix.main}% &cUtilizzo: &6/whois <giocatore>"
                stop
            if {players::*} contains arg-1:
                set {_player_hp} to placeholder "auraskills_hp" from arg-1
                set {_player_hp_max} to placeholder "auraskills_hp_max" from arg-1
                set {_player_xp} to placeholder "player_current_exp" from arg-1
                set {_player_xp_level} to placeholder "player_level" from arg-1
                set {_player_x} to placeholder "player_x" from arg-1
                set {_player_y} to placeholder "player_y" from arg-1
                set {_player_z} to placeholder "player_z" from arg-1
                set {_player_biome} to placeholder "player_biome_capitalized" from arg-1
                set {_player_ip} to placeholder "player_ip" from arg-1
                set {_player_op} to placeholder "player_is_op" from arg-1
                set {_player_strength} to placeholder "auraskills_strength" from arg-1
                set {_player_health} to placeholder "auraskills_health" from arg-1
                set {_player_regeneration} to placeholder "auraskills_regeneration" from arg-1
                set {_player_luck} to placeholder "auraskills_luck" from arg-1
                set {_player_wisdom} to placeholder "auraskills_wisdom" from arg-1
                set {_player_toughness} to placeholder "auraskills_toughness" from arg-1
                set {_player_crit_chance} to placeholder "auraskills_crit_chance" from arg-1
                set {_player_crit_damage} to placeholder "auraskills_crit_damage" from arg-1
                set {_player_speed} to placeholder "auraskills_speed" from arg-1
                set {_player_nick} to {@nick_arg}
                set {_player_gamemode} to {@gamemode_arg}
                set {_player_status} to {@status_arg}
                set {_player_god} to {@god_arg}
                set {_player_fly} to {@fly_arg}
                set {_player_freeze} to {@freeze_arg}
                if arg-1 is online:
                    send "&3====== &bInformazioni per &a%arg-1's name% &3======"
                    send "&fINFORMAZIONI GENERALI"
                    send " &6GIOCATORE"
                    if {_player_nick} isn't arg-1:
                        send "  &eNome (Soprannome)&7: &f%arg-1's name% (%{_player_nick}%)"
                    else:
                        send "  &eNome&7: &f%arg-1's name%"
                    send "  &eUUID&7: &f%arg-1's uuid%"
                    send "  &3Stato&7: &f""%{_player_status}%&f"""
                    #send "  &1AFK&7: %{afk.%arg-1%.status}%"
                    send "  &cModalità di gioco&7: &f%{_player_gamemode}%"
                    send "  &aXP&7: &2%{_player_xp_level}% livelli (&a%regex({_player_xp})% punti&2)"
                    send "  &bVelocità volo&7: &f%arg-1's flyspeed%"
                    send "  &bVelocità passo&7: &f%arg-1's walkspeed%"
                    send "  &4OP&7: %{_player_op}%"
                    send "  &4Immortale&7: %{_player_god}%"
                    send "  &4Volo&7: %{_player_fly}%"
                    send "  &4Immobile&7: %{_player_freeze}%"
                    send " &6ENERGIA"
                    send "  &cVita&7: &f%{_player_hp}%/%{_player_hp_max}%"
                    send "  &aFame&7: &f%arg-1's food level%/10"
                    send " &6POSIZIONE"
                    send "  &fMondo&7: %{whois.world.%arg-1%}%"
                    send "  &fCoordinate&7: &a%{_player_x}% %{_player_y}% %{_player_z}%"
                    send "  &fBioma&7: &b%{_player_biome}%"
                    send " &6TEMPO DI GIOCO"
                    send "  &aSessione&7: &f%{playtime.actual_session.days.%arg-1%}% giorni, %{playtime.actual_session.hours.%arg-1%}% ore, %{playtime.actual_session.minutes.%arg-1%}% minuti e %{playtime.actual_session.seconds.%arg-1%}% secondi"
                    send "  &cTotale&7: &f%{playtime.total.days.%arg-1%}% giorni, %{playtime.total.hours.%arg-1%}% ore, %{playtime.total.minutes.%arg-1%}% minuti e %{playtime.total.seconds.%arg-1%}% secondi"
                    send "  &eSessioni&7: &f%{playtime.sessions.%arg-1%}%"
                    send "  &fPrima volta nel server&7: &f%{playtime.first_login.%arg-1%}%"
                    send " &cCONNETTIVITÀ"
                    send "  &eIndirizzo IP&7: &f%{_player_ip}%"
                    send "  &6Ping&7: &f%arg-1's ping% ms"
                    send ""
                    send "&fPROFILO GIOCATORE"
                    send " &6ABILITÀ"
                    send "  &4Forza&7: &f+%{_player_strength}%"
                    send "  &cIncremento Salute&7: &f+%{_player_health}%"
                    send "  &6Rigenerazione&7: &f+%{_player_regeneration}%"
                    send "  &2Fortuna&7: &f+%{_player_luck}%"
                    send "  &9Saggezza&7: &f+%{_player_wisdom}%"
                    send "  &5Resistenza&7: &f+%{_player_toughness}%"
                    send "  &2Probabilità Colpo Critico&7: &f+%{_player_crit_chance}%%%"
                    send "  &3Danno Colpo Critico&7: &f+%{_player_crit_damage}%%%"
                    send "  &fVelocità&7: &f+%{_player_speed}%"
                    send " &6SUPPORTO"
                    send "  &eBug segnalati&7: &f%{reported_bugs::%arg-1%}%"
                    send "  &eFeedback inviati&7: &f%{feedback_sent::%arg-1%}%"
                    send " &ePROGRESSI"
                    send " &dFama&7: &f%regex({fame::%arg-1%})% &7(%{rank.%arg-1%}%&7)"
                    send " &eMedaglie&7: &f%{medals.%arg-1%}%/15 &e(&7Ultima medaglia ottenuta: %{medals.%arg-1%.last_obtained}%&e)"
                    send " &aSTATISTICHE SANGUINARIE"
                    send "  &cUccisioni&7: &f%regex({kills::%arg-1%})%"
                    send "  &cMorti&7: &f%regex({deaths::%arg-1%})%"
                    send "  &cRapporto U/M&7: &f%regex({kills::%arg-1%}/{deaths::%arg-1%})%"
                    send "  &6Danni inflitti&7: &f%regex({infldamage::%arg-1%})%"
                    send "  &6Danni subiti&7: &f%regex({suffdamage::%arg-1%})%"
                    send "  &eSerie di uccisioni&7: &f%regex({killstreak::%arg-1%})%/%regex({killstreak_max.%arg-1%})%"
                    send " &aSTATISTICHE MINERARIE"
                    send "  &cBlocchi distrutti&7: &f%regex({broken_blocks::%arg-1%})%"
                    send "  &bBlocchi piazzati&7: &f%regex({placed_blocks::%arg-1%})%"
                    stop
                else:
                    if arg-1 has played before:
                        send "&3====== &bInformazioni per &a%arg-1's name% &c(&4OFFLINE&c) &3======"
                        send "&fINFORMAZIONI GENERALI"
                        send " &6GIOCATORE"
                        if {_player_nick} isn't arg-1:
                            send "  &eNome (Soprannome)&7: &f%arg-1's name% (%{_player_nick}%)"
                        else:
                            send "  &eNome&7: &f%arg-1's name%"
                        send "  &eUUID&7: &f%arg-1's uuid%"
                        send "  &3Stato&7: &f""%{_player_status}%&f"""
                        #send "  &1AFK&7: %{afk.%arg-1%.status}%"
                        send "  &cModalità di gioco&7: &f%{_player_gamemode}%"
                        send "  &aXP&7: &2%{whois.offline.xp_level.%arg-1%}% livelli (&a%regex({whois.offline.xp.%arg-1%})% punti&2)"
                        send "  &4OP&7: %{_player_op}%"
                        send "  &4Immortale&7: %{_player_god}%"
                        send "  &4Volo&7: %{_player_fly}%"
                        send "  &4Immobile&7: %{_player_freeze}%"
                        send " &6ENERGIA"
                        send "  &cVita&7: &f%{whois.offline.hp.%arg-1%}%/%{whois.offline.max_hp.%arg-1%}%"
                        send "  &aFame&7: &f%{whois.offline.saturation.%arg-1%}%/10"
                        send " &6POSIZIONE"
                        send "  &fMondo&7: %{whois.world.%arg-1%}%"
                        send "  &fCoordinate&7: &a%{whois.position.x.%arg-1%}% %{whois.position.y.%arg-1%}% %{whois.position.z.%arg-1%}%"
                        send "  &fBioma&7: &b%{whois.position.biome.%arg-1%}%"
                        send " &6TEMPO DI GIOCO"
                        send "  &aUltima sessione&7: &f%{playtime.last_session.days.%arg-1%}% giorni, %{playtime.last_session.hours.%arg-1%}% ore, %{playtime.last_session.minutes.%arg-1%}% minuti e %{playtime.last_session.seconds.%arg-1%}% secondi"
                        send "  &cTotale&7: &f%{playtime.total.days.%arg-1%}% giorni, %{playtime.total.hours.%arg-1%}% ore, %{playtime.total.minutes.%arg-1%}% minuti e %{playtime.total.seconds.%arg-1%}% secondi"
                        send "  &eSessioni&7: &f%{playtime.sessions.%arg-1%}%"
                        send "  &aPrima volta nel server&7: &f%{playtime.first_login.%arg-1%}%"
                        send "  &cUltima volta online&7: &f%{playtime.last_seen.%arg-1%}%"
                        send ""
                        send "&fPROFILO GIOCATORE"
                        send " &6ABILITÀ"
                        send "  &4Forza&7: &f+%{whois.offline.strength.%arg-1%}%"
                        send "  &cIncremento Salute&7: &f+%{whois.offline.health.%arg-1%}%"
                        send "  &6Rigenerazione&7: &f+%{whois.offline.regeneration.%arg-1%}%"
                        send "  &2Fortuna&7: &f+%{whois.offline.luck.%arg-1%}%"
                        send "  &9Saggezza&7: &f+%{whois.offline.wisdom.%arg-1%}%"
                        send "  &5Resistenza&7: &f+%{whois.offline.toughness.%arg-1%}%"
                        send "  &2Probabilità Colpo Critico&7: &f+%{whois.offline.crit_chance.%arg-1%}%%%"
                        send "  &3Danno Colpo Critico&7: &f+%{whois.offline.crit_damage.%arg-1%}%%%"
                        send "  &fVelocità&7: &f+%{whois.offline.speed.%arg-1%}%"
                        send " &6SUPPORTO"
                        send "  &eBug segnalati&7: &f%{reported_bugs::%arg-1%}%"
                        send "  &eFeedback inviati&7: &f%{feedback_sent::%arg-1%}%"
                        send " &ePROGRESSI"
                        send " &dFama&7: &f%regex({fame::%arg-1%})% &7(%{rank.%arg-1%}%&7)"
                        send " &eMedaglie&7: &f%{medals.%arg-1%}%/15 &e(&7Ultima medaglia ottenuta: %{medals.%arg-1%.last_obtained}%&e)"
                        send " &aSTATISTICHE SANGUINARIE"
                        send "  &cUccisioni&7: &f%regex({kills::%arg-1%})%"
                        send "  &cMorti&7: &f%regex({deaths::%arg-1%})%"
                        send "  &cRapporto U/M&7: &f%regex({kills::%arg-1%}/{deaths::%arg-1%})%"
                        send "  &6Danni inflitti&7: &f%regex({infldamage::%arg-1%})%"
                        send "  &6Danni subiti&7: &f%regex({suffdamage::%arg-1%})%"
                        send "  &eSerie di uccisioni&7: &f%regex({killstreak::%arg-1%})%/%regex({killstreak_max.%arg-1%})%"
                        send " &aSTATISTICHE MINERARIE"
                        send "  &cBlocchi distrutti&7: &f%regex({broken_blocks::%arg-1%})%"
                        send "  &bBlocchi piazzati&7: &f%regex({placed_blocks::%arg-1%})%"
                        stop
            else:
                send "%{server.prefix.main}% &cNon ho trovato informazioni per &6%arg-1%&c."
                stop

on tab complete of "/whois":
    set tab completions for position 1 to {players::*}

on player world change:
    if world of player is "smp":
        set {whois.world.%player%} to "&aOverworld"
        set {whois.world.marker.%player%} to grass block
    if world of player is "smp_nether":
        set {whois.world.%player%} to "&cNether"
        set {whois.world.marker.%player%} to netherrack
    if world of player is "smp_the_end":
        set {whois.world.%player%} to "&dEnd"
        set {whois.world.marker.%player%} to end stone

on quit:
    set {whois.position.x.%player%} to placeholder "player_x" from player
    set {whois.position.y.%player%} to placeholder "player_y" from player
    set {whois.position.z.%player%} to placeholder "player_z" from player
    set {whois.position.biome.%player%} to placeholder "player_biome_capitalized" from player
    set {whois.offline.saturation.%player%} to player's food level
    set {whois.offline.hp.%player%} to placeholder "auraskills_hp" from player
    set {whois.offline.max_hp.%player%} to placeholder "auraskills_hp_max" from player
    set {whois.offline.empty_slots.%player%} to placeholder "player_empty_slots" from player
    set {whois.offline.xp.%player%} to placeholder "player_current_exp" from player
    set {whois.offline.xp_level.%player%} to placeholder "player_level" from player
    set {whois.offline.luck.%player%} to placeholder "auraskills_luck" from player
    set {whois.offline.health.%player%} to placeholder "auraskills_health" from player
    set {whois.offline.wisdom.%player%} to placeholder "auraskills_wisdom" from player
    set {whois.offline.strength.%player%} to placeholder "auraskills_strength" from player
    set {whois.offline.regeneration.%player%} to placeholder "auraskills_regeneration" from player
    set {whois.offline.toughness.%player%} to placeholder "auraskills_toughness" from player
    set {whois.offline.crit_chance.%player%} to placeholder "auraskills_crit_chance" from player
    set {whois.offline.crit_damage.%player%} to placeholder "auraskills_crit_damage" from player
    set {whois.offline.speed.%player%} to placeholder "auraskills_speed" from player
    if world of player is "smp":
        set {whois.world.%player%} to "&aOverworld"
        set {whois.world.marker.%player%} to grass block
    if world of player is "smp_nether":
        set {whois.world.%player%} to "&cNether"
        set {whois.world.marker.%player%} to netherrack
    if world of player is "smp_the_end":
        set {whois.world.%player%} to "&dEnd"
        set {whois.world.marker.%player%} to end stone
    if player's tool is air:
        set {whois.equip.mainhand.%player%} to lime stained glass pane named "&aMano principale" with lore "&6%player% &7non ha" and "&7nulla in mano."
    else:
        set {whois.equip.mainhand.%player%} to player's held item
    if slot 40 of player's inventory is air:
        set {whois.equip.offhand.%player%} to magenta stained glass pane named "&dMano secondaria" with lore "&6%player% &7non ha" and "&7oggetti nella seconda mano."
    else:
        set {whois.equip.offhand.%player%} to player's off hand item
    if slot 39 of player's inventory is air:
        set {whois.equip.helmet.%player%} to red stained glass pane named "&cSlot elmetto" with lore "&6%player% &7non sta" and "&7indossando nessun elmetto."
    else:
        set {whois.equip.helmet.%player%} to player's helmet
    if slot 38 of player's inventory is air:
        set {whois.equip.chestplate.%player%} to red stained glass pane named "&cSlot corazza" with lore "&6%player% &7non sta" and "&7indossando nessuna corazza."
    else:
        set {whois.equip.chestplate.%player%} to player's chestplate
    if slot 37 of player's inventory is air:
        set {whois.equip.leggings.%player%} to red stained glass pane named "&cSlot gambiere" with lore "&6%player% &7non sta" and "&7indossando gambiere."
    else:
        set {whois.equip.leggings.%player%} to player's leggings
    if slot 36 of player's inventory is air:
        set {whois.equip.boots.%player%} to red stained glass pane named "&cSlot stivali" with lore "&6%player% &7non sta" and "&7indossando stivali."
    else:
        set {whois.equip.boots.%player%} to player's boots

function OnlineWhoIsGUI(p: player, arg: player):
    set {_player_hp} to placeholder "auraskills_hp" from {_arg}
    set {_player_hp_max} to placeholder "auraskills_hp_max" from {_arg}
    set {_player_xp} to placeholder "player_current_exp" from {_arg}
    set {_player_xp_level} to placeholder "player_level" from {_arg}
    set {_player_x} to placeholder "player_x" from {_arg}
    set {_player_y} to placeholder "player_y" from {_arg}
    set {_player_z} to placeholder "player_z" from {_arg}
    set {_player_biome} to placeholder "player_biome_capitalized" from {_arg}
    set {_player_ip} to placeholder "player_ip" from {_arg}
    set {_player_op} to placeholder "player_is_op" from {_arg}
    set {_gamemode} to {@gamemode_gui_arg}
    set {_gamemode_id} to {@gamemode_id_arg}
    set metadata tag "OnlineWhoIsGUI" of {_p} to a new chest inventory with 5 rows named "&2| &rWhoIs: %{_arg}%"
    if {@gui_background} is true:
        set slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 37, 38, 39, 41, 42, 43 and 44 of metadata tag "OnlineWhoIsGUI" of {_p} to black stained glass pane named "&f"
        set slot 10, 13, 16, 19, 20, 22, 24, 25, 28, 29, 30, 31, 32, 33 and 34 of metadata tag "OnlineWhoIsGUI" of {_p} to gray stained glass pane named "&f"
    set slot 11 of metadata tag "OnlineWhoIsGUI" of {_p} to {_arg}'s skull named "&6Giocatore" with lore " &eNome&7: &f%{_arg}%", " &cUUID&7: &f%{_arg}'s uuid%", " &aSoprannome&7: &f%{nick.%{_arg}%}%", "&f", "{@lclick_info}" and "{@rclick_info}"
    set slot 12 of metadata tag "OnlineWhoIsGUI" of {_p} to potion of strong healing with nbt from {@no_flags} named "&6Energia" with lore " &cVita&7: &f%{_player_hp}%/%{_player_hp_max}%" and " &aFame&7: &f%{_arg}'s food level%/10"
    set slot 13 of metadata tag "OnlineWhoIsGUI" of {_p} to redstone torch named "&3Condizioni giocatore" with lore " &6OP&7: %{_player_op}%", " &6Volo&7: %{fly.%{_arg}%}%", " &6Immortale&7: %{god.%{_arg}%}%", " &6Velocità&7:", "  &ePasso&7: &f%{_arg}'s walkspeed%" and "  &eVolo&7: &f%{_arg}'s flyspeed%"
    set slot 14 of metadata tag "OnlineWhoIsGUI" of {_p} to {whois.world.marker.%{_arg}%} named "&6Posizione" with lore " &fMondo&7: %{whois.world.%{_arg}%}%", " &fCoordinate&7: &a%{_player_x}% %{_player_y}% %{_player_z}%", " &fBioma&7: &b%{_player_biome}%", "&f" and "{@click_teleport}"
    set slot 15 of metadata tag "OnlineWhoIsGUI" of {_p} to book named "&6Tempo di gioco" with lore " &aSessione&7: &f%{playtime.actual_session.days.%{_arg}%}% giorni, %{playtime.actual_session.hours.%{_arg}%}% ore, %{playtime.actual_session.minutes.%{_arg}%}% minuti e %{playtime.actual_session.seconds.%{_arg}%}% secondi", " &cTotale&7: &f%{playtime.total.days.%{_arg}%}% giorni, %{playtime.total.hours.%{_arg}%}% ore, %{playtime.total.minutes.%{_arg}%}% minuti e %{playtime.total.seconds.%{_arg}%}% secondi", "&f", " &eSessioni&7: &f%{playtime.sessions.%{_arg}%}%", "&f" and " &7Prima volta nel server&7: &f%{playtime.first_login.%{_arg}%}%"
    set slot 21 of metadata tag "OnlineWhoIsGUI" of {_p} to {_gamemode_id} named "&eInformazioni di gioco" with lore " &aModalità di gioco&7: %{_gamemode}%"
    set slot 23 of metadata tag "OnlineWhoIsGUI" of {_p} to writable book named "&cConnettività" with lore " &eIndirizzo IP&7: &f%{_player_ip}%" and " &6Ping&7: &f%{_arg}'s ping% ms"
    set slot 40 of metadata tag "OnlineWhoIsGUI" of {_p} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
    open metadata tag "OnlineWhoIsGUI" of {_p} to {_p}

function OfflineWhoIsGUI(p: player, arg: offline player):
    set {_player_hp} to placeholder "auraskills_hp" from {_arg}
    set {_player_hp_max} to placeholder "auraskills_hp_max" from {_arg}
    set {_player_xp} to placeholder "player_current_exp" from {_arg}
    set {_player_xp_level} to placeholder "player_level" from {_arg}
    set {_player_ip} to placeholder "player_ip" from {_arg}
    set {_player_op} to placeholder "player_is_op" from {_arg}
    set metadata tag "OfflineWhoIsGUI" of {_p} to a new chest inventory with 4 rows named "&4| &rWhoIs: %{_arg}%"
    if {@gui_background} is true:
        set slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43 and 44 of metadata tag "OfflineWhoIsGUI" of {_p} to black stained glass pane named "&f"
        set slot 10, 16, 19, 20, 21, 22, 23, 24 and 25 of metadata tag "OfflineWhoIsGUI" of {_p} to gray stained glass pane named "&f"
    set slot 11 of metadata tag "OfflineWhoIsGUI" of {_p} to {_arg}'s skull named "&6Giocatore" with lore " &eNome&7: &f%{_arg}%", " &cUUID&7: &f%{_arg}'s uuid%", " &aSoprannome&7: &f%{nick.%{_arg}%}%", "&f", "{@lclick_info}" and "{@rclick_info}"
    set slot 12 of metadata tag "OfflineWhoIsGUI" of {_p} to {gm.marker.%{_arg}%} named "&eInformazioni di gioco" with lore " &aModalità di gioco&7: %{gm.%{_arg}%}%"
    set slot 13 of metadata tag "OfflineWhoIsGUI" of {_p} to redstone torch named "&3Condizioni giocatore" with lore " &6OP&7: %{_player_op}%", " &6Volo&7: %{fly.%{_arg}%}%" and " &6Immortale&7: %{god.%{_arg}%}%"
    set slot 14 of metadata tag "OfflineWhoIsGUI" of {_p} to {whois.world.marker.%{_arg}%} named "&6Posizione" with lore " &fMondo&7: %{whois.world.%{_arg}%}%", " &fCoordinate&7: &a%{whois.position.x.%{_arg}%}% %{whois.position.y.%{_arg}%}% %{whois.position.z.%{_arg}%}%", " &fBioma&7: &b%{whois.position.biome.%{_arg}%}%", "&f" and "{@click_teleport}"
    set slot 15 of metadata tag "OfflineWhoIsGUI" of {_p} to book named "&6Tempo di gioco" with lore " &aSessione&7: &f%{playtime.last_session.days.%{_arg}%}% giorni, %{playtime.last_session.hours.%{_arg}%}% ore, %{playtime.last_session.minutes.%{_arg}%}% minuti e %{playtime.last_session.seconds.%{_arg}%}% secondi", " &cTotale&7: &f%{playtime.total.days.%{_arg}%}% giorni, %{playtime.total.hours.%{_arg}%}% ore, %{playtime.total.minutes.%{_arg}%}% minuti e %{playtime.total.seconds.%{_arg}%}% secondi", "&f", " &eSessioni&7: &f%{playtime.sessions.%{_arg}%}%", "&f", " &aPrima volta nel server&7: &f%{playtime.first_login.%{_arg}%}%" and " &cUltima volta online&7: &f%{playtime.last_seen.%{_arg}%}%"
    set slot 31 of metadata tag "OfflineWhoIsGUI" of {_p} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
    open metadata tag "OfflineWhoIsGUI" of {_p} to {_p}

function OnlinePlayersInformationGUI(p: player, arg: player):
    set {_player_hp} to placeholder "auraskills_hp" from {_arg}
    set {_player_hp_max} to placeholder "auraskills_hp_max" from {_arg}
    set {_player_xp} to placeholder "player_current_exp" from {_arg}
    set {_player_xp_level} to placeholder "player_level" from {_arg}
    set {_player_inventory} to placeholder "player_empty_slots" from {_arg}
    set {_player_x} to placeholder "player_x" from {_arg}
    set {_player_y} to placeholder "player_y" from {_arg}
    set {_player_z} to placeholder "player_z" from {_arg}
    set {_player_biome} to placeholder "player_biome_capitalized" from {_arg}
    set {_player_ip} to placeholder "player_ip" from {_arg}
    set {_player_op} to placeholder "player_is_op" from {_arg}
    set {_player_luck} to placeholder "auraskills_luck" from {_arg}
    set {_player_health} to placeholder "auraskills_health" from {_arg}
    set {_player_wisdom} to placeholder "auraskills_wisdom" from {_arg}
    set {_player_strength} to placeholder "auraskills_strength" from {_arg}
    set {_player_regeneration} to placeholder "auraskills_regeneration" from {_arg}
    set {_player_toughness} to placeholder "auraskills_toughness" from {_arg}
    set {_player_crit_chance} to placeholder "auraskills_crit_chance" from {_arg}
    set {_player_crit_damage} to placeholder "auraskills_crit_damage" from {_arg}
    set {_player_speed} to placeholder "auraskills_speed" from {_arg}
    set {_genre} to {@genre}
    set metadata tag "OnlinePlayersInformationGUI" of {_p} to a new chest inventory with 6 rows named "&2| &rProfilo di %{_arg}%"
    if {@gui_background} is true:
        set slot 0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of metadata tag "OnlinePlayersInformationGUI" of {_p} to black stained glass pane named "&r"
        set slot 10, 12, 13, 14, 22, 23, 27, 28, 30, 31, 32, 34, 37, 39, 40, 41, 42 and 43 of metadata tag "OnlinePlayersInformationGUI" of {_p} to gray stained glass pane named "&r"
    if {@genre} is "%{server.genre.male}%":
        set slot 4 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s head named "&9%{_arg}%" with lore "&7""%{status.%{_arg}%}%&7""", "&f", " &e➹ Bug segnalati&7: &f%{reported_bugs::%{_arg}%}%", " &6★ Feedback inviati&7: &f%{feedback_sent::%{_arg}%}%", "&f", " &a❉ EXP&7: &2%{_player_xp_level}% livelli (&a%regex({_player_xp})% punti&2)", "&f" and "&7Prima volta nel server: &f%{playtime.first_login.%{_arg}%}%"
    else if {@genre} is "%{server.genre.female}%":
        set slot 4 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s head named "&d%{_arg}%" with lore "&7""%{status.%{_arg}%}%&7""", "&f", " &e➹ Bug segnalati&7: &f%{reported_bugs::%{_arg}%}%", " &6★ Feedback inviati&7: &f%{feedback_sent::%{_arg}%}%", "&f", " &a❉ EXP&7: &2%{_player_xp_level}% livelli (&a%regex({_player_xp})% punti&2)", "&f" and "&7Prima volta nel server: &f%{playtime.first_login.%{_arg}%}%"
    if slot 39 of {_arg}'s inventory is air:
        set slot 11 of metadata tag "OnlinePlayersInformationGUI" of {_p} to red stained glass pane named "&cSlot elmetto" with lore "&6%{_arg}% &7non sta" and "&7indossando nessun elmetto."
    else:
        set slot 11 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s helmet
    if slot 38 of {_arg}'s inventory is air:
        set slot 20 of metadata tag "OnlinePlayersInformationGUI" of {_p} to red stained glass pane named "&cSlot corazza" with lore "&6%{_arg}% &7non sta" and "&7indossando nessuna corazza."
    else:
        set slot 20 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s chestplate
    if slot 37 of {_arg}'s inventory is air:
        set slot 29 of metadata tag "OnlinePlayersInformationGUI" of {_p} to red stained glass pane named "&cSlot gambiere" with lore "&6%{_arg}% &7non sta" and "&7indossando gambiere."
    else:
        set slot 29 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s leggings
    if slot 36 of {_arg}'s inventory is air:
        set slot 38 of metadata tag "OnlinePlayersInformationGUI" of {_p} to red stained glass pane named "&cSlot stivali" with lore "&6%{_arg}% &7non sta" and "&7indossando stivali."
    else:
        set slot 38 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s boots
    if slot 40 of {_arg}'s inventory is air:
        set slot 19 of metadata tag "OnlinePlayersInformationGUI" of {_p} to magenta stained glass pane named "&dMano secondaria" with lore "&6%{_arg}% &7non ha" and "&7oggetti nella seconda mano."
    else:
        set slot 19 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s off hand item
    if {_arg}'s tool is air:
        set slot 21 of metadata tag "OnlinePlayersInformationGUI" of {_p} to lime stained glass pane named "&aMano principale" with lore "&6%{_arg}% &7non ha" and "&7nulla in mano."
    else:
        set slot 21 of metadata tag "OnlinePlayersInformationGUI" of {_p} to {_arg}'s held item
    set slot 15 of metadata tag "OnlinePlayersInformationGUI" of {_p} to writable book named "&bInformazioni generali" with lore " &9✎ Nome&7: &f%{_arg}%", " &6✎ Soprannome&7: &f%{nick.%{_arg}%}%", " &a✧ Sesso&7: &f%{_genre}%", " &e₪ Inventario&7: &f%{_player_inventory}%/35 slot liberi", " &b🌅 Bioma&7: &f%{_player_biome}%", " &3ℹ Ping&7: &f%{_arg}'s ping% ms", " &d✦ Fama&7: &f%regex({fame::%{_arg}%})%", " &a✪ Reputazione&7: &f%{rank.%{_arg}%}%", " &2☘ Fortuna&7: &f+%{_player_luck}%", " &c❣ &cIncremento salute&7: &f+%{_player_health}%", " &9✿ Saggezza&7: &f+%{_player_wisdom}%" and " &f➤ Velocità&7: &f+%{_player_speed}%"
    set slot 16 of metadata tag "OnlinePlayersInformationGUI" of {_p} to diamond sword with nbt from {@no_flags} named "&aStatistiche sanguinarie" with lore " &c🗡 Uccisioni&7: &f%regex({kills::%{_arg}%})%", " &c☠ Morti&7: &f%regex({deaths::%{_arg}%})%", " &c🔥 Rapporto U/M&7: &f%regex({kills::%{_arg}%}/{deaths::%{_arg}%})%", " &6🗡 Danni inflitti&7: &f%regex({infldamage::%{_arg}%})%", " &6☄ Danni subiti&7: &f%regex({suffdamage::%{_arg}%})%", " &e&l⚡ &eSerie di uccisioni&7: &f%regex({killstreak::%{_arg}%})%/%regex({killstreak_max.%{_arg}%})%", " &4➽ Forza&7: &f+%{_player_strength}%", " &6❥ Rigenerazione&7: &f+%{_player_regeneration}%", " &5✦ Resistenza&7: &f+%{_player_toughness}%", " &a⌘ Probabilità Colpo Critico&7: &f+%{_player_crit_chance}%%%" and " &3★ Danno Colpo Critico&7: &f+%{_player_crit_damage}%%%"
    set slot 24 of metadata tag "OnlinePlayersInformationGUI" of {_p} to iron pickaxe with nbt from {@no_flags} named "&aStatistiche minerarie" with lore " &c⛏ Blocchi distrutti&7: &f%regex({broken_blocks::%{_arg}%})%" and " &b🔨 Blocchi piazzati&7: &f%regex({placed_blocks::%{_arg}%})%"
    set slot 25 of metadata tag "OnlinePlayersInformationGUI" of {_p} to sunflower with nbt from {@glinted} named "&eMedaglie" with lore " &6۞ Ottenute&7: &f%{medals.%{_arg}%}%" and " &e✪ Ultima ottenuta&7: &f%{medals.%{_arg}%.last_obtained}%"
    set slot 48 of metadata tag "OnlinePlayersInformationGUI" of {_p} to arrow named "&aIndietro" with lore "&7Torna a WhoIs: %{_arg}%"
    set slot 49 of metadata tag "OnlinePlayersInformationGUI" of {_p} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
    open metadata tag "OnlinePlayersInformationGUI" of {_p} to {_p}

function OfflinePlayersInformationGUI(p: player, arg: offline player):
    set {_genre} to {@genre}
    set metadata tag "OfflinePlayersInformationGUI" of {_p} to a new chest inventory with 6 rows named "&4| &rProfilo di %{_arg}%"
    if {@gui_background} is true:
        set slot 0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of metadata tag "OfflinePlayersInformationGUI" of {_p} to black stained glass pane named "&r"
        set slot 10, 12, 13, 14, 22, 23, 27, 28, 30, 31, 32, 34, 37, 39, 40, 41, 42 and 43 of metadata tag "OfflinePlayersInformationGUI" of {_p} to gray stained glass pane named "&r"
    if {@genre} is "%{server.genre.male}%":
        set slot 4 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {_arg}'s head named "&9%{_arg}% &4[OFFLINE]" with lore "&7""%{status.%{_arg}%}%&7""", "&f", " &e➹ Bug segnalati&7: &f%{reported_bugs::%{_arg}%}%", " &6★ Feedback inviati&7: &f%{feedback_sent::%{_arg}%}%", "&f", " &a❉ EXP&7: &2%{whois.offline.xp_level.%{_arg}%}% livelli (&a%regex({whois.offline.xp.%{_arg}%})% punti&2)", "&f" and "&7Prima volta nel server: &f%{playtime.first_login.%{_arg}%}%"
    else if {@genre} is "%{server.genre.female}%":
        set slot 4 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {_arg}'s head named "&d%{_arg}% &4[OFFLINE]" with lore "&7""%{status.%{_arg}%}%&7""", "&f", " &e➹ Bug segnalati&7: &f%{reported_bugs::%{_arg}%}%", " &6★ Feedback inviati&7: &f%{feedback_sent::%{_arg}%}%", "&f", " &a❉ EXP&7: &2%{whois.offline.xp_level.%{_arg}%}% livelli (&a%regex({whois.offline.xp.%{_arg}%})% punti&2)", "&f" and "&7Prima volta nel server: &f%{playtime.first_login.%{_arg}%}%"
    set slot 11 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {equip.%{_arg}%.helmet}
    set slot 20 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {equip.%{_arg}%.chestplate}
    set slot 29 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {equip.%{_arg}%.leggings}
    set slot 38 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {equip.%{_arg}%.boots}
    set slot 19 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {equip.%{_arg}%.offhand}
    set slot 21 of metadata tag "OfflinePlayersInformationGUI" of {_p} to {equip.%{_arg}%.mainhand}
    set slot 15 of metadata tag "OfflinePlayersInformationGUI" of {_p} to writable book named "&bInformazioni generali" with lore " &9✎ Nome&7: &f%{_arg}%", " &6✎ Soprannome&7: &f%{nick.%{_arg}%}%", " &a✧ Sesso&7: &f%{_genre}%", " &e₪ Inventario&7: &f%{whois.offline.empty_slots.%{_arg}%}%/35 slot liberi", " &b🌅 Bioma&7: &f%{whois.position.biome.%{_arg}%}%", " &d✦ Fama&7: &f%regex({fame::%{_arg}%})%", " &a✪ Reputazione&7: &f%{rank.%{_arg}%}%", " &2☘ Fortuna&7: &f+%{whois.offline.luck.%{_arg}%}%", " &c❣ Incremento salute&7: &f+%{whois.offline.health.%{_arg}%}%", " &9✿ Saggezza&7: &f+%{whois.offline.wisdom.%{_arg}%}%" and " &f➤ Velocità&7: &f+%{whois.offline.speed.%{_arg}%}%"
    set slot 16 of metadata tag "OfflinePlayersInformationGUI" of {_p} to diamond sword with nbt from {@no_flags} named "&aStatistiche sanguinarie" with lore " &c🗡 Uccisioni&7: &f%regex({kills::%{_arg}%})%", " &c☠ Morti&7: &f%regex({deaths::%{_arg}%})%", " &c🔥 Rapporto U/M&7: &f%regex({kills::%{_arg}%}/{deaths::%{_arg}%})%", " &6🗡 Danni inflitti&7: &f%regex({infldamage::%{_arg}%})%", " &6☄ Danni subiti&7: &f%regex({suffdamage::%{_arg}%})%", " &e&l⚡ &eSerie di uccisioni&7: &f%regex({killstreak::%{_arg}%})%/%regex({killstreak_max.%{_arg}%})%", " &4➽ Forza&7: &f+%{whois.offline.strength.%{_arg}%}%", " &6❥ Rigenerazione&7: &f+%{whois.offline.regeneration.%{_arg}%}%", " &5✦ Resistenza&7: &f+%{whois.offline.toughness.%{_arg}%}%", " &a⌘ Probabilità Colpo Critico&7: &f+%{whois.offline.crit_chance.%{_arg}%}%%%" and " &3★ Danno Colpo Critico&7: &f+%{whois.offline.crit_damage.%{_arg}%}%%%"
    set slot 24 of metadata tag "OfflinePlayersInformationGUI" of {_p} to iron pickaxe with nbt from {@no_flags} named "&aStatistiche minerarie" with lore " &c⛏ Blocchi distrutti&7: &f%regex({broken_blocks::%{_arg}%})%" and " &b🔨 Blocchi piazzati&7: &f%regex({placed_blocks::%{_arg}%})%"
    set slot 25 of metadata tag "OfflinePlayersInformationGUI" of {_p} to sunflower with nbt from {@glinted} named "&eMedaglie" with lore " &6۞ Ottenute&7: &f%{medals.%{_arg}%}%" and " &e✪ Ultima ottenuta&7: &f%{medals.%{_arg}%.last_obtained}%"
    set slot 48 of metadata tag "OfflinePlayersInformationGUI" of {_p} to arrow named "&aIndietro" with lore "&7Torna a WhoIs: %{_arg}%"
    set slot 49 of metadata tag "OfflinePlayersInformationGUI" of {_p} to barrier named "&cChiudi" with lore "&7Torna alla %{server.name}%"
    open metadata tag "OfflinePlayersInformationGUI" of {_p} to {_p}
        
on inventory click:
    if event-inventory is metadata tag "OnlineWhoIsGUI" of player:
        if type of event-inventory is chest inventory:
            if index of event-slot isn't 11, 14 or 40:
                cancel event
            else if index of event-slot is 11:
                if click type is left mouse button:
                    cancel event
                    if {whois.%player%.arg} is offline:
                        OfflinePlayersInformationGUI(player,{whois.%player%.arg})
                    else:
                        OnlinePlayersInformationGUI(player,{whois.%player%.arg})
                else if click type is right mouse button:
                    cancel event
                    close player's inventory
                    send formatted "%{server.prefix.main}% &aClicca <ttp:UUID di %{whois.%player%.arg}%><url:https://it.namemc.com/profile/%{whois.%player%.arg}'s uuid%>&b&nqui&r &aper visitare il sito di NameMC." to player
                    play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
                else:
                    cancel event
            else if index of event-slot is 14:
                if click type is left mouse button:
                    cancel event
                    execute player command "/teleport %{whois.%player%.arg}%"
                    close player's inventory
                else:
                    cancel event
            else if index of event-slot is 40:
                if click type is left mouse button:
                    cancel event
                    close player's inventory
                else:
                    cancel event
    else if event-inventory is metadata tag "OfflineWhoIsGUI" of player:
        if type of event-inventory is chest inventory:
            if index of event-slot isn't 11, 14 or 31:
                cancel event
            else if index of event-slot is 11:
                if click type is left mouse button:
                    cancel event
                    if {whois.%player%.arg} is offline:
                        OfflinePlayersInformationGUI(player,{whois.%player%.arg})
                    else:
                        OnlinePlayersInformationGUI(player,{whois.%player%.arg})
                else if click type is right mouse button:
                    cancel event
                    close player's inventory
                    send formatted "%{server.prefix.main}% &aClicca <ttp:UUID di %{whois.%player%.arg}%><url:https://it.namemc.com/profile/%{whois.%player%.arg}'s uuid%>&b&nqui&r &aper visitare il sito di NameMC." to player
                    play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
                else:
                    cancel event
            else if index of event-slot is 14:
                if click type is left mouse button:
                    cancel event
                    execute player command "/tpoffline %{whois.%player%.arg}%"
                    close player's inventory
                else:
                    cancel event
            else if index of event-slot is 31:
                if click type is left mouse button:
                    cancel event
                    close player's inventory
                else:
                    cancel event
    else if event-inventory is metadata tag "OnlinePlayersInformationGUI" of player:
        if type of event-inventory is chest inventory:
            if index of event-slot isn't 48 or 49:
                cancel event
            else if index of event-slot is 48:
                if click type is left mouse button:
                    cancel event
                    if {whois.%player%.arg} is offline:
                        OfflineWhoIsGUI(player,{whois.%player%.arg})
                    else:
                        OnlineWhoIsGUI(player,{whois.%player%.arg})
                else:
                    cancel event
            else if index of event-slot is 49:
                if click type is left mouse button:
                    cancel event
                    close player's inventory
                else:
                    cancel event
    else if event-inventory is metadata tag "OfflinePlayersInformationGUI" of player:
        if type of event-inventory is chest inventory:
            if index of event-slot isn't 48 or 49:
                cancel event
            else if index of event-slot is 48:
                if click type is left mouse button:
                    cancel event
                    if {whois.%player%.arg} is offline:
                        OfflineWhoIsGUI(player,{whois.%player%.arg})
                    else:
                        OnlineWhoIsGUI(player,{whois.%player%.arg})
                else:
                    cancel event
            else if index of event-slot is 49:
                if click type is left mouse button:
                    cancel event
                    close player's inventory
                else:
                    cancel event