options:
 # GENERALI
    prefix: &6[&e&lAnti-Xray&6]
    enabled: &aATTIVATO
    disabled: &cDISATTIVATO
 # SUONI
    confirm_sound: block.note_block.pling
    error_sound: entity.enderman.teleport
    check_sound: entity.player.levelup

function openAXRsettings(p: player):
   if {settings::%{_p}%::glasspanes} is true:
      if {counter::status} is "{@disabled}":
         if {autoalerts::status} is "{@disabled}":
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
         else:
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
      else:
         if {autoalerts::status} is "{@disabled}":
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
         else:
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 0, 1, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
               set slot 19, 22, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
   else:
      if {counter::status} is "{@disabled}":
         if {autoalerts::status} is "{@disabled}":
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
         else:
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai", "&7giocatori, aiutando gli admin a capire", "&7i progressi di un determinato giocatore.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
      else:
         if {autoalerts::status} is "{@disabled}":
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico", "&7dei minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &cdisattivato&3.", "&f" and "&eClicca per attivarlo."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
         else:
            if {consolenotify::status} is "{@disabled}":
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare", "&7le notifiche degli avvisi anche", "&7nella console del server.", "&f", "&3Attualmente sono &cdisattivate&3.", "&f" and "&eClicca per attivarle."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
            else:
               set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &9Impostazioni"
               set slot 2 of {_gui} to oak sign named "&fMenu principale" with lore "&7Torna al menu principale dell'Anti-Xray."
               set slot 3 of {_gui} to book named "&6Notifiche" with lore "&7Gestisci le notifiche degli avvisi dei giocatori,", "&7compresi quelli di quando non eri online sul" and "&7server."
               set slot 4 of {_gui} to diamond named "&dGestione minerali" with lore "&7Attiva o disattiva gli avvisi dei minerali e", "&7gestisci i minerali scavati di un giocatore."
               set slot 5 of {_gui} to redstone torch named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per" and "&7la rottura tra un minerale e un altro."
               set slot 6 of {_gui} to grass block named "&aMondi" with lore "&7Gestisci i mondi per cui l'Anti-Xray debba", "&7tenere sotto controllo i giocatori.", "&f", "&3Mondi abilitati:", " &b%{axr_worlds::*}%", "&f", and "&eClicca per vedere i mondi disponibili."
               set slot 9, 10, 11, 12, 13, 15, 16 and 17 of {_gui} to orange stained glass pane named "&f"
               set slot 14 of {_gui} to yellow stained glass pane named "&f"
               set slot 20 of {_gui} to clock named "&cTimer" with lore "&7Modifica l'intervallo di tempo (in secondi) per cui", "&7l'Anti-Xray debba controllare i minerali scavati", "&7dai giocatori in modo da agire in tempo, se", "&7necessario.", "&f", "&3Attualmente il timer è di &a%{timer}% secondi&3.", "&f" and "&eClicca per modificare il timer."
               set slot 21 of {_gui} to oak sign with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&bContatore minerali" with lore "&7Tiene conto dei minerali scavati dai giocatori, aiutando gli", "&7admin a capire i progressi di un determinato giocatore", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il contatore dei minerali, l'Anti-Xray non", "&cterrà più conto dei minerali scavati dai giocatori", "&ce, pertanto, gli admin non saranno più in grado di", "&ccontrollarne i progressi."
               set slot 23 of {_gui} to iron bars with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6Riconoscimento automatico" with lore "&7Attiva o disattiva il riconoscimento automatico dei", "&7minerali e la ricezione delle notifiche.", "&f", "&3Attualmente è &aattivato&3.", "&f", "&eClicca per disattivarlo.", "&f", "&4&lATTENZIONE!", "&cDisattivando il riconoscimento automatico, l'Anti-Xray", "&cnon sarà più in grado di punire in modo automatico", "&ci giocatori che utilizzano l'Xray, permettendo loro" and "&cdi passarla liscia in assenza di admin sul server."
               set slot 24 of {_gui} to ender eye with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&9Notifiche in console" with lore "&7Decidi se l'Anti-Xray debba inviare le", "&7notifiche degli avvisi anche nella console", "&7del server.", "&f", "&3Attualmente sono &aattivate&3.", "&f", "&eClicca per disattivarle.", "&f", "&4&lATTENZIONE!", "&cDisattivando gli avvisi in console, l'Anti-Xray", "&cnon invierà più notifiche alla console del", "&cserver, inviandole soltanto agli admin che" and "&csono online sul server."
               set slot 30 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
               set slot 32 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
               set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
               open {_gui} to {_p}
function openAXRsettingsOverworldMain(p: player):
   if {settings::%{_p}%::glasspanes} is true:
      if {axr::counter} is not set:
         send "{@prefix} &cQuesta pagina non è disponibile se il contatore dei minerali è disattivato." to {_p}
         play sound "{@error_sound}" with volume 1 and pitch 0 at {_p} for {_p}
      else:
         set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &2Overworld"
         set slot 0, 1, 2, 4, 6, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
         set slot 19, 20, 21, 22, 23, 24, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
         set slot 9, 11, 13, 15 and 17 of {_gui} to lime stained glass pane named "&f"
         set slot 10, 12, 14 and 16 of {_gui} to light blue stained glass pane named "&f"
         set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
         set slot 5 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
         set slot 30 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&bConfigurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin", "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 32 of {_gui} to clock named "&bConfigurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
         open {_gui} to {_p}
   else:
      if {axr::counter} is not set:
         send "{@prefix} &cQuesta pagina non è disponibile se il contatore dei minerali è disattivato." to {_p}
         play sound "{@error_sound}" with volume 1 and pitch 0 at {_p} for {_p}
      else:
         set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &2Overworld"
         set slot 9, 11, 13, 15 and 17 of {_gui} to lime stained glass pane named "&f"
         set slot 10, 12, 14 and 16 of {_gui} to light blue stained glass pane named "&f"
         set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
         set slot 5 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
         set slot 30 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&bConfigurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin", "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 32 of {_gui} to clock named "&bConfigurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
         open {_gui} to {_p}
function openAXRsettingsOverworldManual(p: player):
   if {settings::%{_p}%::glasspanes} is true:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &2Config. manuale"
      set slot 0, 1, 2, 6, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
      set slot 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
      set slot 9, 11, 13, 15 and 17 of {_gui} to light blue stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to lime stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&bConfigurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin" and "&7di eventuali giocatori con l'Xray."
      set slot 5 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
      set slot 19 of {_gui} to iron ore named "&fFerro" with lore "&3Hai %{alert_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 20 of {_gui} to copper ore named "&dRame" with lore "&3Hai %{alert_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 21 of {_gui} to gold ore named "&eOro" with lore "&3Hai %{alert_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 22 of {_gui} to redstone ore named "&cRedstone" with lore "&3Hai %{alert_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 23 of {_gui} to lapis ore named "&9Lapislazzuli" with lore "&3Hai %{alert_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 24 of {_gui} to emerald ore named "&aSmeraldo" with lore "&3Hai %{alert_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 25 of {_gui} to diamond ore named "&bDiamante" with lore "&3Hai %{alert_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 28 of {_gui} to deepslate iron ore named "&fFerro in ardesia profonda" with lore "&3Hai %{alert_deepslate_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 29 of {_gui} to deepslate copper ore named "&dRame in ardesia profonda" with lore "&3Hai %{alert_deepslate_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 30 of {_gui} to deepslate gold ore named "&eOro in ardesia profonda" with lore "&3Hai %{alert_deepslate_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to deepslate redstone ore named "&cRedstone in ardesia profonda" with lore "&3Hai %{alert_deepslate_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to deepslate lapis ore named "&9Lapislazzuli in ardesia profonda" with lore "&3Hai %{alert_deepslate_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 33 of {_gui} to deepslate emerald ore named "&aSmeraldo in ardesia profonda" with lore "&3Hai %{alert_deepslate_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 34 of {_gui} to deepslate diamond ore named "&bDiamante in ardesia profonda" with lore "&3Hai %{alert_deepslate_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to clock named "&bConfigurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per passare alla configurazione", "&eautomatica."
      open {_gui} to {_p}
   else:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &2Config. manuale"
      set slot 9, 11, 13, 15 and 17 of {_gui} to light blue stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to lime stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&bConfigurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin" and "&7di eventuali giocatori con l'Xray."
      set slot 5 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
      set slot 19 of {_gui} to iron ore named "&fFerro" with lore "&3Hai %{alert_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 20 of {_gui} to copper ore named "&dRame" with lore "&3Hai %{alert_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 21 of {_gui} to gold ore named "&eOro" with lore "&3Hai %{alert_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 22 of {_gui} to redstone ore named "&cRedstone" with lore "&3Hai %{alert_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 23 of {_gui} to lapis ore named "&9Lapislazzuli" with lore "&3Hai %{alert_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 24 of {_gui} to emerald ore named "&aSmeraldo" with lore "&3Hai %{alert_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 25 of {_gui} to diamond ore named "&bDiamante" with lore "&3Hai %{alert_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 28 of {_gui} to deepslate iron ore named "&fFerro in ardesia profonda" with lore "&3Hai %{alert_deepslate_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 29 of {_gui} to deepslate copper ore named "&dRame in ardesia profonda" with lore "&3Hai %{alert_deepslate_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 30 of {_gui} to deepslate gold ore named "&eOro in ardesia profonda" with lore "&3Hai %{alert_deepslate_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to deepslate redstone ore named "&cRedstone in ardesia profonda" with lore "&3Hai %{alert_deepslate_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to deepslate lapis ore named "&9Lapislazzuli in ardesia profonda" with lore "&3Hai %{alert_deepslate_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 33 of {_gui} to deepslate emerald ore named "&aSmeraldo in ardesia profonda" with lore "&3Hai %{alert_deepslate_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 34 of {_gui} to deepslate diamond ore named "&bDiamante in ardesia profonda" with lore "&3Hai %{alert_deepslate_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{deepslate_diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to clock named "&bConfigurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per passare alla configurazione", "&eautomatica."
      open {_gui} to {_p}
function openAXRsettingsOverworldAutomatic(p: player):
   if {settings::%{_p}%::glasspanes} is true:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &2Config. automatica"
      set slot 0, 1, 2, 6, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
      set slot 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
      set slot 9, 11, 13, 15 and 17 of {_gui} to light blue stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to lime stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to clock named "&bConfigurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori" and "&7che stanno utilizzando l'Xray."
      set slot 5 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
      set slot 19 of {_gui} to iron ore named "&fFerro" with lore "&3Hai %{autoalert_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 20 of {_gui} to copper ore named "&dRame" with lore "&3Hai %{autoalert_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 21 of {_gui} to gold ore named "&eOro" with lore "&3Hai %{autoalert_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 22 of {_gui} to redstone ore named "&cRedstone" with lore "&3Hai %{autoalert_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 23 of {_gui} to lapis ore named "&9Lapislazzuli" with lore "&3Hai %{autoalert_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 24 of {_gui} to emerald ore named "&aSmeraldo" with lore "&3Hai %{autoalert_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 25 of {_gui} to diamond ore named "&bDiamante" with lore "&3Hai %{autoalert_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 28 of {_gui} to deepslate iron ore named "&fFerro in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 29 of {_gui} to deepslate copper ore named "&dRame in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 30 of {_gui} to deepslate gold ore named "&eOro in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to deepslate redstone ore named "&cRedstone in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to deepslate lapis ore named "&9Lapislazzuli in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 33 of {_gui} to deepslate emerald ore named "&aSmeraldo in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 34 of {_gui} to deepslate diamond ore named "&bDiamante in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&bConfigurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin", "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per passare alla configurazione", "&emanuale."
      open {_gui} to {_p}
   else:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &2Config. automatica"
      set slot 9, 11, 13, 15 and 17 of {_gui} to light blue stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to lime stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to clock named "&bConfigurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori" and "&7che stanno utilizzando l'Xray."
      set slot 5 of {_gui} to grass block named "&aOverworld" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali dell'Overworld."
      set slot 19 of {_gui} to iron ore named "&fFerro" with lore "&3Hai %{autoalert_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 20 of {_gui} to copper ore named "&dRame" with lore "&3Hai %{autoalert_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 21 of {_gui} to gold ore named "&eOro" with lore "&3Hai %{autoalert_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 22 of {_gui} to redstone ore named "&cRedstone" with lore "&3Hai %{autoalert_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 23 of {_gui} to lapis ore named "&9Lapislazzuli" with lore "&3Hai %{autoalert_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 24 of {_gui} to emerald ore named "&aSmeraldo" with lore "&3Hai %{autoalert_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 25 of {_gui} to diamond ore named "&bDiamante" with lore "&3Hai %{autoalert_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 28 of {_gui} to deepslate iron ore named "&fFerro in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_iron::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_iron_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 29 of {_gui} to deepslate copper ore named "&dRame in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_copper::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_copper_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 30 of {_gui} to deepslate gold ore named "&eOro in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_gold::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to deepslate redstone ore named "&cRedstone in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_redstone::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_redstone_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to deepslate lapis ore named "&9Lapislazzuli in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_lapis::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_lapis_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 33 of {_gui} to deepslate emerald ore named "&aSmeraldo in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_emerald::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_emerald_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 34 of {_gui} to deepslate diamond ore named "&bDiamante in ardesia profonda" with lore "&3Hai %{autoalert_deepslate_diamond::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_deepslate_diamond_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &2%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&bConfigurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin", "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per passare alla configurazione", "&emanuale."
      open {_gui} to {_p}
function openAXRsettingsNetherMain(p: player):
   if {settings::%{_p}%::glasspanes} is true:
      if {axr::counter} is not set:
         send "{@prefix} &cQuesta pagina non è disponibile se il contatore dei minerali è disattivato." to {_p}
         play sound "{@error_sound}" with volume 1 and pitch 0 at {_p} for {_p}
      else:
         set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &4Nether"
         set slot 0, 1, 2, 4, 6, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
         set slot 19, 20, 21, 22, 23, 24, 25, 28, 29, 31, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
         set slot 9, 11, 13, 15 and 17 of {_gui} to red stained glass pane named "&f"
         set slot 10, 12, 14 and 16 of {_gui} to orange stained glass pane named "&f"
         set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
         set slot 5 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
         set slot 30 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&6Configurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin", "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 32 of {_gui} to clock named "&6Configurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
         open {_gui} to {_p}
   else:
      if {axr::counter} is not set:
         send "{@prefix} &cQuesta pagina non è disponibile se il contatore dei minerali è disattivato." to {_p}
         play sound "{@error_sound}" with volume 1 and pitch 0 at {_p} for {_p}
      else:
         set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &4Nether"
         set slot 9, 11, 13, 15 and 17 of {_gui} to red stained glass pane named "&f"
         set slot 10, 12, 14 and 16 of {_gui} to orange stained glass pane named "&f"
         set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
         set slot 5 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
         set slot 30 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&bConfigurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin", "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 32 of {_gui} to clock named "&bConfigurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per gestire il configuratore."
         set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
         open {_gui} to {_p}
function openAXRsettingsNetherManual(p: player):
   if {settings::%{_p}%::glasspanes} is true:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &4Config. manuale"
      set slot 0, 1, 2, 6, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
      set slot 19, 20, 21, 22, 23, 24, 25, 28, 29, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
      set slot 9, 11, 13, 15 and 17 of {_gui} to orange stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to red stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&6Configurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin" and "&7di eventuali giocatori con l'Xray."
      set slot 5 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
      set slot 30 of {_gui} to nether quartz ore named "&fQuarzo del Nether" with lore "&3Hai %{alert_nether_quartz_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{nether_quartz_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to nether gold ore named "&6Oro del Nether" with lore "&3Hai %{alert_nether_gold_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{nether_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to ancient debris named "&fDetriti antichi" with lore "&3Hai %{alert_ancient_debris::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{ancient_debris_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to clock named "&6Configurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per passare alla configurazione", "&eautomatica."
      open {_gui} to {_p}
   else:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &4Config. manuale"
      set slot 9, 11, 13, 15 and 17 of {_gui} to orange stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to red stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&6Configurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin" and "&7di eventuali giocatori con l'Xray."
      set slot 5 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
      set slot 30 of {_gui} to nether quartz ore named "&fQuarzo del Nether" with lore "&3Hai %{alert_nether_quartz_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{nether_quartz_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to nether gold ore named "&6Oro del Nether" with lore "&3Hai %{alert_nether_gold_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{nether_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to ancient debris named "&fDetriti antichi" with lore "&3Hai %{alert_ancient_debris::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{ancient_debris_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to clock named "&6Configurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray.", "&f", "&eClicca per passare alla configurazione", "&eautomatica."
      open {_gui} to {_p}
function openAXRsettingsNetherAutomatic(p: player):
   if {settings::%{_p}%::glasspanes} is true:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &4Config. automatica"
      set slot 0, 1, 2, 6, 7, 8, 18, 26, 27, 35, 36, 44, 45, 46, 47, 51, 52 and 53 of {_gui} to black stained glass pane named "&f"
      set slot 19, 20, 21, 22, 23, 24, 25, 28, 29, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&f"
      set slot 9, 11, 13, 15 and 17 of {_gui} to orange stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to red stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to clock named "&6Configurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray."
      set slot 5 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
      set slot 30 of {_gui} to nether quartz ore named "&fQuarzo del Nether" with lore "&3Hai %{autoalert_nether_quartz_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_nether_quartz_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to nether gold ore named "&6Oro del Nether" with lore "&3Hai %{autoalert_nether_gold_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_nether_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to ancient debris named "&fDetriti antichi" with lore "&3Hai %{autoalert_ancient_debris::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_ancient_debris_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&6Configurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin" and "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per passare alla configurazione", "&eautomatica."
      open {_gui} to {_p}
   else:
      set {_gui} to a new chest inventory with 6 rows named "Anti-Xray: &4Config. automatica"
      set slot 9, 11, 13, 15 and 17 of {_gui} to orange stained glass pane named "&f"
      set slot 10, 12, 14 and 16 of {_gui} to red stained glass pane named "&f"
      set slot 3 of {_gui} to redstone torch with nbt compound from "{HideFlags:1,Enchantments:[{id:""minecraft:unbreaking"",lvl:1s}]}" named "&6&l> &e&lImpostazioni &6&l<" with lore "&7Gestisci le impostazioni degli avvisi sui", "&7minerali e modifica il tempo minimo per", "&7la rottura tra un minerale e un altro.", "&f" and "&eClicca per tornare in questa pagina."
      set slot 4 of {_gui} to clock named "&6Configurazione automatica" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e fa sì che il sistema agisca", "&7automaticamente per punire i giocatori", "&7che stanno utilizzando l'Xray."
      set slot 5 of {_gui} to netherrack named "&cNether" with lore "&7Gestisci e controlla l'Anti-Xray per" and "&7i minerali del Nether."
      set slot 30 of {_gui} to nether quartz ore named "&fQuarzo del Nether" with lore "&3Hai %{autoalert_nether_quartz_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_nether_quartz_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 31 of {_gui} to nether gold ore named "&6Oro del Nether" with lore "&3Hai %{autoalert_nether_gold_ore::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_nether_gold_ore_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 32 of {_gui} to ancient debris named "&fDetriti antichi" with lore "&3Hai %{autoalert_ancient_debris::status}% &3gli avvisi per questo minerale.", "&f", "&7I giocatori possono scavare &6%{detect_ancient_debris_mined_in_x_sec}% blocchi", "&7entro un massimo di &c%{timer}% secondi.", "&f" and "&eClicca per modificare la quantità."
      set slot 48 of {_gui} to paper named "&cRipristina predefiniti" with lore "&7Reimposta i valori predefiniti di" and "&7tutti i minerali."
      set slot 49 of {_gui} to comparator named "&aIndietro" with lore "&7Torna a Gestione Server"
      set slot 50 of {_gui} to diamond pickaxe with nbt compound from "{HideFlags:2}" named "&6Configurazione manuale" with lore "&7Gestisci la quantità dei minerali scavati", "&7consentita e il lasso di tempo tra un", "&7minerale e un altro.", "&f", "&7Questa configurazione include tutti i", "&7minerali e serve per avvisare gli admin" and "&7di eventuali giocatori con l'Xray.", "&f", "&eClicca per passare alla configurazione", "&eautomatica."
      open {_gui} to {_p}
on inventory click:
   if name of event-inventory is "Anti-Xray: &9Impostazioni":
      if index of event-slot is 0, 1, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52 or 53:
         cancel event
      else if index of event-slot is 2:
         cancel event
         openAXRmain(player)
      else if index of event-slot is 3:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 4:
         cancel event
         openAXRcounter(player)
      else if index of event-slot is 5:
         cancel event
         send "{@prefix} &cSei già su ""&eImpostazioni&c""!"
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 6:
         cancel event
         openAXRworlds(player)
      else if index of event-slot is 20:
         cancel event
         close player's inventory
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         if {axr::alerts} is not set:
            send "{@prefix} &cGli avvisi minerali sono disabilitati!"
            send "{@prefix} &6Abilitali con &e/axr ore alerts all&6."
            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
         else if {axr::alerts} is true:
            send "{@prefix} &7Il timer è utilizzato per gli &6avvisi minerali &7e &6riconoscimento automatico&7."
            wait 2 ticks
            send "{@prefix} &cDigita la durata del timer in chat &6(Attualmente è impostato a &e%{timer}% secondi&6)."
            set {timeset::%player%} to true
         else if {axr::alerts} is false:
            send "{@prefix} &cGli avvisi minerali sono disabilitati!"
            send "{@prefix} &6Abilitali con &e/axr ore alerts all&6."
            play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 21:
         cancel event
         execute player command "/axr settings counter"
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         openAXRsettings(player)
      else if index of event-slot is 23:
         cancel event
         execute player command "/axr settings alerts autocheck"
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         openAXRsettings(player)
      else if index of event-slot is 24:
         cancel event
         execute player command "/axr settings alerts console"
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         openAXRsettings(player)
      else if index of event-slot is 30:
         cancel event
         openAXRsettingsOverworldMain(player)
      else if index of event-slot is 32:
         cancel event
         openAXRsettingsNetherMain(player)
      else if index of event-slot is 49:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
   else if name of event-inventory is "Anti-Xray: &2Overworld":
      if index of event-slot is 0, 1, 2, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52 or 53:
         cancel event
      else if index of event-slot is 3:
         cancel event
         openAXRsettings(player)
      else if index of event-slot is 5:
         cancel event
         send "{@prefix} &cSei già su ""&aOverworld&c""!"
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 30:
         cancel event
         openAXRsettingsOverworldManual(player)
      else if index of event-slot is 32:
         cancel event
         openAXRsettingsOverworldAutomatic(player)
      else if index of event-slot is 49:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
   else if name of event-inventory is "Anti-Xray: &2Config. manuale":
      if index of event-slot is 0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 26, 27, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 51, 52 or 53:
         cancel event
      else if index of event-slot is 3:
         cancel event
         openAXRsettings(player)
      else if index of event-slot is 4:
         cancel event
         send "{@prefix} &cSei già su ""&aConfigurazione manuale&c""!"
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 5:
         cancel event
         openAXRsettingsOverworldMain(player)
      else if index of event-slot is 19:
         cancel event
         close player's inventory
         set {iron_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fferro &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{iron_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 20:
         cancel event
         close player's inventory
         set {copper_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &drame &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{copper_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 21:
         cancel event
         close player's inventory
         set {gold_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita d'&eoro &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{gold_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 22:
         cancel event
         close player's inventory
         set {redstone_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &credstone &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{redstone_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 23:
         cancel event
         close player's inventory
         set {lapis_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &9lapislazzuli &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{lapis_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 24:
         cancel event
         close player's inventory
         set {emerald_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &asmeraldo &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{emerald_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 25:
         cancel event
         close player's inventory
         set {diamond_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &bdiamante &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{diamond_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 28:
         cancel event
         close player's inventory
         set {deepslate_iron_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fferro in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{deepslate_iron_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 29:
         cancel event
         close player's inventory
         set {deepslate_copper_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &drame in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{deepslate_copper_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 30:
         cancel event
         close player's inventory
         set {deepslate_gold_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita d'&eoro in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{deepslate_gold_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 31:
         cancel event
         close player's inventory
         set {deepslate_redstone_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &credstone in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{deepslate_redstone_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 32:
         cancel event
         close player's inventory
         set {deepslate_lapis_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &9lapislazzuli in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{deepslate_lapis_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 33:
         cancel event
         close player's inventory
         set {deepslate_emerald_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &asmeraldo in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{deepslate_emerald_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 34:
         cancel event
         close player's inventory
         set {deepslate_diamond_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &bdiamante in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{deepslate_diamond_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 48:
         cancel event
         close player's inventory
         send "{@prefix} &cReimposto i valori di tutti i minerali..."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
         set {iron_ore_mined_in_x_sec} to 20
         set {deepslate_iron_ore_mined_in_x_sec} to 20
         set {copper_ore_mined_in_x_sec} to 15
         set {deepslate_copper_ore_mined_in_x_sec} to 15
         set {gold_ore_mined_in_x_sec} to 15
         set {deepslate_gold_ore_mined_in_x_sec} to 15
         set {redstone_ore_mined_in_x_sec} to 16
         set {deepslate_redstone_ore_mined_in_x_sec} to 16
         set {lapis_ore_mined_in_x_sec} to 11
         set {deepslate_lapis_ore_mined_in_x_sec} to 11
         set {emerald_ore_mined_in_x_sec} to 3
         set {deepslate_emerald_ore_mined_in_x_sec} to 3
         set {diamond_ore_mined_in_x_sec} to 6
         set {deepslate_diamond_ore_mined_in_x_sec} to 6
         wait 1 second
         send "{@prefix} &aI valori di tutti i minerali sono stati reimpostati!"
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         openAXRsettingsOverworldManual(player)
      else if index of event-slot is 49:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 50:
         cancel event
         openAXRsettingsOverworldAutomatic(player)
   else if name of event-inventory is "Anti-Xray: &2Config. automatica":
      if index of event-slot is 0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 26, 27, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 51, 52 or 53:
         cancel event
      else if index of event-slot is 3:
         cancel event
         openAXRsettings(player)
      else if index of event-slot is 4:
         cancel event
         send "{@prefix} &cSei già su ""&aConfigurazione automatica&c""!"
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 5:
         cancel event
         openAXRsettingsOverworldMain(player)
      else if index of event-slot is 19:
         cancel event
         close player's inventory
         set {auto_iron_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fferro &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_iron_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 20:
         cancel event
         close player's inventory
         set {auto_copper_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &drame &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_copper_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 21:
         cancel event
         close player's inventory
         set {auto_gold_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita d'&eoro &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_gold_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 22:
         cancel event
         close player's inventory
         set {auto_redstone_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &credstone &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_redstone_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 23:
         cancel event
         close player's inventory
         set {auto_lapis_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &9lapislazzuli &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_lapis_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 24:
         cancel event
         close player's inventory
         set {auto_emerald_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &asmeraldo &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_emerald_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 25:
         cancel event
         close player's inventory
         set {auto_diamond_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &bdiamante &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_diamond_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 28:
         cancel event
         close player's inventory
         set {auto_deepslate_iron_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fferro in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_deepslate_iron_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 29:
         cancel event
         close player's inventory
         set {auto_deepslate_copper_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &drame in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_deepslate_copper_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 30:
         cancel event
         close player's inventory
         set {auto_deepslate_gold_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita d'&eoro in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_deepslate_gold_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 31:
         cancel event
         close player's inventory
         set {auto_deepslate_redstone_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &credstone in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_deepslate_redstone_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 32:
         cancel event
         close player's inventory
         set {auto_deepslate_lapis_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &9lapislazzuli in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_deepslate_lapis_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 33:
         cancel event
         close player's inventory
         set {auto_deepslate_emerald_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &asmeraldo in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_deepslate_emerald_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 34:
         cancel event
         close player's inventory
         set {auto_deepslate_diamond_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &bdiamante in ardesia profonda &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_deepslate_diamond_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 48:
         cancel event
         close player's inventory
         send "{@prefix} &cReimposto i valori di tutti i minerali..."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
         set {detect_iron_ore_mined_in_x_sec} to 30
         set {detect_deepslate_iron_ore_mined_in_x_sec} to 30
         set {detect_copper_ore_mined_in_x_sec} to 30
         set {detect_deepslate_copper_ore_mined_in_x_sec} to 30
         set {detect_gold_ore_mined_in_x_sec} to 25
         set {detect_deepslate_gold_ore_mined_in_x_sec} to 25
         set {detect_redstone_ore_mined_in_x_sec} to 16
         set {detect_deepslate_redstone_ore_mined_in_x_sec} to 16
         set {detect_lapis_ore_mined_in_x_sec} to 11
         set {detect_deepslate_lapis_ore_mined_in_x_sec} to 11
         set {detect_emerald_ore_mined_in_x_sec} to 7
         set {detect_deepslate_emerald_ore_mined_in_x_sec} to 7
         set {detect_diamond_ore_mined_in_x_sec} to 13
         set {detect_deepslate_diamond_ore_mined_in_x_sec} to 13
         wait 1 second
         send "{@prefix} &aI valori di tutti i minerali sono stati reimpostati!"
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         openAXRsettingsOverworldAutomatic(player)
      else if index of event-slot is 49:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 50:
         cancel event
         openAXRsettingsOverworldManual(player)
   else if name of event-inventory is "Anti-Xray: &4Nether":
      if index of event-slot is 0, 1, 2, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52 or 53:
         cancel event
      else if index of event-slot is 3:
         cancel event
         openAXRsettings(player)
      else if index of event-slot is 5:
         cancel event
         send "{@prefix} &cSei già su ""&4Nether&c""!"
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 30:
         cancel event
         openAXRsettingsNetherManual(player)
      else if index of event-slot is 32:
         cancel event
         openAXRsettingsNetherAutomatic(player)
      else if index of event-slot is 49:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
   else if name of event-inventory is "Anti-Xray: &4Config. manuale":
      if index of event-slot is 0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 51, 52 or 53:
         cancel event
      else if index of event-slot is 3:
         cancel event
         openAXRsettings(player)
      else if index of event-slot is 4:
         cancel event
         send "{@prefix} &cSei già su ""&6Configurazione manuale&c""!"
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 5:
         cancel event
         openAXRsettingsNetherMain(player)
      else if index of event-slot is 30:
         cancel event
         close player's inventory
         set {nether_quartz_ore_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fquarzo del Nether &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{nether_quartz_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 31:
         cancel event
         close player's inventory
         set {nether_gold_ore_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita d'&6oro del Nether &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{nether_gold_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 32:
         cancel event
         close player's inventory
         set {ancient_debris_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fdetriti antichi &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{ancient_debris_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 48:
         close player's inventory
         send "{@prefix} &cReimposto i valori di tutti i minerali..."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
         set {nether_quartz_ore_mined_in_x_sec} to 12
         set {nether_gold_ore_mined_in_x_sec} to 16
         set {ancient_debris_mined_in_x_sec} to 2
         wait 1 second
         send "{@prefix} &aI valori di tutti i minerali sono stati reimpostati!"
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         openAXRsettingsNetherManual(player)
      else if index of event-slot is 49:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 50:
         cancel event
         openAXRsettingsNetherAutomatic(player)
   else if name of event-inventory is "Anti-Xray: &4Config. automatica":
      if index of event-slot is 0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 51, 52 or 53:
         cancel event
      else if index of event-slot is 3:
         cancel event
         openAXRsettings(player)
      else if index of event-slot is 4:
         cancel event
         send "{@prefix} &cSei già su ""&6Configurazione automatica&c""!"
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 5:
         cancel event
         openAXRsettingsNetherMain(player)
      else if index of event-slot is 30:
         cancel event
         close player's inventory
         set {auto_nether_quartz_ore_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fquarzo del Nether &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_nether_quartz_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 31:
         cancel event
         close player's inventory
         set {auto_nether_gold_ore_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita d'&6oro del Nether &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_nether_gold_ore_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 32:
         cancel event
         close player's inventory
         set {auto_ancient_debris_set::%player%} to true
         send "{@prefix} &7Modifica la quantità massima consentita di &fdetriti antichi &7che un giocatore possa scavare entro &a%{timer}% secondi &6(Attualmente impostata a &e%{detect_ancient_debris_mined_in_x_sec}% blocchi&6)&7."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
      else if index of event-slot is 48:
         cancel event
         close player's inventory
         send "{@prefix} &cReimposto i valori di tutti i minerali..."
         play sound "{@check_sound}" with volume 1 and pitch 2 at player for player
         set {detect_nether_quartz_ore_mined_in_x_sec} to 16
         set {detect_nether_gold_ore_mined_in_x_sec} to 21
         set {detect_ancient_debris_mined_in_x_sec} to 7
         wait 1 second
         send "{@prefix} &aI valori di tutti i minerali sono stati reimpostati!"
         play sound "{@confirm_sound}" with volume 1 and pitch 2 at player for player
         openAXRsettingsNetherAutomatic(player)
      else if index of event-slot is 49:
         cancel event
         send "&cIn arrivo..."
         play sound "{@error_sound}" with volume 1 and pitch 0 at player for player
      else if index of event-slot is 50:
         cancel event
         openAXRsettingsNetherManual(player)