function openStone1StatsGui(p: player):
    if {settings.%{_p}%.glasspanes} is true:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (1/2 | 1/2)"
        set slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 36, 44, 45, 46, 47, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&r"
        set slot 10 of {_gui} to cobblestone named "&fPietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone}%"
        set slot 11 of {_gui} to stone bricks named "&fMattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_bricks}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_bricks}%"
        set slot 12 of {_gui} to stone named "&fPietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone}%"
        set slot 13 of {_gui} to mossy cobblestone named "&fPietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone}%"
        set slot 14 of {_gui} to mossy stone bricks named "&fMattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_bricks}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_bricks}%"
        set slot 15 of {_gui} to granite named "&fGranito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite}%"
        set slot 16 of {_gui} to diorite named "&fDiorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite}%"
        set slot 19 of {_gui} to cobblestone stairs named "&fScalini di pietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::cobblestone_stairs}%"
        set slot 20 of {_gui} to cracked stone bricks named "&fMattoni di pietra crepati" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cracked_stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::cracked_stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cracked_stone_bricks}%"
        set slot 21 of {_gui} to stone stairs named "&fScalini di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_stairs}%"
        set slot 22 of {_gui} to mossy cobblestone stairs named "&fScalini di pietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_cobblestone_stairs}%"
        set slot 23 of {_gui} to mossy stone brick stairs named "&fScalini di mattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_brick_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_brick_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_brick_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_brick_stairs}%"
        set slot 24 of {_gui} to granite stairs named "&fScalini di granito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::granite_stairs}%"
        set slot 25 of {_gui} to diorite stairs named "&fScalini di diorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::diorite_stairs}%"
        set slot 28 of {_gui} to cobblestone slab named "&fLastra di pietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::cobblestone_slab}%"
        set slot 29 of {_gui} to stone brick stairs named "&fScalini di mattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_brick_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_brick_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_brick_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_brick_stairs}%"
        set slot 30 of {_gui} to stone slab named "&fLastra di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_slab}%"
        set slot 31 of {_gui} to mossy cobblestone slab named "&fLastra di pietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_cobblestone_slab}%"
        set slot 32 of {_gui} to mossy stone brick slab named "&fLastra di mattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_brick_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_brick_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_brick_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_brick_slab}%"
        set slot 33 of {_gui} to granite slab named "&fLastra di granito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::granite_slab}%"
        set slot 34 of {_gui} to diorite slab named "&fLastra di diorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::diorite_slab}%"
        set slot 37 of {_gui} to cobblestone wall named "&fMuretto di pietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::cobblestone_wall}%"
        set slot 38 of {_gui} to stone brick slab named "&fLastra di mattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_brick_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_brick_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_brick_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_brick_slab}%"
        set slot 39 of {_gui} to smooth stone named "&fPietra liscia" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::smooth_stone}%", " &7Piazzati: &f%{build::%{_p}%::placed::smooth_stone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::smooth_stone}%"
        set slot 40 of {_gui} to mossy cobblestone wall named "&fMuretto di pietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_cobblestone_wall}%"
        set slot 41 of {_gui} to mossy stone brick wall named "&fMuretto di mattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_brick_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_brick_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_brick_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_brick_wall}%"
        set slot 42 of {_gui} to granite wall named "&fMuretto di granito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::granite_wall}%"
        set slot 43 of {_gui} to diorite wall named "&fMuretto di diorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::diorite_wall}%"
        set slot 35 of {_gui} to arrow named "&bPagina successiva" with lore "&7Vai a Pietra (1/2 | 2/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 49 of {_gui} to arrow named "&bPagina giù" with lore "&7Vai a Pietra (2/2 | 1/2)"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}
    else:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (1/2 | 1/2)"
        set slot 10 of {_gui} to cobblestone named "&fPietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone}%"
        set slot 11 of {_gui} to stone bricks named "&fMattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_bricks}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_bricks}%"
        set slot 12 of {_gui} to stone named "&fPietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone}%"
        set slot 13 of {_gui} to mossy cobblestone named "&fPietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone}%"
        set slot 14 of {_gui} to mossy stone bricks named "&fMattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_bricks}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_bricks}%"
        set slot 15 of {_gui} to granite named "&fGranito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite}%"
        set slot 16 of {_gui} to diorite named "&fDiorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite}%"
        set slot 19 of {_gui} to cobblestone stairs named "&fScalini di pietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::cobblestone_stairs}%"
        set slot 20 of {_gui} to cracked stone bricks named "&fMattoni di pietra crepati" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cracked_stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::cracked_stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cracked_stone_bricks}%"
        set slot 21 of {_gui} to stone stairs named "&fScalini di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_stairs}%"
        set slot 22 of {_gui} to mossy cobblestone stairs named "&fScalini di pietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_cobblestone_stairs}%"
        set slot 23 of {_gui} to mossy stone brick stairs named "&fScalini di mattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_brick_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_brick_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_brick_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_brick_stairs}%"
        set slot 24 of {_gui} to granite stairs named "&fScalini di granito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::granite_stairs}%"
        set slot 25 of {_gui} to diorite stairs named "&fScalini di diorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::diorite_stairs}%"
        set slot 28 of {_gui} to cobblestone slab named "&fLastra di pietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::cobblestone_slab}%"
        set slot 29 of {_gui} to stone brick stairs named "&fScalini di mattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_brick_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_brick_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_brick_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_brick_stairs}%"
        set slot 30 of {_gui} to stone slab named "&fLastra di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_slab}%"
        set slot 31 of {_gui} to mossy cobblestone slab named "&fLastra di pietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_cobblestone_slab}%"
        set slot 32 of {_gui} to mossy stone brick slab named "&fLastra di mattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_brick_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_brick_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_brick_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_brick_slab}%"
        set slot 33 of {_gui} to granite slab named "&fLastra di granito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::granite_slab}%"
        set slot 34 of {_gui} to diorite slab named "&fLastra di diorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::diorite_slab}%"
        set slot 37 of {_gui} to cobblestone wall named "&fMuretto di pietrisco" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::cobblestone_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::cobblestone_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::cobblestone_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::cobblestone_wall}%"
        set slot 38 of {_gui} to stone brick slab named "&fLastra di mattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_brick_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_brick_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_brick_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_brick_slab}%"
        set slot 39 of {_gui} to smooth stone named "&fPietra liscia" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::smooth_stone}%", " &7Piazzati: &f%{build::%{_p}%::placed::smooth_stone}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::smooth_stone}%"
        set slot 40 of {_gui} to mossy cobblestone wall named "&fMuretto di pietrisco muschioso" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_cobblestone_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_cobblestone_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_cobblestone_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_cobblestone_wall}%"
        set slot 41 of {_gui} to mossy stone brick wall named "&fMuretto di mattoni di pietra muschiosi" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::mossy_stone_brick_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::mossy_stone_brick_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::mossy_stone_brick_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::mossy_stone_brick_wall}%"
        set slot 42 of {_gui} to granite wall named "&fMuretto di granito" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::granite_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::granite_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::granite_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::granite_wall}%"
        set slot 43 of {_gui} to diorite wall named "&fMuretto di diorite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::diorite_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::diorite_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::diorite_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::diorite_wall}%"
        set slot 35 of {_gui} to arrow named "&bPagina successiva" with lore "&7Vai a Pietra (1/2 | 2/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 49 of {_gui} to arrow named "&bPagina giù" with lore "&7Vai a Pietra (2/2 | 1/2)"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}
function openStone1_1StatsGui(p: player):
    if {settings.%{_p}%.glasspanes} is true:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (1/2 | 2/2)"
        set slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&r"
        set slot 13, 14, 15, 16, 20, 21, 22, 23, 24, 25, 29, 30, 31, 32, 33, 34, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&r"
        set slot 10 of {_gui} to andesite named "&fAndesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite}%"
        set slot 11 of {_gui} to calcite named "&fCalcite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::calcite}%", " &7Piazzati: &f%{build::%{_p}%::placed::calcite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::calcite}%"
        set slot 12 of {_gui} to tuff named "&fTufo" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::tuff}%", " &7Piazzati: &f%{build::%{_p}%::placed::tuff}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::tuff}%"
        set slot 19 of {_gui} to andesite stairs named "&fScalini di andesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::andesite_stairs}%"
        set slot 28 of {_gui} to andesite slab named "&fLastra di andesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::andesite_slab}%"
        set slot 37 of {_gui} to andesite wall named "&fMuretto di andesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::andesite_wall}%"
        set slot 27 of {_gui} to arrow named "&bPagina precedente" with lore "&7Vai a Pietra (1/2 | 1/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 49 of {_gui} to arrow named "&bPagina giù" with lore "&7Vai a Pietra (2/2 | 2/2)"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}
    else:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (1/2 | 2/2)"
        set slot 10 of {_gui} to andesite named "&fAndesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite}%"
        set slot 11 of {_gui} to calcite named "&fCalcite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::calcite}%", " &7Piazzati: &f%{build::%{_p}%::placed::calcite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::calcite}%"
        set slot 12 of {_gui} to tuff named "&fTufo" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::tuff}%", " &7Piazzati: &f%{build::%{_p}%::placed::tuff}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::tuff}%"
        set slot 19 of {_gui} to andesite stairs named "&fScalini di andesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::andesite_stairs}%"
        set slot 28 of {_gui} to andesite slab named "&fLastra di andesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::andesite_slab}%"
        set slot 37 of {_gui} to andesite wall named "&fMuretto di andesite" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::andesite_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::andesite_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::andesite_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::andesite_wall}%"
        set slot 27 of {_gui} to arrow named "&bPagina precedente" with lore "&7Vai a Pietra (1/2 | 1/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 49 of {_gui} to arrow named "&bPagina giù" with lore "&7Vai a Pietra (2/2 | 2/2)"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}
function openStone2StatsGui(p: player):
    if {settings.%{_p}%.glasspanes} is true:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (2/2 | 1/2)"
        set slot 0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 26, 27, 36, 44, 45, 46, 47, 49, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&r"
        set slot 10, 13, 14, 19, 21, 22, 23, 28, 29, 30, 31, 32, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&r"
        set slot 11 of {_gui} to stone brick wall named "&fMuretto di mattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_brick_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_brick_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_brick_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_brick_wall}%"
        set slot 12 of {_gui} to smooth stone slab named "&fLastra di pietra liscia" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::smooth_stone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::smooth_stone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::smooth_stone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::smooth_stone_slab}%"
        set slot 15 of {_gui} to polished granite named "&fGranito levigato" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_granite}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_granite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_granite}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_granite}%"
        set slot 16 of {_gui} to polished diorite named "&fDiorite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_diorite}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_diorite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_diorite}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_diorite}%"
        set slot 20 of {_gui} to chiseled stone bricks named "&fMattoni di pietra cesellati" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::chiseled_stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::chiseled_stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::chiseled_stone_bricks}%", " &7Craftati: &f%{build::%{_p}%::crafted::chiseled_stone_bricks}%"
        set slot 24 of {_gui} to polished granite stairs named "&fScalini di granito levigato" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_granite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_granite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_granite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_granite_stairs}%"
        set slot 25 of {_gui} to polished diorite stairs named "&fScalini di diorite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_diorite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_diorite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_diorite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_diorite_stairs}%"
        set slot 33 of {_gui} to polished granite slab named "&fLastra di granito levigato" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_granite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_granite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_granite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_granite_slab}%"
        set slot 34 of {_gui} to polished diorite slab named "&fLastra di diorite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_diorite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_diorite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_diorite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_diorite_slab}%"
        set slot 4 of {_gui} to arrow named "&bPagina su" with lore "&7Vai a Pietra (1/2 | 1/2)"
        set slot 35 of {_gui} to arrow named "&bPagina successiva" with lore "&7Vai a Pietra (2/2 | 2/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}
    else:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (2/2 | 1/2)"
        set slot 11 of {_gui} to stone brick wall named "&fMuretto di mattoni di pietra" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::stone_brick_wall}%", " &7Piazzati: &f%{build::%{_p}%::placed::stone_brick_wall}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::stone_brick_wall}%", " &7Craftati: &f%{build::%{_p}%::crafted::stone_brick_wall}%"
        set slot 12 of {_gui} to smooth stone slab named "&fLastra di pietra liscia" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::smooth_stone_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::smooth_stone_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::smooth_stone_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::smooth_stone_slab}%"
        set slot 15 of {_gui} to polished granite named "&fGranito levigato" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_granite}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_granite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_granite}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_granite}%"
        set slot 16 of {_gui} to polished diorite named "&fDiorite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_diorite}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_diorite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_diorite}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_diorite}%"
        set slot 20 of {_gui} to chiseled stone bricks named "&fMattoni di pietra cesellati" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::chiseled_stone_bricks}%", " &7Piazzati: &f%{build::%{_p}%::placed::chiseled_stone_bricks}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::chiseled_stone_bricks}%", " &7Craftati: &f%{build::%{_p}%::crafted::chiseled_stone_bricks}%"
        set slot 24 of {_gui} to polished granite stairs named "&fScalini di granito levigato" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_granite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_granite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_granite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_granite_stairs}%"
        set slot 25 of {_gui} to polished diorite stairs named "&fScalini di diorite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_diorite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_diorite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_diorite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_diorite_stairs}%"
        set slot 33 of {_gui} to polished granite slab named "&fLastra di granito levigato" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_granite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_granite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_granite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_granite_slab}%"
        set slot 34 of {_gui} to polished diorite slab named "&fLastra di diorite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_diorite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_diorite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_diorite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_diorite_slab}%"
        set slot 4 of {_gui} to arrow named "&bPagina su" with lore "&7Vai a Pietra (1/2 | 1/2)"
        set slot 35 of {_gui} to arrow named "&bPagina successiva" with lore "&7Vai a Pietra (2/2 | 2/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}
function openStone2_1StatsGui(p: player):
    if {settings.%{_p}%.glasspanes} is true:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (2/2 | 2/2)"
        set slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 49, 50, 51, 52 and 53 of {_gui} to black stained glass pane named "&r"
        set slot 11, 12, 13, 14, 15, 16, 20, 21, 22, 23, 24, 25, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42 and 43 of {_gui} to gray stained glass pane named "&r"
        set slot 10 of {_gui} to polished andesite named "&fAndesite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_andesite}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_andesite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_andesite}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_andesite}%"
        set slot 19 of {_gui} to polished andesite stairs named "&fScalini di andesite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_andesite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_andesite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_andesite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_andesite_stairs}%"
        set slot 28 of {_gui} to polished andesite slab named "&fLastra di andesite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_andesite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_andesite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_andesite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_andesite_slab}%"
        set slot 4 of {_gui} to arrow named "&bPagina su" with lore "&7Vai a Pietra (1/2 | 2/2)"
        set slot 27 of {_gui} to arrow named "&bPagina precedente" with lore "&7Vai a Pietra (2/2 | 1/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}
    else:
        set {_gui} to a new chest inventory with 6 rows named "Pietra (2/2 | 2/2)"
        set slot 10 of {_gui} to polished andesite named "&fAndesite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_andesite}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_andesite}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_andesite}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_andesite}%"
        set slot 19 of {_gui} to polished andesite stairs named "&fScalini di andesite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_andesite_stairs}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_andesite_stairs}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_andesite_stairs}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_andesite_stairs}%"
        set slot 28 of {_gui} to polished andesite slab named "&fLastra di andesite levigata" with lore "&aOverworld", " &7Distrutti: &f%{build::%{_p}%::broke::polished_andesite_slab}%", " &7Piazzati: &f%{build::%{_p}%::placed::polished_andesite_slab}%" and " &7Raccolti: &f%{build::%{_p}%::pickup::polished_andesite_slab}%", " &7Craftati: &f%{build::%{_p}%::crafted::polished_andesite_slab}%"
        set slot 4 of {_gui} to arrow named "&bPagina su" with lore "&7Vai a Pietra (1/2 | 2/2)"
        set slot 27 of {_gui} to arrow named "&bPagina precedente" with lore "&7Vai a Pietra (2/2 | 1/2)"
        set slot 48 of {_gui} to arrow named "&fIndietro" with lore "&7Torna a Blocchi da costruzione"
        set slot 50 of {_gui} to paper named "&aStatistiche" with lore "&7Torna alla pagina principale" and "&7delle tue statistiche."
        open {_gui} to {_p}

on inventory click:
    if name of event-inventory is "Pietra (1/2 | 1/2)":
        if type of event-inventory is chest inventory:
            if index of event-slot is 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 51, 52 or 53:
                if click type is left mouse button:
                    cancel event
                else:
                    cancel event
            else if index of event-slot is 35:
                if click type is left mouse button:
                    cancel event
                    openStone1_1StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 48:
                if click type is left mouse button:
                    cancel event
                    openBuildStatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 49:
                if click type is left mouse button:
                    cancel event
                    openStone2StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 50:
                if click type is left mouse button:
                    cancel event
                    openMainStatsGui(player)
                else:
                    cancel event
    else if name of event-inventory is "Pietra (1/2 | 2/2)":
        if type of event-inventory is chest inventory:
            if index of event-slot is 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 51, 52 or 53:
                if click type is left mouse button:
                    cancel event
                else:
                    cancel event
            else if index of event-slot is 27:
                if click type is left mouse button:
                    cancel event
                    openStone1StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 48:
                if click type is left mouse button:
                    cancel event
                    openBuildStatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 49:
                if click type is left mouse button:
                    cancel event
                    openStone2_1StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 50:
                if click type is left mouse button:
                    cancel event
                    openMainStatsGui(player)
                else:
                    cancel event
    else if name of event-inventory is "Pietra (2/2 | 1/2)":
        if type of event-inventory is chest inventory:
            if index of event-slot is 0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 51, 52 or 53:
                if click type is left mouse button:
                    cancel event
                else:
                    cancel event
            else if index of event-slot is 4:
                if click type is left mouse button:
                    cancel event
                    openStone1StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 35:
                if click type is left mouse button:
                    cancel event
                    openStone2_1StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 48:
                if click type is left mouse button:
                    cancel event
                    openBuildStatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 50:
                if click type is left mouse button:
                    cancel event
                    openMainStatsGui(player)
                else:
                    cancel event
    else if name of event-inventory is "Pietra (2/2 | 2/2)":
        if type of event-inventory is chest inventory:
            if index of event-slot is 0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 51, 52 or 53:
                if click type is left mouse button:
                    cancel event
                else:
                    cancel event
            else if index of event-slot is 4:
                if click type is left mouse button:
                    cancel event
                    openStone1_1StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 27:
                if click type is left mouse button:
                    cancel event
                    openStone2StatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 48:
                if click type is left mouse button:
                    cancel event
                    openBuildStatsGui(player)
                else:
                    cancel event
            else if index of event-slot is 50:
                if click type is left mouse button:
                    cancel event
                    openMainStatsGui(player)
                else:
                    cancel event