# SCRIPT PER IL CONTATORE DEGLI OGGETTI PER GLI OBIETTIVI A LIVELLI (E NON)

on right click:
    loop all players:
        if loop-player's gamemode is survival or adventure:
            if loop-player's tool is a wooden axe, stone axe, iron axe, gold axe, diamond axe or netherite axe:
                if event-block is oak log:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_oak_log}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::overworld}
                else if event-block is birch log:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_birch_log}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::overworld}
                else if event-block is dark oak log:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_dark_oak_log}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::overworld}
                else if event-block is spruce log:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_spruce_log}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::overworld}
                else if event-block is acacia log:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_acacia_log}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::overworld}
                else if event-block is mangrove log:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_mangrove_log}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::overworld}
                else if event-block is jungle log:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_jungle_log}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::overworld}
                else if event-block is crimson stem:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_crimson_stem}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::nether}
                else if event-block is warped stem:
                    add 1 to {blocksbuild::%loop-player%::stripped::stripped_warped_stem}
                    add 1 to {blocksbuild::%loop-player%::stripped}
                    add 1 to {item::%loop-player%::stripped::nether}
                

on break:
    loop all players:
        if loop-player's gamemode is survival or adventure:
# BLOCCHI DA COSTRUZIONE
    # QUERCIA
            if event-block is oak log:
                add 1 to {blocksbuild::%loop-player%::broke::oak_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stripped oak log:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_oak_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is oak planks:
                add 1 to {blocksbuild::%loop-player%::broke::oak_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is oak stairs:
                add 1 to {blocksbuild::%loop-player%::broke::oak_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is oak slab:
                add 1 to {blocksbuild::%loop-player%::broke::oak_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is oak fence:
                add 1 to {blocksbuild::%loop-player%::broke::oak_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is oak fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::oak_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is oak door:
                add 1 to {blocksbuild::%loop-player%::broke::oak_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is oak trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::oak_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # BETULLA
            else if event-block is birch log:
                add 1 to {blocksbuild::%loop-player%::broke::birch_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stripped birch log:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_birch_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch planks:
                add 1 to {blocksbuild::%loop-player%::broke::birch_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch stairs:
                add 1 to {blocksbuild::%loop-player%::broke::birch_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch slab:
                add 1 to {blocksbuild::%loop-player%::broke::birch_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch fence:
                add 1 to {blocksbuild::%loop-player%::broke::birch_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::birch_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch door:
                add 1 to {blocksbuild::%loop-player%::broke::birch_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::birch_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # QUERCIA SCURA
            else if event-block is dark oak log:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_log}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is stripped dark oak log:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_dark_oak_log}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is dark oak planks:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_planks}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is dark oak stairs:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_stairs}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is dark oak slab:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_slab}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is dark oak fence:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_fence}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is dark oak fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_fence_gate}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is dark oak door:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_door}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
            else if event-block is dark oak trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::dark_oak_trapdoor}
                add 1 to {blocksbuild::%loop-player%}
                add 1 to {item::%loop-player%::overworld}
    # ABETE
            else if event-block is spruce log:
                add 1 to {blocksbuild::%loop-player%::broke::spruce_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stripped spruce log:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_spruce_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce planks:
                add 1 to {blocksbuild::%loop-player%::broke::spruce_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce stairs:
                add 1 to {blocksbuild::%loop-player%::spruce_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce slab:
                add 1 to {blocksbuild::%loop-player%::spruce_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce fence:
                add 1 to {blocksbuild::%loop-player%::spruce_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce fence gate:
                add 1 to {blocksbuild::%loop-player%::spruce_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce door:
                add 1 to {blocksbuild::%loop-player%::spruce_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce trapdoor:
                add 1 to {blocksbuild::%loop-player%::spruce_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # ACACIA
            else if event-block is acacia log:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stripped acacia log:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_acacia_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia planks:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia stairs:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia slab:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia fence:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia door:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::acacia_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # MANGROVIA
            else if event-block is mangrove log:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stripped mangrove log:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_mangrove_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove planks:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove stairs:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove slab:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove fence:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove door:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::mangrove_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # GIUNGLA
            else if event-block is jungle log:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stripped jungle log:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_jungle_log}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle planks:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle stairs:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle slab:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle fence:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle door:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::jungle_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # CREMISI
            else if event-block is crimson stem:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_stem}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is stripped crimson stem:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_crimson_stem}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is crimson planks:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is crimson stairs:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is crimson slab:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is crimson fence:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is crimson fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is crimson door:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is crimson trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::crimson_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # DISTORTO
            else if event-block is warped stem:
                add 1 to {blocksbuild::%loop-player%::broke::warped_stem}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is stripped warped stem:
                add 1 to {blocksbuild::%loop-player%::broke::stripped_warped_stem}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped planks:
                add 1 to {blocksbuild::%loop-player%::broke::warped_planks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped stairs:
                add 1 to {blocksbuild::%loop-player%::broke::warped_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped slab:
                add 1 to {blocksbuild::%loop-player%::broke::warped_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped fence:
                add 1 to {blocksbuild::%loop-player%::broke::warped_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped fence gate:
                add 1 to {blocksbuild::%loop-player%::broke::warped_fence_gate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped door:
                add 1 to {blocksbuild::%loop-player%::broke::warped_door}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped trapdoor:
                add 1 to {blocksbuild::%loop-player%::broke::warped_trapdoor}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # PIETRISCO
            else if event-block is cobblestone:
                add 1 to {blocksbuild::%loop-player%::broke::cobblestone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cobblestone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::cobblestone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cobblestone slab:
                add 1 to {blocksbuild::%loop-player%::broke::cobblestone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cobblestone wall:
                add 1 to {blocksbuild::%loop-player%::broke::cobblestone_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PIETRISCO MUSCHIOSO
            else if event-block is mossy cobblestone:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_cobblestone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mossy cobblestone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_cobblestone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mossy cobblestone slab:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_cobblestone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mossy cobblestone wall:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_cobblestone_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PIETRA
            else if event-block is stone:
                add 1 to {blocksbuild::%loop-player%::broke::stone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::stone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stone slab:
                add 1 to {blocksbuild::%loop-player%::broke::stone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is calcite:
                add 1 to {blocksbuild::%loop-player%::broke::calcite}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is tuff:
                add 1 to {blocksbuild::%loop-player%::broke::tuff}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PIETRA LISCIA
            else if event-block is smooth stone:
                add 1 to {blocksbuild::%loop-player%::broke::smooth_stone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is smooth stone slab:
                add 1 to {blocksbuild::%loop-player%::broke::smooth_stone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # MATTONI DI PIETRA
            else if event-block is stone bricks:
                add 1 to {blocksbuild::%loop-player%::broke::stone_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cracked stone bricks:
                add 1 to {blocksbuild::%loop-player%::broke::cracked_stone_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stone brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::stone_brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stone brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::stone_brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is stone brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::stone_brick_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is chiseled stone bricks:
                add 1 to {blocksbuild::%loop-player%::broke::chiseled_stone_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # MATTONI DI PIETRA MUSCHIOSI
            else if event-block is mossy stone bricks:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_stone_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mossy stone brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_stone_brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mossy stone brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_stone_brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mossy stone brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::mossy_stone_brick_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # GRANITO
            else if event-block is granite:
                add 1 to {blocksbuild::%loop-player%::broke::granite}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is granite stairs:
                add 1 to {blocksbuild::%loop-player%::broke::granite_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is granite slab:
                add 1 to {blocksbuild::%loop-player%::broke::granite_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is granite wall:
                add 1 to {blocksbuild::%loop-player%::broke::granite_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # GRANITO LEVIGATO
            else if event-block is polished granite:
                add 1 to {blocksbuild::%loop-player%::broke::polished_granite}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished granite stairs:
                add 1 to {blocksbuild::%loop-player%::broke::polished_granite_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished granite slab:
                add 1 to {blocksbuild::%loop-player%::broke::polished_granite_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # DIORITE
            else if event-block is diorite:
                add 1 to {blocksbuild::%loop-player%::broke::diorite}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is diorite stairs:
                add 1 to {blocksbuild::%loop-player%::broke::diorite_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is diorite slab:
                add 1 to {blocksbuild::%loop-player%::broke::diorite_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is diorite wall:
                add 1 to {blocksbuild::%loop-player%::broke::diorite_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # DIORITE LEVIGATA
            else if event-block is polished diorite:
                add 1 to {blocksbuild::%loop-player%::broke::polished_diorite}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished diorite stairs:
                add 1 to {blocksbuild::%loop-player%::broke::polished_diorite_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished diorite slab:
                add 1 to {blocksbuild::%loop-player%::broke::polished_diorite_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # ANDESITE
            else if event-block is andesite:
                add 1 to {blocksbuild::%loop-player%::broke::andesite}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is andesite stairs:
                add 1 to {blocksbuild::%loop-player%::broke::andesite_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is andesite slab:
                add 1 to {blocksbuild::%loop-player%::broke::andesite_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is andesite wall:
                add 1 to {blocksbuild::%loop-player%::broke::andesite_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # ANDESITE LEVIGATA
            else if event-block is polished andesite:
                add 1 to {blocksbuild::%loop-player%::broke::polished_andesite}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished andesite stairs:
                add 1 to {blocksbuild::%loop-player%::broke::polished_andesite_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished andesite slab:
                add 1 to {blocksbuild::%loop-player%::broke::polished_andesite_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PIETRISCO DI ARDESIA PROFONDA E ARDESIA PROFONDA
            else if event-block is cobbled deepslate:
                add 1 to {blocksbuild::%loop-player%::broke::cobbled_deepslate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cobbled deepslate stairs:
                add 1 to {blocksbuild::%loop-player%::broke::cobbled_deepslate_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cobbled deepslate slab:
                add 1 to {blocksbuild::%loop-player%::broke::cobbled_deepslate_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cobbled deepslate wall:
                add 1 to {blocksbuild::%loop-player%::broke::cobbled_deepslate_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is deepslate:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # ARDESIA PROFONDA LEVIGATA
            else if event-block is polished deepslate:
                add 1 to {blocksbuild::%loop-player%::broke::polished_deepslate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished deepslate stairs:
                add 1 to {blocksbuild::%loop-player%::broke::polished_deepslate_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished deepslate slab:
                add 1 to {blocksbuild::%loop-player%::broke::polished_deepslate_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is polished deepslate wall:
                add 1 to {blocksbuild::%loop-player%::broke::polished_deepslate_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # MATTONI DI ARDESIA PROFONDA
            else if event-block is deepslate bricks:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cracked deepslate bricks:
                add 1 to {blocksbuild::%loop-player%::broke::cracked_deepslate_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is deepslate brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_bricks_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is deepslate brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_bricks_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is deepslate brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_bricks_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PIASTRELLE DI ARDESIA PROFONDA
            else if event-block is deepslate tiles:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_tiles}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cracked deepslate tiles:
                add 1 to {blocksbuild::%loop-player%::broke::cracked_deepslate_tiles}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is deepslate tile stairs:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_tiles_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is deepslate tile slab:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_tiles_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is deepslate tile wall:
                add 1 to {blocksbuild::%loop-player%::broke::deepslate_tiles_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # ARDESIA PROFONDA RINFORZATA
            else if event-block is reinforced deepslate:
                add 1 to {blocksbuild::%loop-player%::broke::reinforced_deepslate}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # MATTONI
            else if event-block is bricks:
                add 1 to {blocksbuild::%loop-player%::broke::bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::brick_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # FANGO
            else if event-block is mud:
                add 1 to {blocksbuild::%loop-player%::broke::mud}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is muddy mangrove roots:
                add 1 to {blocksbuild::%loop-player%::broke::muddy_mangrove_roots}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is packed mud:
                add 1 to {blocksbuild::%loop-player%::broke::packed_mud}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mud bricks:
                add 1 to {blocksbuild::%loop-player%::broke::mud_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mud brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::mud_brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mud brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::mud_brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mud brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::mud_brick_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # ARENARIA
            else if event-block is sandstone:
                add 1 to {blocksbuild::%loop-player%::broke::sandstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is sandstone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::sandstone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is sandstone slab:
                add 1 to {blocksbuild::%loop-player%::broke::sandstone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is sandstone wall:
                add 1 to {blocksbuild::%loop-player%::broke::sandstone_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is chiseled sandstone:
                add 1 to {blocksbuild::%loop-player%::broke::chiseled_sandstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cut sandstone:
                add 1 to {blocksbuild::%loop-player%::broke::cut_sandstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cut sandstone slab:
                add 1 to {blocksbuild::%loop-player%::broke::cut_sandstone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # ARENARIA ROSSA
            else if event-block is red sandstone:
                add 1 to {blocksbuild::%loop-player%::broke::red_sandstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red sandstone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::red_sandstone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red sandstone slab:
                add 1 to {blocksbuild::%loop-player%::broke::red_sandstone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red sandstone wall:
                add 1 to {blocksbuild::%loop-player%::broke::red_sandstone_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is chiseled red sandstone:
                add 1 to {blocksbuild::%loop-player%::broke::chiseled_red_sandstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cut red sandstone:
                add 1 to {blocksbuild::%loop-player%::broke::cut_red_sandstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cut red sandstone slab:
                add 1 to {blocksbuild::%loop-player%::broke::cut_red_sandstone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PRISMARINO
            else if event-block is prismarine:
                add 1 to {blocksbuild::%loop-player%::broke::prismarine}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is prismarine stairs:
                add 1 to {blocksbuild::%loop-player%::broke::prismarine_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is prismarine slab:
                add 1 to {blocksbuild::%loop-player%::broke::prismarine_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is prismarine wall:
                add 1 to {blocksbuild::%loop-player%::broke::prismarine_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # MATTONI DI PRISMARINO
            else if event-block is prismarine bricks:
                add 1 to {blocksbuild::%loop-player%::broke::prismarine_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is prismarine brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::prismarine_brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is prismarine brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::prismarine_brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PRISMARINO SCURO
            else if event-block is dark prismarine:
                add 1 to {blocksbuild::%loop-player%::broke::dark_prismarine}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is dark prismarine stairs:
                add 1 to {blocksbuild::%loop-player%::broke::dark_prismarine_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is dark prismarine slab:
                add 1 to {blocksbuild::%loop-player%::broke::dark_prismarine_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # NETHERRACK
            else if event-block is netherrack:
                add 1 to {blocksbuild::%loop-player%::broke::netherrack}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # MATTONI DEL NETHER
            else if event-block is nether bricks:
                add 1 to {blocksbuild::%loop-player%::broke::nether_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is cracked nether bricks:
                add 1 to {blocksbuild::%loop-player%::broke::cracked_nether_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is nether brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::nether_brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is nether brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::nether_brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is nether brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::nether_brick_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is nether brick fence:
                add 1 to {blocksbuild::%loop-player%::broke::nether_brick_fence}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is chiseled nether bricks:
                add 1 to {blocksbuild::%loop-player%::broke::chiseled_nether_brick}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # MATTONI DEL NETHER ROSSI
            else if event-block is red nether bricks:
                add 1 to {blocksbuild::%loop-player%::broke::red_nether_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is red nether brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::red_nether_brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is red nether brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::red_nether_brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is red nether brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::red_nether_brick_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # BASALTO
            else if event-block is basalt:
                add 1 to {blocksbuild::%loop-player%::broke::basalt}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is smooth basalt:
                add 1 to {blocksbuild::%loop-player%::broke::smooth_basalt}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is polished basalt:
                add 1 to {blocksbuild::%loop-player%::broke::polished_basalt}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # PIETRANERA
            else if event-block is blackstone:
                add 1 to {blocksbuild::%loop-player%::broke::blackstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is blackstone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::blackstone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is blackstone slab:
                add 1 to {blocksbuild::%loop-player%::broke::blackstone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is blackstone wall:
                add 1 to {blocksbuild::%loop-player%::broke::blackstone_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is gilded blackstone:
                add 1 to {blocksbuild::%loop-player%::broke::gilded_blackstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # PIETRANERA LEVIGATA
            else if event-block is polished blackstone:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is polished blackstone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is polished blackstone slab:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is polished blackstone wall:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is chiseled polished blackstone:
                add 1 to {blocksbuild::%loop-player%::broke::chiseled_polished_blackstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # MATTONI DI PIETRANERA LEVIGATA
            else if event-block is polished blackstone bricks:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is polished blackstone stairs:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is polished blackstone slab:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is polished blackstone wall:
                add 1 to {blocksbuild::%loop-player%::broke::polished_blackstone_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is chiseled polished blackstone:
                add 1 to {blocksbuild::%loop-player%::broke::chiseled_polished_blackstone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # PIETRA DELL'END E MATTONI DI PIETRA DELL'END
            else if event-block is end stone:
                add 1 to {blocksbuild::%loop-player%::broke::end_stone}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
            else if event-block is end stone bricks:
                add 1 to {blocksbuild::%loop-player%::broke::end_stone_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
            else if event-block is end stone brick stairs:
                add 1 to {blocksbuild::%loop-player%::broke::end_stone_brick_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
            else if event-block is end stone brick slab:
                add 1 to {blocksbuild::%loop-player%::broke::end_stone_brick_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
            else if event-block is end stone brick wall:
                add 1 to {blocksbuild::%loop-player%::broke::end_stone_brick_wall}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
    # PURPUR
            else if event-block is purpur block:
                add 1 to {blocksbuild::%loop-player%::broke::purpur_block}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
            else if event-block is purpur pillar:
                add 1 to {blocksbuild::%loop-player%::broke::purpur_pillar}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
            else if event-block is purpur stairs:
                add 1 to {blocksbuild::%loop-player%::broke::purpur_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
            else if event-block is purpur slab:
                add 1 to {blocksbuild::%loop-player%::broke::purpur_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::end}
    # QUARZO
            else if event-block is quartz block:
                add 1 to {blocksbuild::%loop-player%::broke::quartz_block}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is quartz stairs:
                add 1 to {blocksbuild::%loop-player%::broke::quartz_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is quartz slab:
                add 1 to {blocksbuild::%loop-player%::broke::quartz_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is chiseled quartz block:
                add 1 to {blocksbuild::%loop-player%::broke::chiseled_quartz_block}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is quartz bricks:
                add 1 to {blocksbuild::%loop-player%::broke::quartz_bricks}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is quartz pillar:
                add 1 to {blocksbuild::%loop-player%::broke::quartz_pillar}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is smooth quartz:
                add 1 to {blocksbuild::%loop-player%::broke::smooth_quartz}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is smooth quartz stairs:
                add 1 to {blocksbuild::%loop-player%::broke::smooth_quartz_stairs}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is smooth quartz slab:
                add 1 to {blocksbuild::%loop-player%::broke::smooth_quartz_slab}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # SBARRE DI FERRO
            else if event-block is iron bars:
                add 1 to {blocksbuild::%loop-player%::broke::iron_bars}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # BLOCCHI APPICCICOSI
            else if event-block is slime block:
                add 1 to {blocksbuild::%loop-player%::broke::slime_block}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is honey block:
                add 1 to {blocksbuild::%loop-player%::broke::honey_block}
                add 1 to {blocksbuild::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
# BLOCCHI COLORATI
    # LANA
            else if event-block is white wool:
                add 1 to {blockscolor::%loop-player%::broke::white_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray wool:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray wool:
                add 1 to {blockscolor::%loop-player%::broke::gray_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black wool:
                add 1 to {blockscolor::%loop-player%::broke::black_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown wool:
                add 1 to {blockscolor::%loop-player%::broke::brown_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red wool:
                add 1 to {blockscolor::%loop-player%::broke::red_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange wool:
                add 1 to {blockscolor::%loop-player%::broke::orange_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow wool:
                add 1 to {blockscolor::%loop-player%::broke::yellow_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime wool:
                add 1 to {blockscolor::%loop-player%::broke::lime_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green wool:
                add 1 to {blockscolor::%loop-player%::broke::green_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan wool:
                add 1 to {blockscolor::%loop-player%::broke::cyan_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue wool:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue wool:
                add 1 to {blockscolor::%loop-player%::broke::blue_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple wool:
                add 1 to {blockscolor::%loop-player%::broke::purple_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta wool:
                add 1 to {blockscolor::%loop-player%::broke::magenta_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink wool:
                add 1 to {blockscolor::%loop-player%::broke::pink_wool}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # TAPPETI
            else if event-block is white carpet:
                add 1 to {blockscolor::%loop-player%::broke::white_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray carpet:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray carpet:
                add 1 to {blockscolor::%loop-player%::broke::gray_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black carpet:
                add 1 to {blockscolor::%loop-player%::broke::black_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown carpet:
                add 1 to {blockscolor::%loop-player%::broke::brown_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red carpet:
                add 1 to {blockscolor::%loop-player%::broke::red_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange carpet:
                add 1 to {blockscolor::%loop-player%::broke::orange_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow carpet:
                add 1 to {blockscolor::%loop-player%::broke::yellow_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime carpet:
                add 1 to {blockscolor::%loop-player%::broke::lime_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green carpet:
                add 1 to {blockscolor::%loop-player%::broke::green_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan carpet:
                add 1 to {blockscolor::%loop-player%::broke::cyan_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue carpet:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue carpet:
                add 1 to {blockscolor::%loop-player%::broke::blue_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple carpet:
                add 1 to {blockscolor::%loop-player%::broke::purple_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta carpet:
                add 1 to {blockscolor::%loop-player%::broke::magenta_carpet}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink carpet:
                add 1 to {blockscolor::%loop-player%::broke::pink_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # TERRACOTTA
            else if event-block is terracotta:
                add 1 to {blockscolor::%loop-player%::broke::terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is white terracotta:
                add 1 to {blockscolor::%loop-player%::broke::white_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray terracotta:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray terracotta:
                add 1 to {blockscolor::%loop-player%::broke::gray_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black terracotta:
                add 1 to {blockscolor::%loop-player%::broke::black_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown terracotta:
                add 1 to {blockscolor::%loop-player%::broke::brown_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red terracotta:
                add 1 to {blockscolor::%loop-player%::broke::red_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange terracotta:
                add 1 to {blockscolor::%loop-player%::broke::orange_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow terracotta:
                add 1 to {blockscolor::%loop-player%::broke::yellow_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime terracotta:
                add 1 to {blockscolor::%loop-player%::broke::lime_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green terracotta:
                add 1 to {blockscolor::%loop-player%::broke::green_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan terracotta:
                add 1 to {blockscolor::%loop-player%::broke::cyan_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue terracotta:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue terracotta:
                add 1 to {blockscolor::%loop-player%::broke::blue_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple terracotta:
                add 1 to {blockscolor::%loop-player%::broke::purple_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta terracotta:
                add 1 to {blockscolor::%loop-player%::broke::magenta_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink terracotta:
                add 1 to {blockscolor::%loop-player%::broke::pink_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # TERRACOTTA SMALTATA
            else if event-block is white glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::white_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::gray_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::black_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::brown_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::red_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::orange_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::yellow_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::lime_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::green_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::cyan_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::blue_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::purple_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::magenta_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink glazed terracotta:
                add 1 to {blockscolor::%loop-player%::broke::pink_glazed_terracotta}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # CALCESTRUZZO
            else if event-block is white concrete:
                add 1 to {blockscolor::%loop-player%::broke::white_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray concrete:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray concrete:
                add 1 to {blockscolor::%loop-player%::broke::gray_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black concrete:
                add 1 to {blockscolor::%loop-player%::broke::black_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown concrete:
                add 1 to {blockscolor::%loop-player%::broke::brown_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red concrete:
                add 1 to {blockscolor::%loop-player%::broke::red_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange concrete:
                add 1 to {blockscolor::%loop-player%::broke::orange_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow concrete:
                add 1 to {blockscolor::%loop-player%::broke::yellow_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime concrete:
                add 1 to {blockscolor::%loop-player%::broke::lime_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green concrete:
                add 1 to {blockscolor::%loop-player%::broke::green_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan concrete:
                add 1 to {blockscolor::%loop-player%::broke::cyan_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue concrete:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue concrete:
                add 1 to {blockscolor::%loop-player%::broke::blue_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple concrete:
                add 1 to {blockscolor::%loop-player%::broke::purple_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta concrete:
                add 1 to {blockscolor::%loop-player%::broke::magenta_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink concrete:
                add 1 to {blockscolor::%loop-player%::broke::pink_concrete}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # POLVERE DI CALCESTRUZZO
            else if event-block is white concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::white_concrete_powder_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::gray_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::black_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown concrete powder: 
                add 1 to {blockscolor::%loop-player%::broke::brown_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::red_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::orange_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::yellow_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::lime_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::green_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::cyan_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::blue_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::purple_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::magenta_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink concrete powder:
                add 1 to {blockscolor::%loop-player%::broke::pink_concrete_powder}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # VETRO
            else if event-block is glass:
                add 1 to {blockscolor::%loop-player%::broke::glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is tinted glass:
                add 1 to {blockscolor::%loop-player%::broke::tinted_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is white stained glass:
                add 1 to {blockscolor::%loop-player%::broke::white_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray stained glass:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray stained glass:
                add 1 to {blockscolor::%loop-player%::broke::gray_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black stained glass:
                add 1 to {blockscolor::%loop-player%::broke::black_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown stained glass:
                add 1 to {blockscolor::%loop-player%::broke::brown_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red stained glass:
                add 1 to {blockscolor::%loop-player%::broke::red_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange stained glass:
                add 1 to {blockscolor::%loop-player%::broke::orange_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow stained glass:
                add 1 to {blockscolor::%loop-player%::broke::yellow_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime stained glass:
                add 1 to {blockscolor::%loop-player%::broke::lime_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green stained glass:
                add 1 to {blockscolor::%loop-player%::broke::green_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan stained glass:
                add 1 to {blockscolor::%loop-player%::broke::cyan_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue stained glass:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue stained glass:
                add 1 to {blockscolor::%loop-player%::broke::blue_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple stained glass:
                add 1 to {blockscolor::%loop-player%::broke::purple_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta stained glass:
                add 1 to {blockscolor::%loop-player%::broke::magenta_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink stained glass:
                add 1 to {blockscolor::%loop-player%::broke::pink_stained_glass}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # PANNELLI DI VETRO
            else if event-block is glass pane:
                add 1 to {blockscolor::%loop-player%::broke::glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is white stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::white_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::gray_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::black_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::brown_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::red_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::orange_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::yellow_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::lime_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::green_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::cyan_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::blue_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::purple_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::magenta_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink stained glass pane:
                add 1 to {blockscolor::%loop-player%::broke::pink_stained_glass_pane}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # SHULKER BOX
            else if event-block is shulker box:
                add 1 to {blockscolor::%loop-player%::broke::shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is white shulker box:
                add 1 to {blockscolor::%loop-player%::broke::white_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray shulker box:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray shulker box:
                add 1 to {blockscolor::%loop-player%::broke::gray_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black shulker box:
                add 1 to {blockscolor::%loop-player%::broke::black_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown shulker box:
                add 1 to {blockscolor::%loop-player%::broke::brown_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red shulker box:
                add 1 to {blockscolor::%loop-player%::broke::red_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange shulker box:
                add 1 to {blockscolor::%loop-player%::broke::orange_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow shulker box:
                add 1 to {blockscolor::%loop-player%::broke::yellow_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime shulker box:
                add 1 to {blockscolor::%loop-player%::broke::lime_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green shulker box:
                add 1 to {blockscolor::%loop-player%::broke::green_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan shulker box:
                add 1 to {blockscolor::%loop-player%::broke::cyan_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue shulker box:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue shulker box:
                add 1 to {blockscolor::%loop-player%::broke::blue_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple shulker box:
                add 1 to {blockscolor::%loop-player%::broke::purple_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta shulker box:
                add 1 to {blockscolor::%loop-player%::broke::magenta_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink shulker box:
                add 1 to {blockscolor::%loop-player%::broke::pink_shulker_box}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # LETTI
            else if event-block is white bed:
                add 1 to {blockscolor::%loop-player%::broke::white_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray bed:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray bed:
                add 1 to {blockscolor::%loop-player%::broke::gray_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black bed:
                add 1 to {blockscolor::%loop-player%::broke::black_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown bed:
                add 1 to {blockscolor::%loop-player%::broke::brown_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red bed:
                add 1 to {blockscolor::%loop-player%::broke::red_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange bed:
                add 1 to {blockscolor::%loop-player%::broke::orange_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow bed:
                add 1 to {blockscolor::%loop-player%::broke::yellow_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime bed:
                add 1 to {blockscolor::%loop-player%::broke::lime_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green bed:
                add 1 to {blockscolor::%loop-player%::broke::green_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan bed:
                add 1 to {blockscolor::%loop-player%::broke::cyan_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue bed:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue bed:
                add 1 to {blockscolor::%loop-player%::broke::blue_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple bed:
                add 1 to {blockscolor::%loop-player%::broke::purple_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta bed:
                add 1 to {blockscolor::%loop-player%::broke::magenta_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink bed:
                add 1 to {blockscolor::%loop-player%::broke::pink_bed}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # CANDELA
            else if event-block is candle:
                add 1 to {blockscolor::%loop-player%::broke::candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is white candle:
                add 1 to {blockscolor::%loop-player%::broke::white_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light gray candle:
                add 1 to {blockscolor::%loop-player%::broke::light_gray_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is gray candle:
                add 1 to {blockscolor::%loop-player%::broke::gray_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is black candle:
                add 1 to {blockscolor::%loop-player%::broke::black_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is brown candle:
                add 1 to {blockscolor::%loop-player%::broke::brown_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red candle:
                add 1 to {blockscolor::%loop-player%::broke::red_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is orange candle:
                add 1 to {blockscolor::%loop-player%::broke::orange_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is yellow candle:
                add 1 to {blockscolor::%loop-player%::broke::yellow_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is lime candle:
                add 1 to {blockscolor::%loop-player%::broke::lime_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is green candle:
                add 1 to {blockscolor::%loop-player%::broke::green_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is cyan candle:
                add 1 to {blockscolor::%loop-player%::broke::cyan_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is light blue candle:
                add 1 to {blockscolor::%loop-player%::broke::light_blue_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue candle:
                add 1 to {blockscolor::%loop-player%::broke::blue_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is purple candle:
                add 1 to {blockscolor::%loop-player%::broke::purple_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is magenta candle:
                add 1 to {blockscolor::%loop-player%::broke::magenta_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pink candle:
                add 1 to {blockscolor::%loop-player%::broke::pink_candle}
                add 1 to {blockscolor::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
# BLOCCHI NATURALI            
    # - TERRA E VARIANTI - #
            else if event-block is grass block:
                add 1 to {blocksnature::%loop-player%::broke::grass_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is podzol:
                add 1 to {blocksnature::%loop-player%::broke::podzol}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mycelium block:
                add 1 to {blocksnature::%loop-player%::broke::mycelium}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is dirt path:
                add 1 to {blocksnature::%loop-player%::broke::dirt_path}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is dirt:
                add 1 to {blocksnature::%loop-player%::broke::dirt}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is coarse dirt:
                add 1 to {blocksnature::%loop-player%::broke::coarse_dirt}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is rooted dirt:
                add 1 to {blocksnature::%loop-player%::broke::rooted_dirt}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is farmland:
                add 1 to {blocksnature::%loop-player%::broke::farmland}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - GHIACCIO - #
            else if event-block is ice:
                add 1 to {blocksnature::%loop-player%::broke::ice}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is packed ice:
                add 1 to {blocksnature::%loop-player%::broke::packed_ice}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is blue ice:
                add 1 to {blocksnature::%loop-player%::broke::blue_ice}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - GHIAIA - #
            else if event-block is gravel:
                add 1 to {blocksnature::%loop-player%::broke::gravel}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - SABBIA E SABBIA ROSSA - #
            else if event-block is sand:
                add 1 to {blocksnature::%loop-player%::broke::sand}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red sand:
                add 1 to {blocksnature::%loop-player%::broke::red_sand}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - MUSCHIO - #
            else if event-block is moss block:
                add 1 to {blocksnature::%loop-player%::broke::moss_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is moss carpet:
                add 1 to {blocksnature::%loop-player%::broke::moss_carpet}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - NECELI - #
            else if event-block is crimson nylium:
                add 1 to {blocksnature::%loop-player%::broke::crymson_nylium}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped nylium:
                add 1 to {blocksnature::%loop-player%::broke::warped_nylium}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # - SABBIA DELLE ANIME E TERRA DELLE ANIME - #
            else if event-block is soul sand:
                add 1 to {blocksnature::%loop-player%::broke::soul_sand}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is soul soil:
                add 1 to {blocksnature::%loop-player%::broke::soul_soil}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # - SPELEOTEMA - #
            else if event-block is dripstone block:
                add 1 to {blocksnature::%loop-player%::broke::dripstone_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is pointed dripstone:
                add 1 to {blocksnature::%loop-player%::broke::pointed_dripstone}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - OSSIDIANA - #
            else if event-block is obsidian:
                add 1 to {blocksnature::%loop-player%::broke::obsidian}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is crying obsidian:
                add 1 to {blocksnature::%loop-player%::broke::crying_obsidian}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - FOGLIE - #
            else if event-block is oak leaves:
                add 1 to {blocksnature::%loop-player%::broke::oak_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce leaves:
                add 1 to {blocksnature::%loop-player%::broke::spruce_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch leaves:
                add 1 to {blocksnature::%loop-player%::broke::birch_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle leaves:
                add 1 to {blocksnature::%loop-player%::broke::jungle_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is dark oak leaves:
                add 1 to {blocksnature::%loop-player%::broke::dark_oak_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove leaves:
                add 1 to {blocksnature::%loop-player%::broke::mangrove_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove roots:
                add 1 to {blocksnature::%loop-player%::broke::mangrove_roots}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is azalea leaves:
                add 1 to {blocksnature::%loop-player%::broke::azalea_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is flowering azalea leaves:
                add 1 to {blocksnature::%loop-player%::broke::flowering_azalea_leaves}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - BLOCCHI DI FUNGHI - #
            else if event-block is brown mushroom block:
                add 1 to {blocksnature::%loop-player%::broke::brown_mushroom_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is red mushroom block:
                add 1 to {blocksnature::%loop-player%::broke::red_mushroom_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - BLOCHHI DI VERRUCHE DEL NETHER - #
            else if event-block is nether wart block:
                add 1 to {blocksnature::%loop-player%::broke::nether_wart_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
            else if event-block is warped wart block:
                add 1 to {blocksnature::%loop-player%::broke::warped_wart_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # - BLOCCO DI MAGMA - #
            else if event-block is magma block:
                add 1 to {blocksnature::%loop-player%::broke::magma_block}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::nether}
    # - ARBOSCELLI - #
            else if event-block is oak sapling:
                add 1 to {blocksnature::%loop-player%::broke::oak_sapling}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is spruce sapling:
                add 1 to {blocksnature::%loop-player%::broke::spruce_sapling}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is birch sapling:
                add 1 to {blocksnature::%loop-player%::broke::birch_sapling}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is jungle sapling:
                add 1 to {blocksnature::%loop-player%::broke::jungle_sapling}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is acacia sapling:
                add 1 to {blocksnature::%loop-player%::broke::acacia_sapling}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is dark oak sapling:
                add 1 to {blocksnature::%loop-player%::broke::dark_oak_sapling}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is mangrove propagule:
                add 1 to {blocksnature::%loop-player%::broke::mangrove_propagule}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - AZALEE FIORITE - #
            else if event-block is: azalea
                add 1 to {blocksnature::%loop-player%::broke::azalea}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: flowering azalea
                add 1 to {blocksnature::%loop-player%::broke::flowering_azalea}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - FIORI E VEGETAZIONE - #
            else if event-block is: poppy
                add 1 to {blocksnature::%loop-player%::broke::poppy}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: blue orchid
                add 1 to {blocksnature::%loop-player%::broke::blue_orchid}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: azure bluet
                add 1 to {blocksnature::%loop-player%::broke::azure_bluet}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: red tulip
                add 1 to {blocksnature::%loop-player%::broke::red_tulip}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: orange tulip
                add 1 to {blocksnature::%loop-player%::broke::orange_tulip}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: white tulip
                add 1 to {blocksnature::%loop-player%::broke::white_tulip}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: pink tulip
                add 1 to {blocksnature::%loop-player%::broke::pink_tulip}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: oxeye daisy
                add 1 to {blocksnature::%loop-player%::broke::oxeye_daisy}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: cornflower
                add 1 to {blocksnature::%loop-player%::broke::cornflower}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: lilac
                add 1 to {blocksnature::%loop-player%::broke::lilac}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: rose bush
                add 1 to {blocksnature::%loop-player%::broke::rose_bush}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: peony
                add 1 to {blocksnature::%loop-player%::broke::peony}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: spore blossom
                add 1 to {blocksnature::%loop-player%::broke::spore_blossom}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: whiter rose
                add 1 to {blocksnature::%loop-player%::broke::whiter_rose}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: bamboo
                add 1 to {blocksnature::%loop-player%::broke::bamboo}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: sugar cane
                add 1 to {blocksnature::%loop-player%::broke::sugar_cane}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: cactus
                add 1 to {blocksnature::%loop-player%::broke::cactus}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
            else if event-block is: kelp
                add 1 to {blocksnature::%loop-player%::broke::kelp}
                add 1 to {blocksnature::%loop-player%::broke}
                add 1 to {item::%loop-player%::broke::overworld}
    # - SEMI E BLOCCHI DI ZUCCA, ANGURIA E FIENO - #