options:
    prefix: &b[&6&lIP&b]

command /ip [<text>] [<offline player>]:
    permission: ip.admin
    permission message: {@prefix} &cComando sconosciuto.
    description: Visualizza l'IP del server o di un giocatore.
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "{@prefix} &eL'IP del server è &a%{server.ip.named}%&e."
                    stop

            else if arg-1 is "server":
                if arg-2 isn't set:
                    send "{@prefix} &eL'IP del server è &a%{server.ip.named}%&e."
                    stop
                else:
                    send "{@prefix} &cQuesto comando non richiede parametri aggiuntivi."
                    stop

            else if arg-1 is "player":
                if arg-2 isn't set:
                    send "{@prefix} &cSpecifica il nome di un giocatore."
                    stop
                else if arg-2 is online:
                    send "{@prefix} &eL'IP di &b%arg-2% &eè &a%arg-2's ip%&e."
                    stop
                else if arg-2 is offline:
                    send "{@prefix} &6%arg-2% &cè offline."
                    stop

            else if arg-1 is not "server" or "player":
                send "{@prefix} &cComando sconosciuto."
                send "{@prefix} &cUtilizzo: &6/ip server"
                send "{@prefix} &cUtilizzo: &6/ip player <&egiocatore&6>"
                stop
        else:
            if arg-1 isn't set:
                if arg-2 isn't set:
                    send "{@prefix} &eL'IP del server è &a%{server.ip.named}%&e." to console
                    stop

            else if arg-1 is "server":
                if arg-2 isn't set:
                    send "{@prefix} &eL'IP del server è &a%{server.ip.named}%&e." to console
                    stop
                else:
                    send "{@prefix} &cQuesto comando non richiede parametri aggiuntivi." to console
                    stop

            else if arg-1 is "player":
                if arg-2 isn't set:
                    send "{@prefix} &cSpecifica il nome di un giocatore." to console
                    stop
                else if arg-2 is online:
                    send "{@prefix} &eL'IP di &b%arg-2% &eè &a%arg-2's ip%&e." to console
                    stop
                else if arg-2 is offline:
                    send "{@prefix} &6%arg-2% &cè offline." to console
                    stop

            else if arg-1 is not "server" or "player":
                send "{@prefix} &cComando sconosciuto." to console
                send "{@prefix} &cUtilizzo: &6/ip server" to console
                send "{@prefix} &cUtilizzo: &6/ip player <&egiocatore&6>" to console
                stop

on tab complete of "/ip":
    if player has permission "ip.admin":
        set tab completions for position 1 to "server" and "player"

command /myip:
    description: Visualizza l'IP del giocatore che esegue il comando.
    executable by: player, console
    trigger:
        if sender is player:
            send "{@prefix} &eIl tuo IP è &a%player's ip%&e." to player
            stop
        else:
            send "{@prefix} &eL'IP del server è &a%{server.ip.named}%" to console
            stop