on right click:
    if event-item is compass named "&cTPR rapido &7(Click destro)" with lore "&7Teletrasportati in un punto", "&7a caso nel mondo con un" and "&7semplice click.":
        execute player command "/tpr"

command /tprcompass:
    description: "Una bussola che ti teletrasporta? Ok!" 
    trigger:
        give 1 compass named "&cTPR rapido &7(Click destro)" with lore "&7Teletrasportati in un punto", "&7a caso nel mondo con un" and "&7semplice click." to player
        play sound "entity.item.pickup" with volume 1 and pitch 2 at player for player
        stop