on load:
    if {arenacombat.status} isn't set:
        set {arenacombat.status} to false

command /arenacombat:
    permission: arenacombat.toggle
    permission message: %{server.prefix.main}% &cComando sconosciuto.
    executable by: player, console
    trigger:
        if {arenacombat.status} is false:
            set {arenacombat.status} to true
            broadcast "%{server.prefix.main}% &cModalità combattimento Arena attivata!"
            send "%{server.prefix.main}% &6Le tue statistiche sanguinarie rimarranno invariate durante i combattimenti." to all players
            stop
        else:
            set {arenacombat.status} to false
            broadcast "%{server.prefix.main}% &aModalità combattimento Arena disattivata!"
            send "%{server.prefix.main}% &6Le tue statistiche sanguinarie subiranno modifiche durante i combattimenti." to all players
            stop

every tick:
    loop all players:
        if {arenacombat.status} is true:
            send action bar "&a&lMODALITÀ ARENA ATTIVA" to loop-player