options:
    prefix: &6[&cPlayTime&6]
    prefix_tip: &2&k0&c&lTIP&2&k0

    confirm_sound: play sound "block.note_block.pling" with volume 1 and pitch 2

    no_more_args: &cQuesto comando non richiede parametri aggiuntivi.

    permission: playtime.other

# UPDATE VARIABILI
on join:
    if {playtime.%player%.days}, {playtime.%player%.hours}, {playtime.%player%.minutes}, {playtime.%player%.seconds}, {playtime.%player%.total_days}, {playtime.%player%.total_hours}, {playtime.%player%.total_minutes}, {playtime.%player%.total_seconds}, {playtime.%player%.archived_days}, {playtime.%player%.archived_hours}, {playtime.%player%.archived_minutes}, {playtime.%player%.archived_seconds} or {playtime.%player%.first_login} is set:
        set {playtime.last_session.days.%player%} to {playtime.%player%.archived_days}
        set {playtime.last_session.hours.%player%} to {playtime.%player%.archived_hours}
        set {playtime.last_session.minutes.%player%} to {playtime.%player%.archived_minutes}
        set {playtime.last_session.seconds.%player%} to {playtime.%player%.archived_seconds}

        set {playtime.actual_session.days.%player%} to {playtime.%player%.days}
        set {playtime.actual_session.hours.%player%} to {playtime.%player%.hours}
        set {playtime.actual_session.minutes.%player%} to {playtime.%player%.minutes}
        set {playtime.actual_session.seconds.%player%} to {playtime.%player%.seconds}

        set {playtime.first_login.%player%} to {playtime.%player%.first_login}
        wait 1 second
        delete {playtime.%player%.days}, {playtime.%player%.hours}, {playtime.%player%.minutes}, {playtime.%player%.seconds}, {playtime.%player%.total_days}, {playtime.%player%.total_hours}, {playtime.%player%.total_minutes}, {playtime.%player%.total_seconds}, {playtime.%player%.archived_days}, {playtime.%player%.archived_hours}, {playtime.%player%.archived_minutes}, {playtime.%player%.archived_seconds} and {playtime.%player%.first_login}
        {@confirm_sound} at player for player
        send ""
        send "{@prefix} &c&lNOTIFICA DI AGGIORNAMENTO"
        send " &6Ci sono stati degli aggiornamenti riguardo il tuo tempo di gioco!"
        send " &aQuesto aggiornamento include variabili nuove e ottimizzate, il counter è stato fixato e adesso terrà in modo corretto il tuo tempo di gioco totale, online e offline."
        send " &cPer evitare problemi durante l'ottimizzazione delle variabili, i tuoi tempi di gioco sono stati azzerati."
        send " &aPuoi utilizzare &e/ab pt &6session&e, &6total &eo &6both &aper consultare il tuo tempo di gioco in tempo reale."
        send " &bGrazie di giocare e sostenere la %{server.name}%!"
        send ""

on join:
    if player has not played before:
        if {playtime.first_login.%player%} isn't set:
            set {playtime.first_login.%player%} to now
    if {playtime.sessions.%player%} isn't set:
        set {playtime.sessions.%player%} to 0

on join:
    set {playtime.actual_session.days.%player%} to 0
    set {playtime.actual_session.hours.%player%} to 0
    set {playtime.actual_session.minutes.%player%} to 0
    set {playtime.actual_session.seconds.%player%} to 0
    delete {playtime.last_session.days.%player%}
    delete {playtime.last_session.hours.%player%}
    delete {playtime.last_session.minutes.%player%}
    delete {playtime.last_session.seconds.%player%}
    if {playtime.total.days.%player%} isn't set:
        set {playtime.total.days.%player%} to 0
    if {playtime.total.hours.%player%} isn't set:
        set {playtime.total.hours.%player%} to 0
    if {playtime.total.minutes.%player%} isn't set:
        set {playtime.total.minutes.%player%} to 0
    if {playtime.total.seconds.%player%} isn't set:
        set {playtime.total.seconds.%player%} to 0

on quit:
    log "[PLAYTIME] Nella sua ultima sessione di gioco, %player% ha giocato per %{playtime.actual_session.days.%player%}% giorni, %{playtime.actual_session.hours.%player%}% ore, %{playtime.actual_session.minutes.%player%}% minuti e %{playtime.actual_session.seconds.%player%}% secondi." to "Sessioni di gioco.log"
    set {playtime.last_session.days.%player%} to {playtime.actual_session.days.%player%}
    set {playtime.last_session.hours.%player%} to {playtime.actual_session.hours.%player%}
    set {playtime.last_session.minutes.%player%} to {playtime.actual_session.minutes.%player%}
    set {playtime.last_session.seconds.%player%} to {playtime.actual_session.seconds.%player%}
    wait 2 ticks
    delete {playtime.actual_session.days.%player%}
    delete {playtime.actual_session.hours.%player%}
    delete {playtime.actual_session.minutes.%player%}
    delete {playtime.actual_session.seconds.%player%}
    add 1 to {playtime.sessions.%player%}
    set {playtime.last_seen.%player%} to now

command /playtime [<text>] [<offline player>]:
    aliases: /pt
    description: "Tieni d'occhio il tuo tempo di gioco."
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                send ""
                send "&e&lIL TUO TEMPO DI GIOCO"
                send " &7In questa sessione hai giocato per &c%{playtime.actual_session.days.%player%}% giorni&7, &c%{playtime.actual_session.hours.%player%}% ore&7, &c%{playtime.actual_session.minutes.%player%}% minuti &7e &c%{playtime.actual_session.seconds.%player%}% secondi&7."
                send " &7In totale hai giocato per &c%{playtime.total.days.%player%}% giorni&7, &c%{playtime.total.hours.%player%}% ore&7, &c%{playtime.total.minutes.%player%}% minuti &7e &c%{playtime.total.seconds.%player%}% secondi&7."
                send ""
                stop
            else if arg-1 is "session":
                if arg-2 isn't set:
                    send "{@prefix} &7In questa sessione hai giocato per &c%{playtime.actual_session.days.%player%}% giorni&7, &c%{playtime.actual_session.hours.%player%}% ore&7, &c%{playtime.actual_session.minutes.%player%}% minuti &7e &c%{playtime.actual_session.seconds.%player%}% secondi&7."
                    stop
                else if arg-2 is online:
                    if player has permission "{@permission}":
                        send "{@prefix} &7In questa sessione, &6%arg-2% &7ha giocato per &c%{playtime.actual_session.days.%arg-2%}% giorni&7, &c%{playtime.actual_session.hours.%arg-2%}% ore&7, &c%{playtime.actual_session.minutes.%arg-2%}% minuti &7e &c%{playtime.actual_session.seconds.%arg-2%}% secondi&7."
                        stop
                    else:
                        send "{@prefix} {@no_more_args}"
                        stop
                else:
                    if arg-2 has played before:
                        if player has permission "{@permission}":
                            send "{@prefix} &7Nella sua ultima sessione, &6%arg-2% &7ha giocato per &c%{playtime.last_session.days.%arg-2%}% giorni&7, &c%{playtime.last_session.hours.%arg-2%}% ore&7, &c%{playtime.last_session.minutes.%arg-2%}% minuti &7e &c%{playtime.last_session.seconds.%arg-2%}% secondi&7."
                            stop
                        else:
                            send "{@prefix} {@no_more_args}"
                            stop
                    else:
                        if player has permission "{@permission}":
                            send "{@prefix} &cNon ho trovato dati per &6%arg-2%&c."
                            stop
                        else:
                            send "{@prefix} {@no_more_args}"
                            stop
            else if arg-1 is "total":
                if arg-2 isn't set:
                    send "{@prefix} &7In totale hai giocato per &c%{playtime.total.days.%player%}% giorni&7, &c%{playtime.total.hours.%player%}% ore&7, &c%{playtime.total.minutes.%player%}% minuti &7e &c%{playtime.total.seconds.%player%}% secondi&7."
                    stop
                else:
                    if arg-2 has played before:
                        if player has permission "{@permission}":
                            send "{@prefix} &7In totale, &6%arg-2% &7ha giocato per &c%{playtime.total.days.%arg-2%}% giorni&7, &c%{playtime.total.hours.%arg-2%}% ore&7, &c%{playtime.total.minutes.%arg-2%}% minuti &7e &c%{playtime.total.seconds.%arg-2%}% secondi&7."
                            stop
                        else:
                            send "{@prefix} {@no_more_args}"
                            stop
                    else:
                        if player has permission "{@permission}":
                            send "{@prefix} &cNon ho trovato dati per &6%arg-2%&c."
                            stop
                        else:
                            send "{@prefix} {@no_more_args}"
                            stop
        else:
            if arg-1 isn't set:
                send "{@prefix} &cSolo i giocatori possono eseguire questo comando."
                stop
            else if arg-1 is "session":
                if arg-2 isn't set:
                    send "{@prefix} &cSpecifica il nome di un giocatore!"
                    stop
                else if arg-2 is online:
                    send "{@prefix} &7In questa sessione, &6%arg-2% &7ha giocato per &c%{playtime.actual_session.days.%arg-2%}% giorni&7, &c%{playtime.actual_session.hours.%arg-2%}% ore&7, &c%{playtime.actual_session.minutes.%arg-2%}% minuti &7e &c%{playtime.actual_session.seconds.%arg-2%}% secondi&7."
                    stop
                else:
                    if arg-2 has played before:
                        send "{@prefix} &7Nella sua ultima sessione, &6%arg-2% &7ha giocato per &c%{playtime.last_session.days.%arg-2%}% giorni&7, &c%{playtime.last_session.hours.%arg-2%}% ore&7, &c%{playtime.last_session.minutes.%arg-2%}% minuti &7e &c%{playtime.last_session.seconds.%arg-2%}% secondi&7."
                        stop
                    else:
                        send "{@prefix} &cNon ho trovato dati per &6%arg-2%&c."
                        stop
            else if arg-1 is "total":
                if arg-2 isn't set:
                    send "{@prefix} &cSpecifica il nome di un giocatore!"
                    stop
                else:
                    if arg-2 has played before:
                        send "{@prefix} &7In totale, &6%arg-2% &7ha giocato per &c%{playtime.total.days.%arg-2%}% giorni&7, &c%{playtime.total.hours.%arg-2%}% ore&7, &c%{playtime.total.minutes.%arg-2%}% minuti &7e &c%{playtime.total.seconds.%arg-2%}% secondi&7."
                        stop
                    else:
                        send "{@prefix} &cNon ho trovato dati per &6%arg-2%&c."
                        stop

on tab complete of "/playtime" or "/pt":
    set tab completions for position 1 to "total" and "session"
    if player has permission "{@permission}":
        set tab completions for position 2 to {players::*}
    
every hour:
    loop all players:
        if {playtime.actual_session.hours.%loop-player%} = 23:
            set {playtime.actual_session.hours.%loop-player%} to 0
            add 1 to {playtime.actual_session.days.%loop-player%}

        if {playtime.total.hours.%loop-player%} = 23:
            set {playtime.total.hours.%loop-player%} to 0
            add 1 to {playtime.total.days.%loop-player%}

every minute:
    loop all players:
        if {playtime.actual_session.minutes.%loop-player%} = 59:
            set {playtime.actual_session.minutes.%loop-player%} to 0
            if {playtime.actual_session.hours.%loop-player%} != 23:
                add 1 to {playtime.actual_session.hours.%loop-player%}
        
        if {playtime.total.minutes.%loop-player%} = 59:
            set {playtime.total.minutes.%loop-player%} to 0
            if {playtime.total.hours.%loop-player%} != 23:
                add 1 to {playtime.total.hours.%loop-player%}

every second:
    loop all players:
        if {playtime.actual_session.seconds.%loop-player%} < 59:
            add 1 to {playtime.actual_session.seconds.%loop-player%}
        else:
            set {playtime.actual_session.seconds.%loop-player%} to 0
            if {playtime.actual_session.minutes.%loop-player%} != 59:
                add 1 to {playtime.actual_session.minutes.%loop-player%}

        if {playtime.total.seconds.%loop-player%} < 59:
            add 1 to {playtime.total.seconds.%loop-player%}
        else:
            set {playtime.total.seconds.%loop-player%} to 0
            if {playtime.total.minutes.%loop-player%} != 59:
                add 1 to {playtime.total.minutes.%loop-player%}

every 10 tick:
    loop all players:
        if {actionbar.playtime.session.%loop-player%} is true:
            send action bar "&aTempo della sessione: &f%{playtime.actual_session.days.%loop-player%}%:%{playtime.actual_session.hours.%loop-player%}%:%{playtime.actual_session.minutes.%loop-player%}%:%{playtime.actual_session.seconds.%loop-player%}%" to loop-player
        else if {actionbar.playtime.total.%loop-player%} is true:
            send action bar "&bTempo totale: &f%{playtime.total.days.%loop-player%}%:%{playtime.total.hours.%loop-player%}%:%{playtime.total.minutes.%loop-player%}%:%{playtime.total.seconds.%loop-player%}%" to loop-player
        else if {actionbar.playtime.both.%loop-player%} is true:
            send action bar "&aSessione: &f%{playtime.actual_session.days.%loop-player%}%:%{playtime.actual_session.hours.%loop-player%}%:%{playtime.actual_session.minutes.%loop-player%}%:%{playtime.actual_session.seconds.%loop-player%}%  &7|  &bTotale: &f%{playtime.total.days.%loop-player%}%:%{playtime.total.hours.%loop-player%}%:%{playtime.total.minutes.%loop-player%}%:%{playtime.total.seconds.%loop-player%}%" to loop-player