#
# DIPENDENZE:
#
# - SkBee
# - skript-yaml
#

options:
    fall: &x&f&b&a&6&0&0A&x&e&c&9&7&0&0u&x&d&d&8&8&0&0t&x&c&e&7&a&0&0u&x&b&e&6&b&0&0n&x&a&f&5&c&0&0n&x&a&0&4&d&0&0o
    winter: &x&0&0&b&0&f&bI&x&2&1&b&3&f&2n&x&4&1&b&6&e&8v&x&6&2&b&a&d&fe&x&8&2&b&d&d&6r&x&a&3&c&0&c&cn&x&c&3&c&3&c&3o
    spring: &x&0&4&f&b&2&bP&x&0&4&f&2&4&6r&x&0&3&e&9&6&0i&x&0&3&e&0&7&bm&x&0&2&d&7&9&5a&x&0&2&c&e&b&0v&x&0&1&c&5&c&ae&x&0&1&b&c&e&5r&x&0&0&b&3&f&fa&a
    summer: &x&f&b&e&2&0&0E&x&f&c&c&7&0&0s&x&f&d&a&c&0&0t&x&f&d&9&2&0&0a&x&f&e&7&7&0&0t&x&f&f&5&c&0&0e
    
    no: &c✖
    yes: &a✔
    
    file_p: "settings-%player's uuid%"
    file_arg: "settings-%arg-1's uuid%"
    file_lp: "settings-%loop-player's uuid%"
    scoreboard: yaml value "personalization.scoreboard.enabled"
    scoreboard_marker: yaml value "personalization.scoreboard.marker"
    no_scoreboard: yaml value "notify.generic.no_scoreboard.enabled"
    no_scoreboard_marker: yaml value "notify.generic.no_scoreboard.marker"

every second:
    loop all players:
        if weather in "%{server.world.overworld}%" is clear:
            set {_weather} to placeholder "rs_season_%{server.world.overworld}%" from loop-player
            if time in "%{server.world.overworld}%" is between 6:00 and 19:00:
                if {_weather} is not "{@winter}" or "{@fall}":
                    set {rs_weather} to "&e☀"
                else:
                    set {rs_weather} to "&7☁"
            else:
                set {rs_weather} to "&9☽"
        if weather in "%{server.world.overworld}%" is rain:
            set {rs_weather} to "%{rs_weather.rain}%"
        if weather in "%{server.world.overworld}%" is thunder:
            set {rs_weather} to "%{rs_weather.thunder}%"

every tick:
    loop all players:
        set {_weekday} to placeholder "rs_weekday_%{server.world.overworld}%" from loop-player
        if {week.day} is set:
            delete {week.day}
        if {_weekday} is "Lunedì":
            set {rs.week_day} to "Lun"
        else if {_weekday} is "Martedì":
            set {rs.week_day} to "Mar"
        else if {_weekday} is "Mercoledì":
            set {rs.week_day} to "Mer"
        else if {_weekday} is "Giovedì":
            set {rs.week_day} to "Gio"
        else if {_weekday} is "Venerdì":
            set {rs.week_day} to "Ven"
        else if {_weekday} is "Sabato":
            set {rs.week_day} to "Sab"
        else if {_weekday} is "Domenica":
            set {rs.week_day} to "Dom"

every 5 seconds:
    loop all players:
        set {_weather_rain} to placeholder "rs_season_%{server.world.overworld}%" from loop-player
        if {_weather_rain} is not "{@winter}":
            set {rs_weather.rain} to "&b🌧"
            wait 2 seconds
            set {rs_weather.rain} to "&3🌧"
        else:
            set {rs_weather.rain} to "&b❄"
            wait 2 seconds
            set {rs_weather.rain} to "&3❄"

every 5 seconds:
    loop all players:
        set {_weather_thunder} to placeholder "rs_season_%{server.world.overworld}%" from loop-player
        set {rs_weather.thunder} to "&7⛈"
        wait 2 seconds
        set {rs_weather.thunder} to "&8⛈"

every tick:
    loop all players:
        if {@scoreboard} in {@file_lp} is true:
            if world of loop-player is "%{server.world.overworld}%":
                set title of loop-player's scoreboard to {animation.UltraSMP}
                set line 1 of loop-player's scoreboard to "%placeholder "rs_season" from loop-player% [ %placeholder "rs_temperature" from loop-player% ]"
                set line 2 of loop-player's scoreboard to "&fStagione %{rs_weather}%"
                set line 3 of loop-player's scoreboard to ""
                set line 4 of loop-player's scoreboard to "&b%placeholder "player_biome_capitalized" from loop-player%"
                set line 5 of loop-player's scoreboard to "&fBioma"
                set line 6 of loop-player's scoreboard to ""
                set line 7 of loop-player's scoreboard to "&a%placeholder "player_x" from loop-player% %placeholder "player_y" from loop-player% %placeholder "player_z" from loop-player% &8[&b&l%placeholder "player_direction" from loop-player%&8]"
                set line 8 of loop-player's scoreboard to "&fCoordinate"
                set line 9 of loop-player's scoreboard to ""
                set line 10 of loop-player's scoreboard to placeholder "tab_placeholder_player_empty_slots" from loop-player 
                set line 11 of loop-player's scoreboard to "&fInventario"
                set line 12 of loop-player's scoreboard to ""
                set line 13 of loop-player's scoreboard to "&fVita: &c%placeholder "auraskills_hp" from loop-player%/%placeholder "auraskills_hp_max" from loop-player% ❤"
                set line 14 of loop-player's scoreboard to ""
                set line 15 of loop-player's scoreboard to "&7%{rs.week_day}% %placeholder "rs_day_smp" from loop-player%/%placeholder "rs_month_smp" from loop-player%/%placeholder "rs_year_smp" from loop-player% &f- &b%placeholder "rs_time_smp" from loop-player%"
            else if world of loop-player is "%{server.world.nether}%":
                set title of loop-player's scoreboard to {animation.UltraSMP}
                set line 1 of loop-player's scoreboard to placeholder "rs_season_%{server.world.overworld}%" from loop-player
                set line 2 of loop-player's scoreboard to "&fStagione %{rs_weather}%"
                set line 3 of loop-player's scoreboard to ""
                set line 4 of loop-player's scoreboard to "&c%placeholder "player_biome_capitalized" from loop-player%"
                set line 5 of loop-player's scoreboard to "&fBioma"
                set line 6 of loop-player's scoreboard to ""
                set line 7 of loop-player's scoreboard to "&6%placeholder "player_x" from loop-player% %placeholder "player_y" from loop-player% %placeholder "player_z" from loop-player% &8[&c&l%placeholder "player_direction" from loop-player%&8]"
                set line 8 of loop-player's scoreboard to "&fCoordinate"
                set line 9 of loop-player's scoreboard to ""
                set line 10 of loop-player's scoreboard to placeholder "tab_placeholder_player_empty_slots" from loop-player 
                set line 11 of loop-player's scoreboard to "&fInventario"
                set line 12 of loop-player's scoreboard to ""
                set line 13 of loop-player's scoreboard to "&fVita: &c%placeholder "auraskills_hp" from loop-player%/%placeholder "auraskills_hp_max" from loop-player% ❤"
                set line 14 of loop-player's scoreboard to ""
                set line 15 of loop-player's scoreboard to "&7%{rs.week_day}% %placeholder "rs_day_smp" from loop-player%/%placeholder "rs_month_smp" from loop-player%/%placeholder "rs_year_smp" from loop-player% &f- &6%placeholder "rs_time_smp" from loop-player%"
            else if world of loop-player is "%{server.world.end}%":
                set title of loop-player's scoreboard to {animation.UltraSMP}
                set line 1 of loop-player's scoreboard to placeholder "rs_season_%{server.world.overworld}%" from loop-player
                set line 2 of loop-player's scoreboard to "&fStagione %{rs_weather}%"
                set line 3 of loop-player's scoreboard to ""
                set line 4 of loop-player's scoreboard to "&5%placeholder "player_biome_capitalized" from loop-player%"
                set line 5 of loop-player's scoreboard to "&fBioma"
                set line 6 of loop-player's scoreboard to ""
                set line 7 of loop-player's scoreboard to "&d%placeholder "player_x" from loop-player% %placeholder "player_y" from loop-player% %placeholder "player_z" from loop-player% &8[&5&l%placeholder "player_direction" from loop-player%&8]"
                set line 8 of loop-player's scoreboard to "&fCoordinate"
                set line 9 of loop-player's scoreboard to ""
                set line 10 of loop-player's scoreboard to placeholder "tab_placeholder_player_empty_slots" from loop-player 
                set line 11 of loop-player's scoreboard to "&fInventario"
                set line 12 of loop-player's scoreboard to ""
                set line 13 of loop-player's scoreboard to "&fVita: &c%placeholder "auraskills_hp" from loop-player%/%placeholder "auraskills_hp_max" from loop-player% ❤"
                set line 14 of loop-player's scoreboard to ""
                set line 15 of loop-player's scoreboard to "&7%{rs.week_day}% %placeholder "rs_day_smp" from loop-player%/%placeholder "rs_month_smp" from loop-player%/%placeholder "rs_year_smp" from loop-player% &f- &5%placeholder "rs_time_smp" from loop-player%"
        else:
            clear scoreboard of loop-player

every hour: # AVVISO SCOREBOARD DISATTIVATA
    loop all players:
        if {@scoreboard} in {@file_lp} is false:
            if {@no_scoreboard} in {@file_lp} is true:
                send "" to loop-player
                send "%{server.prefix.main}% &4&lNOTIFICA GENERALE" to loop-player
                send "" to loop-player
                send "%{server.prefix.main}% &cHo notato che la tua scoreboard non è attivata." to loop-player
                send "%{server.prefix.main}% &6Attivala con <ttp:&fClicca qui per attivare la scoreboard><cmd:/sb>&e&n/sb<reset> &6per avere tutte le informazioni di cui hai bisogno a vista d'occhio." to loop-player
                send "" to loop-player
                send "" to loop-player
                send "%{server.prefix.main}% &ePuoi disattivare questa notifica in &fImpostazioni &epresso il &7Profilo &7&lSMP&e." to loop-player
                send "" to loop-player
                play sound "block.note_block.pling" with volume 1 and pitch 2 at loop-player for loop-player

command /sb [<offline player>]:
    executable by: player, console
    trigger:
        if sender is player:
            if arg-1 isn't set:
                if {@scoreboard} in {@file_p} is false:
                    set {@scoreboard} in {@file_p} to true
                    set {@scoreboard_marker} in {@file_p} to "{@yes}"
                    play sound "entity.player.levelup" with volume 1 and pitch 2 at player for player
                    send "%{server.prefix.main}% &aLa tua scoreboard è stata attivata."
                    stop
                else:
                    set {@scoreboard} in {@file_p} to false
                    set {@scoreboard_marker} in {@file_p} to "{@no}"
                    play sound "block.beacon.deactivate" with volume 1 at player for player
                    send "%{server.prefix.main}% &cLa tua scoreboard è stata disattivata."
                    stop
            else:
                if arg-1 is online:
                    if player has permission "sb.toggle.other":
                        if {@scoreboard} in {@file_arg} is false:
                            set {@scoreboard} in {@file_arg} to true
                            set {@scoreboard_marker} in {@file_arg} to "{@yes}"
                            send "%{server.prefix.main}% &aLa tua scoreboard è stata attivata da &e%player%&a." to arg-1
                            send "%{server.prefix.main}% &aScoreboard attivata per &e%arg-1%&a." to player
                            play sound "entity.player.levelup" with volume 1 and pitch 2 at arg-1 for arg-1
                            stop
                        else:
                            set {@scoreboard} in {@file_arg} to false
                            set {@scoreboard_marker} in {@file_arg} to "{@no}"
                            send "%{server.prefix.main}% &cLa tua scoreboard è stata disattivata da &6%player%&c." to arg-1
                            send "%{server.prefix.main}% &cScoreboard disattivata per &6%arg-1%&c." to player
                            play sound "block.beacon.deactivate" with volume 1 at arg-1 for arg-1
                            stop
                    else:
                        send "%{server.prefix.main}% &cNon hai il permesso di gestire la scoreboard altrui!"
                        play sound "entity.enderman.teleport" with volume 1 and pitch 0 at arg-1 for arg-1
                        stop
                else:
                    if player has permission "sb.toggle.other":
                        send "%{server.prefix.main}% &c%arg-1% &6non è online!"
                        stop
                    else:
                        send "%{server.prefix.main}% &cNon hai il permesso di gestire la scoreboard altrui!"
                        play sound "entity.enderman.teleport" with volume 1 and pitch 0 at arg-1 for arg-1
                        stop
        else:
            if arg-1 isn't set:
                send "%{server.prefix.main}% &cSolo i giocatori possono gestire la propria scoreboard!"
                stop
            else if arg-1 is online:
                if {@scoreboard} in {@file_arg} is false:
                    set {@scoreboard} in {@file_arg} to true
                    set {@scoreboard_marker} in {@file_arg} to "{@yes}"
                    send "%{server.prefix.main}% &aLa tua scoreboard è stata attivata dalla &econsole&a." to arg-1
                    send "%{server.prefix.main}% &aScoreboard attivata per &e%arg-1%&a." to console
                    play sound "entity.player.levelup" with volume 1 and pitch 2 at arg-1 for arg-1
                    stop
                else:
                    set {@scoreboard} in {@file_arg} to false
                    set {@scoreboard_marker} in {@file_arg} to "{@no}"
                    send "%{server.prefix.main}% &cLa tua scoreboard è stata disattivata dalla &6console&c." to arg-1
                    send "%{server.prefix.main}% &cScoreboard disattivata per &6%arg-1%&c." to console
                    play sound "block.beacon.deactivate" with volume 1 at arg-1 for arg-1
                    stop
            else:
                if player has permission "sb.toggle.other":
                    send "%{server.prefix.main}% &c%arg-1% &6non è online!"
                    stop