command /broadcast [<text>]:
	aliases: /annuncio
	permission: broadcast.use
	permission message: &8[&4&lINFO&8] &cNon puoi fare annunci!
	description: Annuncia qualcosa nel server.
	trigger:
		if arg-1 is not set:
			send "&e[&6&lBROADCAST&e] &cCosa vuoi annunciare?" to sender
			stop
		else:
			broadcast "&c[&aAnnuncio&c]&r %arg-1%"
			play sound "entity.experience_orb.pickup" with volume 1 and pitch 0 at all players
			stop