on join:
    wait 5 seconds
    send ""
    send "&e&lAVVISO!"
    send " &aDurante il periodo estivo (&6luglio e agosto&a) l'%{server.name}% sarà chiusa."
    send " &bLa chiusurà avrà inizio il &e&l26 giugno 2024 &balle &e&l22:30&b."
    send " &bVerrà riaperta l'&e&l1 settembre &balle &e&l11:00 &b(imprevisti esclusi!)."
    send " &6&lL'%{server.name}% ti augura una buona estate!"
    send ""
    play sound "block.note_block.pling" with volume 1 and pitch 2 at player for player