# QUI SI TROVANO TUTTE LE VARIABILI GLOBALI PRESENTI NELLA ULTRA SMP.

options:
    version: "&4&lBETA &7v0.16"

on load:
    set {server.version} to {@version}


variables:
# NOME SERVER
    {server.name} = "Ultra SMP"
    {server.name_CAPS} = "ULTRA SMP"

# IP SERVER
    {server.ip.named} = "ultrasmp.org"
    {server.ip} = "-"
    {server.port} = "24368"

# PREFISSI
    {server.prefix.main} = "&4[&6&lS&e&lM&6&lP&4]"

# SESSO GIOCATORI
    {server.genre.male} = "&9Maschio"
    {server.genre.female} = "&dFemmina"

# MONDI
    {server.world.overworld} = "smp"
    {server.world.nether} = "smp_nether"
    {server.world.end} = "smp_the_end"