options:
    dir: plugins/Dati Giocatori/Generali
    data: "data-%player's uuid%"

    status: &cNessuno stato impostato.
    no_flags: "{hide_additional_tooltip:{}}"

    on: Sì
    off: No

on join:
    load yaml "{@dir}/%player's uuid%.yml" as {@data}
    set {_player_hp} to placeholder "auraskills_hp" from player
    set {_player_hp_max} to placeholder "auraskills_hp_max" from player
    set {_player_xp} to placeholder "player_current_exp" from player
    set {_player_xp_level} to placeholder "player_level" from player
    set {_player_x} to placeholder "player_x" from player
    set {_player_y} to placeholder "player_y" from player
    set {_player_z} to placeholder "player_z" from player
    set {_player_biome} to placeholder "player_biome_capitalized" from player
    set {_player_ip} to placeholder "player_ip" from player
    set {_player_op} to placeholder "player_is_op" from player
    set {_player_strength} to placeholder "auraskills_strength" from player
    set {_player_health} to placeholder "auraskills_health" from player
    set {_player_regeneration} to placeholder "auraskills_regeneration" from player
    set {_player_luck} to placeholder "auraskills_luck" from player
    set {_player_wisdom} to placeholder "auraskills_wisdom" from player
    set {_player_toughness} to placeholder "auraskills_toughness" from player
    set {_player_crit_chance} to placeholder "auraskills_crit_chance" from player
    set {_player_crit_damage} to placeholder "auraskills_crit_damage" from player
    set {_player_speed} to placeholder "auraskills_speed" from player
    set yaml value "player_info.player.name" in {@data} to player's name
    set yaml value "player_info.player.uuid" in {@data} to player's uuid
    set yaml value "player_info.player.nickname" in {@data} to player's name
    set yaml value "player_info.player.status.new" in {@data} to "{@status}"
    set yaml value "player_info.player.status.old" in {@data} to "-"
    set yaml value "player_info.player.gamemode.info" in {@data} to "Creativa" #"Sopravvivenza"
    set yaml value "player_info.player.gamemode.id" in {@data} to grass block #iron sword with nbt from {@no_flags}
    set yaml value "player_info.player.xp" in {@data} to "%regex({_player_xp_level})% (%regex({_player_xp})%)"
    set yaml value "player_info.player.speed.fly" in {@data} to player's flyspeed
    set yaml value "player_info.player.speed.walk" in {@data} to player's walkspeed
    set yaml value "player_info.player.info.op" in {@data} to uncolored {_player_op}
    set yaml value "player_info.player.info.god" in {@data} to false
    set yaml value "player_info.player.info.fly" in {@data} to false
    set yaml value "player_info.player.info.freeze" in {@data} to false
    set yaml value "player_info.player.info.afk" in {@data} to false
    set yaml value "player_info.energy.health" in {@data} to "%regex({_player_hp})%/%regex({_player_hp_max})%"
    set yaml value "player_info.energy.saturation" in {@data} to "%regex(player's food level)%/10"
    set yaml value "player_info.position.dimension" in {@data} to uncolored {whois.world.%player%}
    set yaml value "player_info.position.coordinates" in {@data} to "%{_player_x}% %{_player_y}% %{_player_z}%"
    set yaml value "player_info.position.biome" in {@data} to {_player_biome}
    set yaml value "player_info.playtime.session" in {@data} to "%{playtime.actual_session.days.%player%}% giorni, %{playtime.actual_session.hours.%player%}% ore, %{playtime.actual_session.minutes.%player%}% minuti e %{playtime.actual_session.seconds.%player%}% secondi"
    set yaml value "player_info.playtime.total" in {@data} to "%{playtime.total.days.%player%}% giorni, %{playtime.total.hours.%player%}% ore, %{playtime.total.minutes.%player%}% minuti e %{playtime.total.seconds.%player%}% secondi"
    set yaml value "player_info.playtime.sessions" in {@data} to {playtime.sessions.%player%}
    set yaml value "player_info.playtime.first_join" in {@data} to {playtime.first_login.%player%}
    set yaml value "player_info.connection.ip_address" in {@data} to {_player_ip}
    set yaml value "player_info.connection.ping" in {@data} to player's ping
    set yaml value "player_profile.skills.strength" in {@data} to "+%regex({_player_strength})%"
    set yaml value "player_profile.skills.health" in {@data} to "+%regex({_player_health})%"
    set yaml value "player_profile.skills.regeneration" in {@data} to "+%regex({_player_regeneration})%"
    set yaml value "player_profile.skills.luck" in {@data} to "+%regex({_player_luck})%"
    set yaml value "player_profile.skills.wisdom" in {@data} to "+%regex({_player_wisdom})%"
    set yaml value "player_profile.skills.toughness" in {@data} to "+%regex({_player_toughness})%"
    set yaml value "player_profile.skills.crit_chance" in {@data} to "+%regex({_player_crit_chance})%%%"
    set yaml value "player_profile.skills.crit_damage" in {@data} to "+%regex({_player_crit_damage})%%%"
    set yaml value "player_profile.skills.speed" in {@data} to "+%regex({_player_speed})%"
    set yaml value "player_profile.support.reported_bugs" in {@data} to regex({reported_bugs::%player%})
    set yaml value "player_profile.support.feedback_sent" in {@data} to regex({feedback_sent::%player%})
    set yaml value "player_profile.progress.level.smp" in {@data} to {level::%player%}
    if yaml value "player_profile.progress.level.xp" in {@data} isn't set:
        set yaml value "player_profile.progress.level.xp" in {@data} to {level.xp.%player%}
    set yaml value "player_profile.progress.level.xp_until_next_level" in {@data} to "%({level.max.%player%} - {level.xp.%player%})% PE"
    set yaml value "player_profile.progress.fama" in {@data} to regex({fame::%player%})
    set yaml value "player_profile.progress.rank" in {@data} to uncolored {rank.%player%}
    set yaml value "player_profile.progress.bloody_stats.kills" in {@data} to regex({kills::%player%})
    set yaml value "player_profile.progress.bloody_stats.deaths" in {@data} to regex({deaths::%player%})
    set yaml value "player_profile.progress.bloody_stats.kd_ratio" in {@data} to regex({kills::%player%}/{deaths::%player%})
    set yaml value "player_profile.progress.bloody_stats.damage.inflicted" in {@data} to regex({infldamage::%player%})
    set yaml value "player_profile.progress.bloody_stats.damage.suffered" in {@data} to regex({suffdamage::%player%})
    set yaml value "player_profile.progress.bloody_stats.killstreak" in {@data} to "%regex({killstreak::%player%})%/%regex({killstreak_max.%player%})%"
    set yaml value "player_profile.progress.collection_stats.broken_blocks" in {@data} to regex({broken_blocks::%player%})
    set yaml value "player_profile.progress.collection_stats.placed_blocks" in {@data} to regex({placed_blocks::%player%})
    set yaml value "player_profile.progress.collection_stats.fished_loots" in {@data} to regex({fished_loots::%player%})
    set yaml value "player_gui.last_opened_1" in {@data} to "-"
    set yaml value "player_gui.last_opened_2" in {@data} to "-"
    set yaml value "player_gui.last_opened_3" in {@data} to "-"
    set yaml value "player_gui.last_opened_4" in {@data} to "-"
    set yaml value "player_gui.last_opened_5" in {@data} to "-"
    save yaml {@data}

on quit:
    save yaml {@data}
    unload yaml {@data}

every 3 minutes:
    loop all loaded yaml:
        save loop-value
        # We add a small wait between each player data to prevent
        # a massive amount of lag if a lot of players are online
        # Adjust to suit your server's needs
        wait 2 ticks

#command /clearOldData:
    #trigger:
        #set {_n} to 0 # lets create a counter
        #loop all offline players:
            # here we are going to load each offline player's data, and check the difference between now and last-login
            # if grater than 100 days, we will delete their data
            # else we will just unload it and move onto the next
            #load yaml "{@dir}/%uuid of loop-offline player%.yml" as "off-%uuid of loop-offline player%"
            #set {_t} to yaml value "last-login" from "off-%uuid of loop-offline player%"
            #if difference between now and {_t} > 50 days:
                #delete yaml "off-%uuid of loop-offline player%"
                # lets just let the console know we're deleting this
                #send "Deleting data for %loop-offline player%" to console
                # We will add 1 to {_n} so we know how many player data's we cleared
                #add 1 to {_n}
            #else:
                #unload yaml "off-%uuid of loop-offline player%"
            #wait 1 tick
        # Now we tell the console how many data's we cleared
        #send "Removed player data for %{_n}% inactive player(s)" to console