options:
    dir: plugins/Dati Giocatori/Generali
    data: "data-%player's uuid%"

    status: &cNessuno stato impostato.
    no_flags: "{hide_additional_tooltip:{}}"

    on: Sì
    off: No

on join:
    load yaml "{@dir}/%player's uuid%.yml" as {@data}
    if yaml {@data} is empty:
        set {_player_hp} to placeholder "auraskills_hp" from player
        set {_player_hp_max} to placeholder "auraskills_hp_max" from player
        set {_player_xp} to placeholder "player_current_exp" from player
        set {_player_xp_level} to placeholder "player_level" from player
        set {_player_x} to placeholder "player_x" from player
        set {_player_y} to placeholder "player_y" from player
        set {_player_z} to placeholder "player_z" from player
        set {_player_biome} to placeholder "player_biome_capitalized" from player
        set {_player_ip} to placeholder "player_ip" from player
        set {_player_op} to placeholder "player_is_op" from player
        set {_player_strength} to placeholder "auraskills_strength" from player
        set {_player_health} to placeholder "auraskills_health" from player
        set {_player_regeneration} to placeholder "auraskills_regeneration" from player
        set {_player_luck} to placeholder "auraskills_luck" from player
        set {_player_wisdom} to placeholder "auraskills_wisdom" from player
        set {_player_toughness} to placeholder "auraskills_toughness" from player
        set {_player_crit_chance} to placeholder "auraskills_crit_chance" from player
        set {_player_crit_damage} to placeholder "auraskills_crit_damage" from player
        set {_player_speed} to placeholder "auraskills_speed" from player
        set yaml value "player_info.player.name" in {@data} to player's name
        set yaml value "player_info.player.uuid" in {@data} to player's uuid
        set yaml value "player_info.player.status.new" in {@data} to "{@status}"
        set yaml value "player_info.player.status.old" in {@data} to "-"
        set yaml value "player_info.player.gamemode.info" in {@data} to uncolored {gm.%player%} #Sopravvivenza
        set yaml value "player_info.player.gamemode.id" in {@data} to {gm.marker.%player%} #iron sword with nbt from {@no_flags}
        set yaml value "player_info.player.xp.levels" in {@data} to regex({_player_xp_level})
        set yaml value "player_info.player.xp.points" in {@data} to regex({_player_xp})
        set yaml value "player_info.player.flyspeed" in {@data} to player's flyspeed
        set yaml value "player_info.player.walkspeed" in {@data} to player's walkspeed
        set yaml value "player_info.player.op" in {@data} to uncolored {_player_op}
        set yaml value "player_info.player.god" in {@data} to uncolored {god.%player%} #"{@off}"
        set yaml value "player_info.player.fly" in {@data} to uncolored {fly.%player%} #"{@off}"
        set yaml value "player_info.player.freeze" in {@data} to "{@off}"
        set yaml value "player_info.player.afk" in {@data} to "{@off}"
        set yaml value "player_info.energy.health" in {@data} to "%regex({_player_hp})%/%regex({_player_hp_max})%"
        set yaml value "player_info.energy.saturation" in {@data} to "%regex(player's food level)%/10"
        set yaml value "player_info.position.dimension.name" in {@data} to uncolored {whois.world.%player%}
        set yaml value "player_info.position.dimension.id" in {@data} to {whois.world.marker.%player%}
        set yaml value "player_info.position.coordinates" in {@data} to "%{_player_x}% %{_player_y}% %{_player_z}%"
        set yaml value "player_info.position.biome" in {@data} to {_player_biome}
        set yaml value "player_info.playtime.session.days" in {@data} to {playtime.actual_session.days.%player%}
        set yaml value "player_info.playtime.session.hours" in {@data} to {playtime.actual_session.hours.%player%}
        set yaml value "player_info.playtime.session.minutes" in {@data} to {playtime.actual_session.minutes.%player%}
        set yaml value "player_info.playtime.session.seconds" in {@data} to {playtime.actual_session.seconds.%player%}
        set yaml value "player_info.playtime.total.days" in {@data} to {playtime.total.days.%player%}
        set yaml value "player_info.playtime.total.hours" in {@data} to {playtime.total.hours.%player%}
        set yaml value "player_info.playtime.total.minutes" in {@data} to {playtime.total.minutes.%player%}
        set yaml value "player_info.playtime.total.seconds" in {@data} to {playtime.total.seconds.%player%}
        set yaml value "player_info.playtime.sessions" in {@data} to {playtime.sessions.%player%}
        set yaml value "player_info.playtime.first_join" in {@data} to {playtime.first_login.%player%}
        set yaml value "player_info.connectivity.ip_address" in {@data} to {_player_ip}
        set yaml value "player_info.connectivity.ping" in {@data} to player's ping
        set yaml value "player_profile.skills.strength" in {@data} to "+%regex({_player_strength})%"
        set yaml value "player_profile.skills.health" in {@data} to "+%regex({_player_health})%"
        set yaml value "player_profile.skills.regeneration" in {@data} to "+%regex({_player_regeneration})%"
        set yaml value "player_profile.skills.luck" in {@data} to "+%regex({_player_luck})%"
        set yaml value "player_profile.skills.wisdom" in {@data} to "+%regex({_player_wisdom})%"
        set yaml value "player_profile.skills.toughness" in {@data} to "+%regex({_player_toughness})%"
        set yaml value "player_profile.skills.crit_chance" in {@data} to "+%regex({_player_crit_chance})%%%"
        set yaml value "player_profile.skills.crit_damage" in {@data} to "+%regex({_player_crit_damage})%%%"
        set yaml value "player_profile.skills.speed" in {@data} to "+%regex({_player_speed})%"
        set yaml value "player_profile.support.reported_bugs" in {@data} to regex({reported_bugs::%player%})
        set yaml value "player_profile.support.feedback_sent" in {@data} to regex({feedback_sent::%player%})
        set yaml value "player_profile.progress.fama" in {@data} to regex({fame::%player%})
        set yaml value "player_profile.progress.rank" in {@data} to uncolored {rank.%player%}
        set yaml value "player_profile.progress.medals.count" in {@data} to "%{medals.%player%}%/15"
        set yaml value "player_profile.progress.medals.last_obtained" in {@data} to uncolored {medals.%player%.last_obtained}
        set yaml value "player_profile.progress.bloody_stats.kills" in {@data} to regex({kills::%player%})
        set yaml value "player_profile.progress.bloody_stats.deaths" in {@data} to regex({deaths::%player%})
        set yaml value "player_profile.progress.bloody_stats.kd_ratio" in {@data} to regex({kills::%player%}/{deaths::%player%})
        set yaml value "player_profile.progress.bloody_stats.damage.inflicted" in {@data} to regex({infldamage::%player%})
        set yaml value "player_profile.progress.bloody_stats.damage.suffered" in {@data} to regex({suffdamage::%player%})
        set yaml value "player_profile.progress.bloody_stats.killstreak" in {@data} to "%regex({killstreak::%player%})%/%regex({killstreak_max.%player%})%"
        set yaml value "player_profile.progress.mining_stats.broken_blocks" in {@data} to regex({broken_blocks::%player%})
        set yaml value "player_profile.progress.mining_stats.placed_blocks" in {@data} to regex({placed_blocks::%player%})
        save yaml {@data}

on quit:
    save yaml {@data}
    unload yaml {@data}

every 5 minutes:
    loop all loaded yaml:
        save loop-value
        # We add a small wait between each player data to prevent
        # a massive amount of lag if a lot of players are online
        # Adjust to suit your server's needs
        wait 2 ticks

command /clearOldData:
    trigger:
        set {_n} to 0 # lets create a counter
        loop all offline players:
            # here we are going to load each offline player's data, and check the difference between now and last-login
            # if grater than 100 days, we will delete their data
            # else we will just unload it and move onto the next
            load yaml "{@dir}/%uuid of loop-offline player%.yml" as "off-%uuid of loop-offline player%"
            set {_t} to yaml value "last-login" from "off-%uuid of loop-offline player%"
            if difference between now and {_t} > 50 days:
                delete yaml "off-%uuid of loop-offline player%"
                # lets just let the console know we're deleting this
                send "Deleting data for %loop-offline player%" to console
                # We will add 1 to {_n} so we know how many player data's we cleared
                add 1 to {_n}
            else:
                unload yaml "off-%uuid of loop-offline player%"
            wait 1 tick
        # Now we tell the console how many data's we cleared
        send "Removed player data for %{_n}% inactive player(s)" to console